# **B3 - Integration**
### **(B2_B0 Anchor with M_Geometry_Integration)**

# **Step 0 - Setup**

In [1]:
# ============================================================
# B3 Setup 0A — Mount Drive + Define Upstream / B3 Paths
# ============================================================
#
# Notebook:
#   B3_B0_B2_M_Geometry_Integration.ipynb
#
# Purpose
# -------
# B3 integrates:
#
#   B0 : unguided SAM2 anchor
#   B2 : B0-anchored semantic recovery
#   M1 : Marigold geometry refinement
#
# IMPORTANT
# ---------
# This notebook starts from FROZEN upstream artifacts.
#
# It does NOT initially:
#   - rerun SAN
#   - rerun SAM2
#   - rerun Marigold
#   - regenerate C/D semantic evidence
#   - regenerate A3c masks
#
# ============================================================

from google.colab import drive
from pathlib import Path

drive.mount("/content/drive")


# ------------------------------------------------------------
# Project root
# ------------------------------------------------------------

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/MSc_Project_ZeroShot_Counting"
)

RESULTS_ROOT = (
    PROJECT_ROOT
    / "results"
)


# ============================================================
# Frozen development subset
# ============================================================

B1_RESULTS_ROOT = (
    RESULTS_ROOT
    / "B1_experiments"
)

DEV100_FILE = (
    B1_RESULTS_ROOT
    / "subsets"
    / "FSC147_val_dev_100.csv"
)


# ============================================================
# B0
# ============================================================

B0_ROOT = (
    RESULTS_ROOT
    / "B0_dev100"
)

B0_PER_IMAGE_FILE = (
    B0_ROOT
    / "B0_dev100_per_image.csv"
)


# ============================================================
# B1 semantic evidence
# ============================================================

C_PER_IMAGE_FILE = (
    B1_RESULTS_ROOT
    / "Group_C"
    / "B1_Group_C_E_candidates_per_image.csv"
)

D_PER_IMAGE_FILE = (
    B1_RESULTS_ROOT
    / "Group_D"
    / "B1_Group_D_E_candidates_per_image.csv"
)


# ============================================================
# Frozen ABC / A3c artifacts
# ============================================================

ABC_ARTIFACT_ROOT = (
    B1_RESULTS_ROOT
    / "ABC_artifacts"
)

A3C_MASK_CACHE_DIR = (
    ABC_ARTIFACT_ROOT
    / "A3c_masks"
)

ABC_ARTIFACT_METADATA_DIR = (
    ABC_ARTIFACT_ROOT
    / "metadata"
)

A3C_MASK_INDEX_FILE = (
    ABC_ARTIFACT_METADATA_DIR
    / "A3c_mask_cache_index.csv"
)


# ============================================================
# B2
# ============================================================

B2_ROOT = (
    B1_RESULTS_ROOT
    / "B2_B0_Anchored_Semantic_Validation"
)

B2_CACHE_DIR = (
    B2_ROOT
    / "cache"
)

B2_TABLES_DIR = (
    B2_ROOT
    / "tables"
)

B2_METADATA_DIR = (
    B2_ROOT
    / "metadata"
)


# Frozen B0 masks reproduced inside B2
B0_MASK_INDEX_FILE = (
    B2_TABLES_DIR
    / "B0_mask_cache_index.csv"
)


# ------------------------------------------------------------
# Current B2 semantic-only counting-rule artifacts
# ------------------------------------------------------------

B2_GATE_SUMMARY_FILE = (
    B2_TABLES_DIR
    / "B0_C1_step3D_simple_gate_summary.csv"
)

B2_GATE_PER_IMAGE_FILE = (
    B2_TABLES_DIR
    / "B0_C1_step3D_simple_gate_per_image.csv"
)

B2_GATE_DENSITY_FILE = (
    B2_TABLES_DIR
    / "B0_C1_step3D_simple_gate_by_density.csv"
)

B2_GATE_MANIFEST_FILE = (
    B2_METADATA_DIR
    / "B0_recovery_step_4BB_simple_gate_manifest.json"
)


# ------------------------------------------------------------
# Useful B2 recovery-level artifacts
# ------------------------------------------------------------

B2_RAW_RECOVERY_PER_IMAGE_FILE = (
    B2_TABLES_DIR
    / "B0_plus_raw_recovery_counts_per_image.csv"
)

B2_STEP3D_PER_IMAGE_FILE = (
    B2_TABLES_DIR
    / "B0_C1_anchored_selective_D_counts_per_image.csv"
)

B2_STEP3D_POINTS_FILE = (
    B2_TABLES_DIR
    / "B0_C1_anchored_selective_D_points.csv"
)

B2_RECOVERY_POINTS_FILE = (
    B2_TABLES_DIR
    / "B0_recovery_semantic_points_long.csv"
)


# ============================================================
# M1 — Marigold geometry
# ============================================================

M1_ROOT = (
    RESULTS_ROOT
    / "M1_Marigold_Geometric_Diagnostics"
)

M1_DEPTH_CACHE_DIR = (
    M1_ROOT
    / "depth_cache"
)

M1_TABLES_DIR = (
    M1_ROOT
    / "tables"
)


# ------------------------------------------------------------
# Geometry component / proposal artifacts
# ------------------------------------------------------------

M1_7A_CANDIDATE_COMPONENT_FILE = (
    M1_TABLES_DIR
    / "M1_7A_split_candidate_components.csv"
)

M1_7B_RAW_PROPOSALS_FILE = (
    M1_TABLES_DIR
    / "M1_7B_raw_depth_split_proposals.csv"
)

M1_7B_IMAGE_SUMMARY_FILE = (
    M1_TABLES_DIR
    / "M1_7B_image_split_summary.csv"
)


M1_7B_ROOT = (
    M1_ROOT
    / "step7_geometry_refinement"
)

M1_7B_LABEL_DIR = (
    M1_7B_ROOT
    / "raw_split_label_maps"
)


# ------------------------------------------------------------
# Frozen geometry-count variants
# ------------------------------------------------------------

M1_7D_A_COMPONENT_FILE = (
    M1_TABLES_DIR
    / "M1_7D_A_component_geometry_count_contributions.csv"
)

M1_7D_A_IMAGE_FILE = (
    M1_TABLES_DIR
    / "M1_7D_A_image_geometry_counts.csv"
)

M1_7D_C_FEATURE_FILE = (
    M1_TABLES_DIR
    / "M1_7D_C_inference_only_image_features.csv"
)

M1_7D_D_POLICY_FILE = (
    M1_TABLES_DIR
    / "M1_7D_D_routing_policy_sensitivity.csv"
)

M1_7D_D_IMAGE_FILE = (
    M1_TABLES_DIR
    / "M1_7D_D_routing_image_evaluation.csv"
)


# ============================================================
# B3 output structure
# ============================================================

B3_ROOT = (
    RESULTS_ROOT
    / "B3_B0_B2_M_Geometry_Integration"
)

B3_TABLES_DIR = (
    B3_ROOT
    / "tables"
)

B3_METADATA_DIR = (
    B3_ROOT
    / "metadata"
)

B3_CACHE_DIR = (
    B3_ROOT
    / "cache"
)

B3_VIS_DIR = (
    B3_ROOT
    / "visualisations"
)


for path in [
    B3_ROOT,
    B3_TABLES_DIR,
    B3_METADATA_DIR,
    B3_CACHE_DIR,
    B3_VIS_DIR,
]:
    path.mkdir(
        parents=True,
        exist_ok=True,
    )


# ============================================================
# Existence checks
# ============================================================

REQUIRED_INPUT_FILES = {
    "dev100":
        DEV100_FILE,

    "B0 per-image":
        B0_PER_IMAGE_FILE,

    "C semantic evidence":
        C_PER_IMAGE_FILE,

    "D semantic evidence":
        D_PER_IMAGE_FILE,

    "A3c mask index":
        A3C_MASK_INDEX_FILE,

    "B0 mask index":
        B0_MASK_INDEX_FILE,

    "B2 gate summary":
        B2_GATE_SUMMARY_FILE,

    "B2 gate per-image":
        B2_GATE_PER_IMAGE_FILE,

    "B2 gate manifest":
        B2_GATE_MANIFEST_FILE,

    "M1 Step7A candidates":
        M1_7A_CANDIDATE_COMPONENT_FILE,

    "M1 Step7B raw proposals":
        M1_7B_RAW_PROPOSALS_FILE,

    "M1 Step7B image summary":
        M1_7B_IMAGE_SUMMARY_FILE,

    "M1 Step7D-A component counts":
        M1_7D_A_COMPONENT_FILE,

    "M1 Step7D-A image counts":
        M1_7D_A_IMAGE_FILE,

    "M1 Step7D-C inference features":
        M1_7D_C_FEATURE_FILE,

    "M1 Step7D-D routing policy":
        M1_7D_D_POLICY_FILE,

    "M1 Step7D-D image eval":
        M1_7D_D_IMAGE_FILE,
}


missing_inputs = [
    name
    for name, path in REQUIRED_INPUT_FILES.items()
    if not path.exists()
]


assert not missing_inputs, (
    "Missing required frozen B3 inputs:\n"
    + "\n".join(
        missing_inputs
    )
)


print("=" * 120)
print("B3 SETUP 0A — PATHS AND FROZEN INPUTS")
print("=" * 120)

print("Project root :", PROJECT_ROOT)
print("B3 root      :", B3_ROOT)

print("\nUpstream branches:")
print("  B0 :", B0_ROOT)
print("  B2 :", B2_ROOT)
print("  M1 :", M1_ROOT)

print("\nAll required frozen inputs: PASS")
print("Test set accessed          : NO")

Mounted at /content/drive
========================================================================================================================
B3 SETUP 0A — PATHS AND FROZEN INPUTS
========================================================================================================================
Project root : /content/drive/MyDrive/MSc_Project_ZeroShot_Counting
B3 root      : /content/drive/MyDrive/MSc_Project_ZeroShot_Counting/results/B3_B0_B2_M_Geometry_Integration

Upstream branches:
  B0 : /content/drive/MyDrive/MSc_Project_ZeroShot_Counting/results/B0_dev100
  B2 : /content/drive/MyDrive/MSc_Project_ZeroShot_Counting/results/B1_experiments/B2_B0_Anchored_Semantic_Validation
  M1 : /content/drive/MyDrive/MSc_Project_ZeroShot_Counting/results/M1_Marigold_Geometric_Diagnostics

All required frozen inputs: PASS
Test set accessed          : NO

In [ ]:
# ============================================================
# B3 Setup 0B — Load Frozen Upstream Tables
# ============================================================

import json
import numpy as np
import pandas as pd


# ------------------------------------------------------------
# Core identity tables
# ------------------------------------------------------------

dev100_df = pd.read_csv(
    DEV100_FILE
)

b0_df = pd.read_csv(
    B0_PER_IMAGE_FILE
)

c_df = pd.read_csv(
    C_PER_IMAGE_FILE
)

d_df = pd.read_csv(
    D_PER_IMAGE_FILE
)


# ------------------------------------------------------------
# Artifact indexes
# ------------------------------------------------------------

a3c_mask_index_df = pd.read_csv(
    A3C_MASK_INDEX_FILE
)

b0_mask_index_df = pd.read_csv(
    B0_MASK_INDEX_FILE
)


# ------------------------------------------------------------
# B2 semantic-only outputs
# ------------------------------------------------------------

b2_gate_summary_df = pd.read_csv(
    B2_GATE_SUMMARY_FILE
)

b2_gate_per_image_df = pd.read_csv(
    B2_GATE_PER_IMAGE_FILE
)

b2_gate_density_df = pd.read_csv(
    B2_GATE_DENSITY_FILE
)


with open(
    B2_GATE_MANIFEST_FILE,
    "r",
) as f:

    b2_gate_manifest = json.load(
        f
    )


# ------------------------------------------------------------
# M1 geometry outputs
# ------------------------------------------------------------

m1_7a_candidates_df = pd.read_csv(
    M1_7A_CANDIDATE_COMPONENT_FILE
)

m1_7b_raw_proposals_df = pd.read_csv(
    M1_7B_RAW_PROPOSALS_FILE
)

m1_7b_image_summary_df = pd.read_csv(
    M1_7B_IMAGE_SUMMARY_FILE
)

m1_7d_component_counts_df = pd.read_csv(
    M1_7D_A_COMPONENT_FILE
)

m1_7d_image_counts_df = pd.read_csv(
    M1_7D_A_IMAGE_FILE
)

m1_7d_inference_features_df = pd.read_csv(
    M1_7D_C_FEATURE_FILE
)

m1_7d_routing_policy_df = pd.read_csv(
    M1_7D_D_POLICY_FILE
)

m1_7d_routing_image_df = pd.read_csv(
    M1_7D_D_IMAGE_FILE
)


# ------------------------------------------------------------
# Basic expected sizes
# ------------------------------------------------------------

assert len(dev100_df) == 100
assert len(b0_df) == 100

assert len(c_df) == 300
assert len(d_df) == 500

assert len(a3c_mask_index_df) == 100
assert len(b0_mask_index_df) == 100

assert len(m1_7a_candidates_df) == 2554
assert len(m1_7b_image_summary_df) == 100
assert len(m1_7d_image_counts_df) == 100
assert len(m1_7d_inference_features_df) == 100


print("=" * 120)
print("B3 SETUP 0B — LOAD FROZEN TABLES")
print("=" * 120)

print("dev100                   :", len(dev100_df))
print("B0 images                :", len(b0_df))
print("C rows                    :", len(c_df))
print("D rows                    :", len(d_df))

print("A3c mask artifacts        :", len(a3c_mask_index_df))
print("B0 mask artifacts         :", len(b0_mask_index_df))

print("M1 original components    :", len(m1_7a_candidates_df))
print("M1 image geometry rows    :", len(m1_7d_image_counts_df))

print("\nSetup 0B: PASS")

========================================================================================================================
B3 SETUP 0B — LOAD FROZEN TABLES
========================================================================================================================
dev100                   : 100
B0 images                : 100
C rows                    : 300
D rows                    : 500
A3c mask artifacts        : 100
B0 mask artifacts         : 100
M1 original components    : 2554
M1 image geometry rows    : 100

Setup 0B: PASS

In [ ]:
# ============================================================
# B3 Setup 0C — Exact Cross-Notebook Alignment Checks
# ============================================================

IMAGE_KEY_COLS = [
    "dataset_index",
    "image_id",
    "category",
    "density_stratum",
    "gt_count",
]


# ------------------------------------------------------------
# Authoritative dev100 identity
# ------------------------------------------------------------

dev100_identity_df = (
    dev100_df[
        IMAGE_KEY_COLS
    ]
    .copy()
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


assert len(
    dev100_identity_df
) == 100

assert (
    dev100_identity_df[
        "dataset_index"
    ]
    .is_unique
)

assert (
    dev100_identity_df[
        "image_id"
    ]
    .is_unique
)


# ------------------------------------------------------------
# Helper
# ------------------------------------------------------------

def assert_exact_image_alignment(
    reference_df,
    other_df,
    other_name,
):

    available_keys = [
        col
        for col in IMAGE_KEY_COLS
        if col in other_df.columns
    ]

    assert (
        "dataset_index"
        in
        available_keys
    ), (
        f"{other_name}: dataset_index missing"
    )


    # If full identity is present, compare all identity fields.
    if set(
        IMAGE_KEY_COLS
    ).issubset(
        other_df.columns
    ):

        other_identity = (
            other_df[
                IMAGE_KEY_COLS
            ]
            .drop_duplicates()
            .sort_values(
                "dataset_index"
            )
            .reset_index(
                drop=True
            )
        )

        assert len(
            other_identity
        ) == 100


        merged = (
            reference_df
            .merge(
                other_identity,
                on=IMAGE_KEY_COLS,
                how="outer",
                indicator=True,
            )
        )


        assert (
            merged[
                "_merge"
            ]
            .eq(
                "both"
            )
            .all()
        ), (
            f"{other_name}: image identity mismatch"
        )

    else:

        observed_indices = (
            other_df[
                "dataset_index"
            ]
            .drop_duplicates()
            .sort_values()
            .to_numpy()
        )

        expected_indices = (
            reference_df[
                "dataset_index"
            ]
            .sort_values()
            .to_numpy()
        )

        assert np.array_equal(
            observed_indices,
            expected_indices,
        ), (
            f"{other_name}: dataset_index mismatch"
        )


# ------------------------------------------------------------
# Run alignment checks
# ------------------------------------------------------------

assert_exact_image_alignment(
    dev100_identity_df,
    b0_df,
    "B0",
)

assert_exact_image_alignment(
    dev100_identity_df,
    c_df,
    "C",
)

assert_exact_image_alignment(
    dev100_identity_df,
    d_df,
    "D",
)

assert_exact_image_alignment(
    dev100_identity_df,
    a3c_mask_index_df,
    "A3c mask index",
)

assert_exact_image_alignment(
    dev100_identity_df,
    b0_mask_index_df,
    "B0 mask index",
)

assert_exact_image_alignment(
    dev100_identity_df,
    m1_7b_image_summary_df,
    "M1 Step7B image summary",
)

assert_exact_image_alignment(
    dev100_identity_df,
    m1_7d_image_counts_df,
    "M1 Step7D image counts",
)

assert_exact_image_alignment(
    dev100_identity_df,
    m1_7d_inference_features_df,
    "M1 Step7D inference features",
)


# ------------------------------------------------------------
# Candidate identities
# ------------------------------------------------------------

assert sorted(
    c_df[
        "candidate_id"
    ]
    .unique()
    .tolist()
) == [
    "C1",
    "C2b",
    "C2c",
]


expected_D = [
    "D1",
    "D4",
    "D5-768",
    "D6B-T-native",
    "D6B9-strict",
]


assert sorted(
    d_df[
        "candidate_id"
    ]
    .unique()
    .tolist()
) == sorted(
    expected_D
)


# ------------------------------------------------------------
# Frozen geometry identities
# ------------------------------------------------------------

assert len(
    m1_7a_candidates_df
) == 2554

assert int(
    m1_7a_candidates_df[
        "split_candidate"
    ]
    .sum()
) == 699


assert int(
    m1_7d_image_counts_df[
        "G0_geometry_count"
    ]
    .sum()
) == 2554


assert int(
    m1_7d_image_counts_df[
        "G2_geometry_count"
    ]
    .sum()
) == 6065


assert int(
    m1_7d_image_counts_df[
        "G3_geometry_count"
    ]
    .sum()
) == 5001


print("=" * 120)
print("B3 SETUP 0C — CROSS-NOTEBOOK ALIGNMENT")
print("=" * 120)

print("B0 aligned             : PASS")
print("C aligned              : PASS")
print("D aligned              : PASS")
print("A3c artifacts aligned  : PASS")
print("B0 masks aligned       : PASS")
print("M1 geometry aligned    : PASS")

print("\nFrozen geometry identities:")
print("  A3c components       : 2554")
print("  split candidates     : 699")
print("  G2 geometry total    : 6065")
print("  G3 geometry total    : 5001")

print("\nSetup 0C: PASS")

========================================================================================================================
B3 SETUP 0C — CROSS-NOTEBOOK ALIGNMENT
========================================================================================================================
B0 aligned             : PASS
C aligned              : PASS
D aligned              : PASS
A3c artifacts aligned  : PASS
B0 masks aligned       : PASS
M1 geometry aligned    : PASS

Frozen geometry identities:
  A3c components       : 2554
  split candidates     : 699
  G2 geometry total    : 6065
  G3 geometry total    : 5001

Setup 0C: PASS

In [ ]:
# ============================================================
# B3 Setup 0D — Freeze Current B2 Semantic-Only Reference
# ============================================================
#
# Frozen B2 reference:
#
#   Base:
#       B0_plus_C1_raw
#
#   Additional recovery:
#       Step3D D6B-T-native, C1-supported
#
#   Weight:
#       alpha = 0.5
#
#   Gate:
#       C1_added >= 10
#
# This is carried into B3 unchanged.
# ============================================================

B2_REFERENCE_GATE_ID = (
    "C1added_ge_10"
)

B2_REFERENCE_ALPHA = 0.5


# ------------------------------------------------------------
# Extract exact saved B2 reference rows
# ------------------------------------------------------------

b2_reference_df = (
    b2_gate_per_image_df[
        b2_gate_per_image_df[
            "gate_id"
        ]
        ==
        B2_REFERENCE_GATE_ID
    ]
    .copy()
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


assert len(
    b2_reference_df
) == 100


assert (
    b2_reference_df[
        "alpha"
    ]
    .eq(
        B2_REFERENCE_ALPHA
    )
    .all()
)


# ------------------------------------------------------------
# Exact image alignment
# ------------------------------------------------------------

assert_exact_image_alignment(
    dev100_identity_df,
    b2_reference_df,
    "B2 reference",
)


# ------------------------------------------------------------
# Compute metrics from the saved per-image reference
# ------------------------------------------------------------

b2_gt = (
    b2_reference_df[
        "gt_count"
    ]
    .to_numpy(
        dtype=float
    )
)

b2_pred = (
    b2_reference_df[
        "predicted_count"
    ]
    .to_numpy(
        dtype=float
    )
)

b2_error = (
    b2_pred
    -
    b2_gt
)


B2_REFERENCE_MAE = float(
    np.mean(
        np.abs(
            b2_error
        )
    )
)

B2_REFERENCE_RMSE = float(
    np.sqrt(
        np.mean(
            b2_error ** 2
        )
    )
)

B2_REFERENCE_SIGNED_ERROR = float(
    np.mean(
        b2_error
    )
)


print("=" * 120)
print("B3 SETUP 0D — FROZEN B2 SEMANTIC-ONLY REFERENCE")
print("=" * 120)

print("Gate                   :", B2_REFERENCE_GATE_ID)
print("Alpha                  :", B2_REFERENCE_ALPHA)

print("\nMAE                    :", B2_REFERENCE_MAE)
print("RMSE                   :", B2_REFERENCE_RMSE)
print("Mean signed error      :", B2_REFERENCE_SIGNED_ERROR)

print("\nB2 rows                :", len(b2_reference_df))
print("Test set accessed      : NO")

print("\nSetup 0D: PASS")

========================================================================================================================
B3 SETUP 0D — FROZEN B2 SEMANTIC-ONLY REFERENCE
========================================================================================================================
Gate                   : C1added_ge_10
Alpha                  : 0.5

MAE                    : 70.9
RMSE                   : 260.2727223509986
Mean signed error      : -62.03

B2 rows                : 100
Test set accessed      : NO

Setup 0D: PASS

In [ ]:
# ============================================================
# B3 Setup 0E — Freeze Provisional Geometry Configuration
# ============================================================
#
# Geometry mechanism carried from M1:
#
# Candidate selection:
#   within-image A3c component-area >= 75th percentile
#
# Depth refinement:
#   Marigold depth
#   deterministic 1-D k-means, k=2
#   4-connected spatial pieces
#
# Fragment retention:
#   anchors
#   +
#   satellites with:
#
#       proposal_area_fraction_of_original >= 0.001
#
# This is G2.
#
# Provisional image-level M1 routing result:
#
#   candidate_area_fraction >= 0.85
#
# NOTE:
# The 0.85 image gate was selected on dev100 and remains
# provisional. B3 should not silently treat it as final.
# ============================================================

B3_GEOMETRY_VARIANT = "G2"

B3_SPLIT_CANDIDATE_QUANTILE = 0.75

B3_SATELLITE_PARENT_THRESHOLD = 0.001

B3_M1_IMAGE_GATE_FEATURE = (
    "candidate_area_fraction"
)

B3_M1_IMAGE_GATE_THRESHOLD = 0.85


# ------------------------------------------------------------
# Build frozen inference-only geometry table
# ------------------------------------------------------------

geometry_reference_df = (
    m1_7d_inference_features_df[
        [
            "dataset_index",
            "candidate_area_fraction",
            "G1_increment_per_G0",
            "G2_increment_per_G0",
            "G2_raw_increment_retention",
        ]
    ]
    .merge(
        m1_7d_image_counts_df[
            [
                "dataset_index",
                "G0_geometry_count",
                "G2_geometry_count",
            ]
        ],
        on="dataset_index",
        how="left",
        validate="one_to_one",
    )
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


assert len(
    geometry_reference_df
) == 100


geometry_reference_df[
    "M1_G2_gate_ON"
] = (
    geometry_reference_df[
        B3_M1_IMAGE_GATE_FEATURE
    ]
    >=
    B3_M1_IMAGE_GATE_THRESHOLD
)


print("=" * 120)
print("B3 SETUP 0E — PROVISIONAL M1 GEOMETRY CONFIGURATION")
print("=" * 120)

print("Geometry variant               :", B3_GEOMETRY_VARIANT)
print(
    "Step-7A candidate quantile     :",
    B3_SPLIT_CANDIDATE_QUANTILE,
)

print(
    "Satellite parent-area threshold:",
    B3_SATELLITE_PARENT_THRESHOLD,
)

print(
    "Provisional image gate         :",
    f"{B3_M1_IMAGE_GATE_FEATURE} >= "
    f"{B3_M1_IMAGE_GATE_THRESHOLD}",
)

print(
    "Images gate ON                 :",
    int(
        geometry_reference_df[
            "M1_G2_gate_ON"
        ]
        .sum()
    ),
)

print("\nGeometry actually injected into B2 : NO")
print("B2 modified                         : NO")
print("Test set accessed                   : NO")

print("\nSetup 0E: PASS")

========================================================================================================================
B3 SETUP 0E — PROVISIONAL M1 GEOMETRY CONFIGURATION
========================================================================================================================
Geometry variant               : G2
Step-7A candidate quantile     : 0.75
Satellite parent-area threshold: 0.001
Provisional image gate         : candidate_area_fraction >= 0.85
Images gate ON                 : 57

Geometry actually injected into B2 : NO
B2 modified                         : NO
Test set accessed                   : NO

Setup 0E: PASS

# **Step 1 - Exact Baseline Verification**

In [ ]:
# ============================================================
# B3 Step 1 — Exact Baseline Verification / Integration Check
# ============================================================
#
# Purpose
# -------
# Put the frozen upstream counting branches side-by-side on
# the exact same FSC-147 dev100 images.
#
# This step is a VERIFICATION step only.
#
# Systems compared:
#
#   B0
#       Unguided SAM2 AMG anchor.
#
#   B2-S
#       Frozen semantic-only B2 reference:
#       B0 + gated/weighted semantic recovery.
#
#   M-G0
#       Original A3c connected-component counter.
#
#   M-G2-global
#       G2 geometry refinement applied globally.
#
#   M-G2-gated
#       G2 geometry refinement applied only when:
#
#           candidate_area_fraction >= 0.85
#
#
# IMPORTANT
# ---------
# No geometry is injected into B2 in this step.
# No new threshold is tuned.
# No model inference is rerun.
# Test set remains untouched.
#
# ============================================================

import numpy as np
import pandas as pd


print("=" * 120)
print("B3 STEP 1 — EXACT BASELINE VERIFICATION / INTEGRATION CHECK")
print("=" * 120)


# ------------------------------------------------------------
# 1. Guards
# ------------------------------------------------------------

assert "dev100_identity_df" in globals()
assert "b0_df" in globals()
assert "b2_reference_df" in globals()
assert "geometry_reference_df" in globals()
assert "m1_7d_image_counts_df" in globals()

assert len(dev100_identity_df) == 100
assert len(b0_df) == 100
assert len(b2_reference_df) == 100
assert len(geometry_reference_df) == 100
assert len(m1_7d_image_counts_df) == 100


# ------------------------------------------------------------
# 2. Resolve B0 prediction column safely
#
# The exact upstream B0 table schema may use pred_count or a
# similar stored name. We resolve it explicitly rather than
# silently assuming.
# ------------------------------------------------------------

B0_PRED_CANDIDATES = [
    "pred_count",
    "prediction",
    "predicted_count",
    "selected_count",
    "raw_count",
]


b0_pred_col = None

for candidate_col in B0_PRED_CANDIDATES:
    if candidate_col in b0_df.columns:
        b0_pred_col = candidate_col
        break


assert b0_pred_col is not None, (
    "Could not identify B0 prediction column.\n"
    f"Available B0 columns:\n{list(b0_df.columns)}"
)


print("\nResolved B0 prediction column:")
print(" ", b0_pred_col)


# ------------------------------------------------------------
# 3. Resolve B2 prediction column safely
# ------------------------------------------------------------

B2_PRED_CANDIDATES = [
    "predicted_count",
    "pred_count",
    "prediction",
]


b2_pred_col = None

for candidate_col in B2_PRED_CANDIDATES:
    if candidate_col in b2_reference_df.columns:
        b2_pred_col = candidate_col
        break


assert b2_pred_col is not None, (
    "Could not identify B2 prediction column.\n"
    f"Available B2 columns:\n{list(b2_reference_df.columns)}"
)


print("Resolved B2 prediction column:")
print(" ", b2_pred_col)


# ------------------------------------------------------------
# 4. Build exact 100-image comparison table
# ------------------------------------------------------------

b3_step1_df = (
    dev100_identity_df[
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",
        ]
    ]
    .merge(
        b0_df[
            [
                "dataset_index",
                b0_pred_col,
            ]
        ]
        .rename(
            columns={
                b0_pred_col:
                    "B0_count",
            }
        ),
        on="dataset_index",
        how="left",
        validate="one_to_one",
    )
    .merge(
        b2_reference_df[
            [
                "dataset_index",
                b2_pred_col,
            ]
        ]
        .rename(
            columns={
                b2_pred_col:
                    "B2_S_count",
            }
        ),
        on="dataset_index",
        how="left",
        validate="one_to_one",
    )
    .merge(
        m1_7d_image_counts_df[
            [
                "dataset_index",
                "G0_geometry_count",
                "G2_geometry_count",
            ]
        ]
        .rename(
            columns={
                "G0_geometry_count":
                    "M_G0_count",

                "G2_geometry_count":
                    "M_G2_global_count",
            }
        ),
        on="dataset_index",
        how="left",
        validate="one_to_one",
    )
    .merge(
        geometry_reference_df[
            [
                "dataset_index",
                "candidate_area_fraction",
                "M1_G2_gate_ON",
            ]
        ],
        on="dataset_index",
        how="left",
        validate="one_to_one",
    )
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


assert len(b3_step1_df) == 100


# ------------------------------------------------------------
# 5. Exact completeness checks
# ------------------------------------------------------------

required_step1_cols = [
    "gt_count",
    "B0_count",
    "B2_S_count",
    "M_G0_count",
    "M_G2_global_count",
    "candidate_area_fraction",
    "M1_G2_gate_ON",
]


assert (
    b3_step1_df[
        required_step1_cols
    ]
    .notna()
    .all()
    .all()
), (
    "Missing values detected in aligned Step-1 table."
)


# ------------------------------------------------------------
# 6. Build standalone gated M1 count
#
# This reproduces the provisional M1 standalone routing rule:
#
#   if candidate_area_fraction >= 0.85:
#       use G2
#   else:
#       use G0
#
# ------------------------------------------------------------

b3_step1_df[
    "M_G2_gated_count"
] = np.where(
    b3_step1_df[
        "M1_G2_gate_ON"
    ],
    b3_step1_df[
        "M_G2_global_count"
    ],
    b3_step1_df[
        "M_G0_count"
    ],
).astype(float)


# ------------------------------------------------------------
# 7. Structural frozen-identity checks
# ------------------------------------------------------------

assert int(
    b3_step1_df[
        "M_G0_count"
    ]
    .sum()
) == 2554


assert int(
    b3_step1_df[
        "M_G2_global_count"
    ]
    .sum()
) == 6065


assert int(
    b3_step1_df[
        "M1_G2_gate_ON"
    ]
    .sum()
) == 57


# ------------------------------------------------------------
# 8. Metric helper
# ------------------------------------------------------------

def compute_count_metrics_b3_step1(
    df,
    pred_col,
    system_name,
):

    gt = (
        df[
            "gt_count"
        ]
        .to_numpy(
            dtype=float
        )
    )

    pred = (
        df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    signed = (
        pred
        -
        gt
    )

    abs_error = np.abs(
        signed
    )

    squared_error = (
        signed
        ** 2
    )

    return {
        "system":
            system_name,

        "prediction_column":
            pred_col,

        "num_images":
            int(
                len(
                    df
                )
            ),

        "total_GT":
            int(
                gt.sum()
            ),

        "total_prediction":
            float(
                pred.sum()
            ),

        "mean_GT":
            float(
                gt.mean()
            ),

        "mean_prediction":
            float(
                pred.mean()
            ),

        "MAE":
            float(
                abs_error.mean()
            ),

        "RMSE":
            float(
                np.sqrt(
                    squared_error.mean()
                )
            ),

        "mean_signed_error":
            float(
                signed.mean()
            ),

        "median_signed_error":
            float(
                np.median(
                    signed
                )
            ),

        "under_images":
            int(
                (
                    signed
                    <
                    0
                )
                .sum()
            ),

        "exact_images":
            int(
                (
                    signed
                    ==
                    0
                )
                .sum()
            ),

        "over_images":
            int(
                (
                    signed
                    >
                    0
                )
                .sum()
            ),
    }


# ------------------------------------------------------------
# 9. Overall baseline table
# ------------------------------------------------------------

SYSTEMS_B3_STEP1 = [
    (
        "B0",
        "B0_count",
    ),

    (
        "B2-S",
        "B2_S_count",
    ),

    (
        "M-G0",
        "M_G0_count",
    ),

    (
        "M-G2-global",
        "M_G2_global_count",
    ),

    (
        "M-G2-gated",
        "M_G2_gated_count",
    ),
]


overall_rows_b3_step1 = []


for system_name, pred_col in SYSTEMS_B3_STEP1:

    overall_rows_b3_step1.append(
        compute_count_metrics_b3_step1(
            df=
                b3_step1_df,

            pred_col=
                pred_col,

            system_name=
                system_name,
        )
    )


b3_step1_overall_df = (
    pd.DataFrame(
        overall_rows_b3_step1
    )
)


# ------------------------------------------------------------
# 10. Verify exact known checkpoints
#
# These are regression checks, not tuning.
# ------------------------------------------------------------

b0_row = (
    b3_step1_overall_df[
        b3_step1_overall_df[
            "system"
        ]
        ==
        "B0"
    ]
    .iloc[0]
)


b2_row = (
    b3_step1_overall_df[
        b3_step1_overall_df[
            "system"
        ]
        ==
        "B2-S"
    ]
    .iloc[0]
)


mg0_row = (
    b3_step1_overall_df[
        b3_step1_overall_df[
            "system"
        ]
        ==
        "M-G0"
    ]
    .iloc[0]
)


mg2_global_row = (
    b3_step1_overall_df[
        b3_step1_overall_df[
            "system"
        ]
        ==
        "M-G2-global"
    ]
    .iloc[0]
)


mg2_gated_row = (
    b3_step1_overall_df[
        b3_step1_overall_df[
            "system"
        ]
        ==
        "M-G2-gated"
    ]
    .iloc[0]
)


# B0 known checkpoint
assert np.isclose(
    float(
        b0_row[
            "MAE"
        ]
    ),
    80.69,
    atol=1e-6,
), (
    f"B0 MAE mismatch: {b0_row['MAE']}"
)


# B2 frozen checkpoint
assert np.isclose(
    float(
        b2_row[
            "MAE"
        ]
    ),
    70.90,
    atol=1e-6,
), (
    f"B2-S MAE mismatch: {b2_row['MAE']}"
)


# M-G0 checkpoint
assert np.isclose(
    float(
        mg0_row[
            "MAE"
        ]
    ),
    79.67,
    atol=1e-6,
), (
    f"M-G0 MAE mismatch: {mg0_row['MAE']}"
)


# M-G2-global checkpoint
assert np.isclose(
    float(
        mg2_global_row[
            "MAE"
        ]
    ),
    71.70,
    atol=1e-6,
), (
    f"M-G2-global MAE mismatch: {mg2_global_row['MAE']}"
)


# M-G2-gated checkpoint
assert np.isclose(
    float(
        mg2_gated_row[
            "MAE"
        ]
    ),
    69.60,
    atol=1e-6,
), (
    f"M-G2-gated MAE mismatch: {mg2_gated_row['MAE']}"
)


# ------------------------------------------------------------
# 11. Density-stratum metrics
# ------------------------------------------------------------

stratum_rows_b3_step1 = []


for stratum in [
    "S1_0_20",
    "S2_20_40",
    "S3_40_60",
    "S4_60_80",
    "S5_80_95",
    "S6_95_100",
]:

    sdf = (
        b3_step1_df[
            b3_step1_df[
                "density_stratum"
            ]
            ==
            stratum
        ]
    )


    for system_name, pred_col in SYSTEMS_B3_STEP1:

        gt = (
            sdf[
                "gt_count"
            ]
            .to_numpy(
                dtype=float
            )
        )

        pred = (
            sdf[
                pred_col
            ]
            .to_numpy(
                dtype=float
            )
        )

        signed = (
            pred
            -
            gt
        )


        stratum_rows_b3_step1.append(
            {
                "density_stratum":
                    stratum,

                "system":
                    system_name,

                "num_images":
                    int(
                        len(
                            sdf
                        )
                    ),

                "MAE":
                    float(
                        np.abs(
                            signed
                        )
                        .mean()
                    ),

                "RMSE":
                    float(
                        np.sqrt(
                            np.mean(
                                signed
                                ** 2
                            )
                        )
                    ),

                "mean_signed_error":
                    float(
                        signed.mean()
                    ),
            }
        )


b3_step1_stratum_df = (
    pd.DataFrame(
        stratum_rows_b3_step1
    )
)


# ------------------------------------------------------------
# 12. Save Step-1 integration checkpoint
# ------------------------------------------------------------

B3_STEP1_IMAGE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step1_baseline_verification_per_image.csv"
)

B3_STEP1_OVERALL_FILE = (
    B3_TABLES_DIR
    /
    "B3_step1_baseline_verification_overall.csv"
)

B3_STEP1_STRATUM_FILE = (
    B3_TABLES_DIR
    /
    "B3_step1_baseline_verification_by_density.csv"
)


b3_step1_df.to_csv(
    B3_STEP1_IMAGE_FILE,
    index=False,
)

b3_step1_overall_df.to_csv(
    B3_STEP1_OVERALL_FILE,
    index=False,
)

b3_step1_stratum_df.to_csv(
    B3_STEP1_STRATUM_FILE,
    index=False,
)


# ------------------------------------------------------------
# 13. Report — overall
# ------------------------------------------------------------

print("\nOverall frozen baseline verification")
print("------------------------------------")

display(
    b3_step1_overall_df[
        [
            "system",
            "total_prediction",
            "mean_prediction",
            "MAE",
            "RMSE",
            "mean_signed_error",
            "under_images",
            "exact_images",
            "over_images",
        ]
    ]
)


# ------------------------------------------------------------
# 14. Report — density-stratum MAE
# ------------------------------------------------------------

print("\nMAE by density stratum")
print("----------------------")

display(
    b3_step1_stratum_df
    .pivot(
        index=
            "density_stratum",

        columns=
            "system",

        values=
            "MAE",
    )
)


# ------------------------------------------------------------
# 15. Regression checkpoint summary
# ------------------------------------------------------------

print("\nKnown checkpoint reproduction")
print("-----------------------------")

print(
    "B0 MAE             :",
    float(
        b0_row[
            "MAE"
        ]
    ),
)

print(
    "B2-S MAE           :",
    float(
        b2_row[
            "MAE"
        ]
    ),
)

print(
    "M-G0 MAE           :",
    float(
        mg0_row[
            "MAE"
        ]
    ),
)

print(
    "M-G2-global MAE    :",
    float(
        mg2_global_row[
            "MAE"
        ]
    ),
)

print(
    "M-G2-gated MAE     :",
    float(
        mg2_gated_row[
            "MAE"
        ]
    ),
)


# ------------------------------------------------------------
# 16. Protocol report
# ------------------------------------------------------------

print("\nFrozen B0 reused                   : YES")
print("Frozen B2 semantic-only reused     : YES")
print("Frozen M1 geometry reused          : YES")

print("\nNew semantic evidence generated    : NO")
print("New SAM2 inference run             : NO")
print("New Marigold inference run         : NO")

print("\nGeometry injected into B2          : NO")
print("Routing threshold changed          : NO")
print("B2 semantic rule changed           : NO")

print("\nAll known checkpoints reproduced   : YES")
print("Test set accessed                  : NO")

print("\nB3 Step 1: PASS")

========================================================================================================================
B3 STEP 1 — EXACT BASELINE VERIFICATION / INTEGRATION CHECK
========================================================================================================================

Resolved B0 prediction column:
  pred_count
Resolved B2 prediction column:
  predicted_count

Overall frozen baseline verification
------------------------------------

,system,total_prediction,mean_prediction,MAE,RMSE,mean_signed_error,under_images,exact_images,over_images
0,B0,2298.0,22.98,80.69,270.233880,-77.47,76,4,20
1,B2-S,3842.0,38.42,70.90,260.272722,-62.03,46,7,47
2,M-G0,2554.0,25.54,79.67,263.541363,-74.91,68,5,27
3,M-G2-global,6065.0,60.65,71.70,240.928620,-39.80,31,2,67
4,M-G2-gated,4643.0,46.43,69.60,242.624236,-54.02,49,6,45

MAE by density stratum
----------------------

system               B0     B2-S    M-G0  M-G2-gated  M-G2-global
density_stratum
S1_0_20            5.15    5.575    5.25        9.85        13.00
S2_20_40           6.55    7.950    8.30       15.85        23.65
S3_40_60          14.95    9.950   11.20       15.85        22.65
S4_60_80          34.30   21.225   26.50       18.75        31.60
S5_80_95          62.10   40.550   74.60       64.90        43.40
S6_95_100        622.90  579.050  619.60      510.50       491.80

Known checkpoint reproduction
-----------------------------
B0 MAE             : 80.69
B2-S MAE           : 70.9
M-G0 MAE           : 79.67
M-G2-global MAE    : 71.7
M-G2-gated MAE     : 69.6

Frozen B0 reused                   : YES
Frozen B2 semantic-only reused     : YES
Frozen M1 geometry reused          : YES

New semantic evidence generated    : NO
New SAM2 inference run             : NO
New Marigold inference run         : NO

Geometry injected into B2          : NO
Routing threshold changed          : NO
B2 semantic rule changed           : NO

All known checkpoints reproduced   : YES
Test set accessed                  : NO

B3 Step 1: PASS

# **Step 2 — Geometry Contribution to B2-S Recovery**

In [ ]:
# ============================================================
# B3 Step 2A — Map B2 C1 Recovery to M1/A3c Components
# ============================================================
#
# Purpose
# -------
# Build the exact bridge between:
#
#   B2 semantic recovery
#
# and
#
#   M1 geometry refinement.
#
#
# Key identity
# ------------
#
# Frozen C1 is generated from the frozen A3c mask using
# scipy.ndimage.label() connected components.
#
# ABC emits exactly one centroid point per connected component,
# in component-ID order:
#
#       point_index = 0  -> component_id = 1
#       point_index = 1  -> component_id = 2
#       ...
#
# Therefore:
#
#       original_component_id = point_index + 1
#
#
# This avoids using centroid-pixel containment as the primary
# mapping mechanism.
#
#
# This step DOES NOT:
#
#   - change B2 count
#   - add geometry count
#   - change alpha
#   - change B2 gate
#   - change M1 thresholds
#   - use GT to make an inference decision
#   - access test set
#
# ============================================================

import numpy as np
import pandas as pd


print("=" * 120)
print("B3 STEP 2A — MAP B2 C1 RECOVERY TO M1 / A3c COMPONENTS")
print("=" * 120)


# ------------------------------------------------------------
# 1. Guards
# ------------------------------------------------------------

assert "B2_RECOVERY_POINTS_FILE" in globals()
assert B2_RECOVERY_POINTS_FILE.exists()

assert "m1_7a_candidates_df" in globals()
assert "m1_7d_component_counts_df" in globals()
assert "geometry_reference_df" in globals()
assert "c_df" in globals()

assert len(m1_7a_candidates_df) == 2554
assert len(m1_7d_component_counts_df) == 2554
assert len(geometry_reference_df) == 100


# ------------------------------------------------------------
# 2. Load authoritative B2 semantic recovery point table
# ------------------------------------------------------------

recovery_points_b3_2a_df = pd.read_csv(
    B2_RECOVERY_POINTS_FILE
)


required_recovery_cols_2a = {
    "branch",
    "candidate_id",
    "dataset_index",
    "image_id",
    "point_index",
    "x",
    "y",
    "covered_by_b0",
    "recovery_candidate",
}


assert required_recovery_cols_2a.issubset(
    recovery_points_b3_2a_df.columns
), (
    "Required B2 recovery-point columns missing.\n"
    f"Required: {sorted(required_recovery_cols_2a)}\n"
    f"Found: {list(recovery_points_b3_2a_df.columns)}"
)


print(
    "\nLoaded B2 recovery-point rows:",
    len(recovery_points_b3_2a_df),
)


# ------------------------------------------------------------
# 3. Keep frozen C1 only
# ------------------------------------------------------------

c1_recovery_all_2a_df = (
    recovery_points_b3_2a_df[
        (
            recovery_points_b3_2a_df[
                "branch"
            ]
            .astype(str)
            .eq("C")
        )
        &
        (
            recovery_points_b3_2a_df[
                "candidate_id"
            ]
            .astype(str)
            .eq("C1")
        )
    ]
    .copy()
    .sort_values(
        [
            "dataset_index",
            "point_index",
        ]
    )
    .reset_index(
        drop=True
    )
)


# Frozen C1 identity
assert len(
    c1_recovery_all_2a_df
) == 2554, (
    f"Expected 2554 frozen C1 points, "
    f"found {len(c1_recovery_all_2a_df)}"
)


assert (
    c1_recovery_all_2a_df[
        "dataset_index"
    ]
    .nunique()
    ==
    100
)


# ------------------------------------------------------------
# 4. Exact C1 point -> A3c component identity
#
# C1 point_index is zero-based.
# scipy connected-component IDs are one-based.
# ------------------------------------------------------------

c1_recovery_all_2a_df[
    "original_component_id"
] = (
    c1_recovery_all_2a_df[
        "point_index"
    ]
    .astype(int)
    +
    1
)


# ------------------------------------------------------------
# 5. Check component IDs against authoritative M1 inventory
# ------------------------------------------------------------

m1_component_keys_2a_df = (
    m1_7a_candidates_df[
        [
            "dataset_index",
            "component_id",
        ]
    ]
    .rename(
        columns={
            "component_id":
                "original_component_id",
        }
    )
    .drop_duplicates()
)


assert len(
    m1_component_keys_2a_df
) == 2554


component_identity_check_2a_df = (
    c1_recovery_all_2a_df[
        [
            "dataset_index",
            "original_component_id",
        ]
    ]
    .merge(
        m1_component_keys_2a_df.assign(
            component_exists_in_M1=True
        ),
        on=[
            "dataset_index",
            "original_component_id",
        ],
        how="left",
        validate="one_to_one",
    )
)


assert (
    component_identity_check_2a_df[
        "component_exists_in_M1"
    ]
    .fillna(False)
    .all()
), (
    "At least one C1 point_index+1 component identity "
    "does not exist in the M1 A3c component inventory."
)


print(
    "C1 -> A3c component identity:",
    "2554/2554 exact"
)


# ------------------------------------------------------------
# 6. Strong coordinate sanity check
#
# ABC C1 points are geometric centroids of the same frozen
# connected components.
#
# Compare them with M1's independently reconstructed
# component centroids.
# ------------------------------------------------------------

required_m1_candidate_cols_2a = {
    "dataset_index",
    "component_id",
    "area_pixels",
    "area_percentile_within_image",
    "split_candidate",
    "centroid_x",
    "centroid_y",
}


assert required_m1_candidate_cols_2a.issubset(
    m1_7a_candidates_df.columns
), (
    "Required M1 Step-7A component columns missing.\n"
    f"Missing: "
    f"{sorted(required_m1_candidate_cols_2a - set(m1_7a_candidates_df.columns))}"
)


component_info_2a_df = (
    m1_7a_candidates_df[
        [
            "dataset_index",
            "component_id",
            "area_pixels",
            "area_percentile_within_image",
            "split_candidate",
            "centroid_x",
            "centroid_y",
        ]
    ]
    .rename(
        columns={
            "component_id":
                "original_component_id",

            "area_pixels":
                "a3c_component_area",
        }
    )
    .copy()
)


c1_component_map_2a_df = (
    c1_recovery_all_2a_df
    .merge(
        component_info_2a_df,
        on=[
            "dataset_index",
            "original_component_id",
        ],
        how="left",
        validate="one_to_one",
    )
)


assert len(
    c1_component_map_2a_df
) == 2554


c1_component_map_2a_df[
    "centroid_delta_px"
] = np.hypot(
    c1_component_map_2a_df[
        "x"
    ]
    -
    c1_component_map_2a_df[
        "centroid_x"
    ],

    c1_component_map_2a_df[
        "y"
    ]
    -
    c1_component_map_2a_df[
        "centroid_y"
    ],
)

# ------------------------------------------------------------
# Centroid-coordinate consistency check
#
# ABC stores C1 centroid coordinates as float32, while M1
# recomputes centroids from the frozen A3c masks at higher
# precision. Therefore tiny numerical differences are expected.
#
# Diagnostic result:
#   max observed delta ≈ 3.23e-05 px
#   2554/2554 component identities preserve point_index + 1
#
# Use 1e-4 px purely as a numerical consistency tolerance.
# ------------------------------------------------------------

CENTROID_TOLERANCE_PX_2A = 1e-4


assert (
    c1_component_map_2a_df[
        "centroid_delta_px"
    ]
    <=
    CENTROID_TOLERANCE_PX_2A
).all(), (
    "C1/M1 centroid mismatch exceeds the expected "
    "float32 numerical tolerance."
)


print(
    "C1 centroid reproduction     : 2554/2554 within",
    CENTROID_TOLERANCE_PX_2A,
    "px"
)

print(
    "Maximum centroid delta       :",
    float(
        c1_component_map_2a_df[
            "centroid_delta_px"
        ]
        .max()
    ),
)

# ------------------------------------------------------------
# 7. Attach frozen G2 component-level contribution
#
# G2_count_contribution means:
#
#   noncandidate component -> 1
#
#   candidate component ->
#       two anchors
#       + retained satellites >= 0.001 parent-area fraction
#
# IMPORTANT:
# We only attach this information here.
# We do NOT add it to B2 yet.
# ------------------------------------------------------------

required_g2_component_cols_2a = {
    "dataset_index",
    "original_component_id",
    "G0_count_contribution",
    "G2_count_contribution",
}


assert required_g2_component_cols_2a.issubset(
    m1_7d_component_counts_df.columns
), (
    "Required M1 Step-7D component-count columns missing.\n"
    f"Missing: "
    f"{sorted(required_g2_component_cols_2a - set(m1_7d_component_counts_df.columns))}"
)


g2_component_info_2a_df = (
    m1_7d_component_counts_df[
        [
            "dataset_index",
            "original_component_id",
            "G0_count_contribution",
            "G2_count_contribution",
        ]
    ]
    .copy()
)


c1_component_map_2a_df = (
    c1_component_map_2a_df
    .merge(
        g2_component_info_2a_df,
        on=[
            "dataset_index",
            "original_component_id",
        ],
        how="left",
        validate="one_to_one",
    )
)


assert (
    c1_component_map_2a_df[
        [
            "G0_count_contribution",
            "G2_count_contribution",
        ]
    ]
    .notna()
    .all()
    .all()
)


assert (
    c1_component_map_2a_df[
        "G0_count_contribution"
    ]
    ==
    1
).all()


c1_component_map_2a_df[
    "G2_extra_units_vs_C1"
] = (
    c1_component_map_2a_df[
        "G2_count_contribution"
    ]
    -
    1
)


assert (
    c1_component_map_2a_df[
        "G2_extra_units_vs_C1"
    ]
    >=
    0
).all()


# ------------------------------------------------------------
# 8. Attach frozen image-level M1 gate
#
# candidate_area_fraction >= 0.85
#
# Again: descriptive / eligibility annotation only here.
# ------------------------------------------------------------

image_geometry_status_2a_df = (
    geometry_reference_df[
        [
            "dataset_index",
            "candidate_area_fraction",
            "M1_G2_gate_ON",
        ]
    ]
    .copy()
)


c1_component_map_2a_df = (
    c1_component_map_2a_df
    .merge(
        image_geometry_status_2a_df,
        on="dataset_index",
        how="left",
        validate="many_to_one",
    )
)


assert (
    c1_component_map_2a_df[
        [
            "candidate_area_fraction",
            "M1_G2_gate_ON",
        ]
    ]
    .notna()
    .all()
    .all()
)


# ------------------------------------------------------------
# 9. Isolate actual B2 C1 recovery candidates
#
# These are C1 points outside all B0 masks.
# ------------------------------------------------------------

b2_c1_recovery_map_2a_df = (
    c1_component_map_2a_df[
        c1_component_map_2a_df[
            "recovery_candidate"
        ]
        .astype(bool)
    ]
    .copy()
    .sort_values(
        [
            "dataset_index",
            "original_component_id",
        ]
    )
    .reset_index(
        drop=True
    )
)


assert len(
    b2_c1_recovery_map_2a_df
) == 1215, (
    f"Expected 1215 frozen C1 outside-B0 recovery candidates, "
    f"found {len(b2_c1_recovery_map_2a_df)}"
)


# ------------------------------------------------------------
# 10. Define geometry-status labels for diagnostics only
#
# NO count rule is changed here.
# ------------------------------------------------------------

b2_c1_recovery_map_2a_df[
    "geometry_split_candidate"
] = (
    b2_c1_recovery_map_2a_df[
        "split_candidate"
    ]
    .astype(bool)
)


b2_c1_recovery_map_2a_df[
    "geometry_image_gate_ON"
] = (
    b2_c1_recovery_map_2a_df[
        "M1_G2_gate_ON"
    ]
    .astype(bool)
)


b2_c1_recovery_map_2a_df[
    "geometry_refinable"
] = (
    b2_c1_recovery_map_2a_df[
        "geometry_split_candidate"
    ]
    &
    b2_c1_recovery_map_2a_df[
        "geometry_image_gate_ON"
    ]
)


# ------------------------------------------------------------
# 11. Summary
# ------------------------------------------------------------

summary_2a = {
    "all_C1_components":
        int(
            len(
                c1_component_map_2a_df
            )
        ),

    "C1_covered_by_B0":
        int(
            c1_component_map_2a_df[
                "covered_by_b0"
            ]
            .astype(bool)
            .sum()
        ),

    "C1_outside_B0_recovery":
        int(
            len(
                b2_c1_recovery_map_2a_df
            )
        ),

    "recovery_step7A_candidates":
        int(
            b2_c1_recovery_map_2a_df[
                "geometry_split_candidate"
            ]
            .sum()
        ),

    "recovery_in_M1_gate_ON_images":
        int(
            b2_c1_recovery_map_2a_df[
                "geometry_image_gate_ON"
            ]
            .sum()
        ),

    "recovery_geometry_refinable":
        int(
            b2_c1_recovery_map_2a_df[
                "geometry_refinable"
            ]
            .sum()
        ),

    "G2_extra_units_all_recovery":
        int(
            b2_c1_recovery_map_2a_df[
                "G2_extra_units_vs_C1"
            ]
            .sum()
        ),

    "G2_extra_units_refinable_only":
        int(
            b2_c1_recovery_map_2a_df.loc[
                b2_c1_recovery_map_2a_df[
                    "geometry_refinable"
                ],
                "G2_extra_units_vs_C1",
            ]
            .sum()
        ),
}


b3_step2a_summary_df = pd.DataFrame(
    [
        summary_2a
    ]
)


# ------------------------------------------------------------
# 12. Per-image bridge summary
# ------------------------------------------------------------

b3_step2a_per_image_df = (
    b2_c1_recovery_map_2a_df
    .groupby(
        "dataset_index",
        as_index=False,
    )
    .agg(
        C1_recovery_count=(
            "original_component_id",
            "count",
        ),

        C1_recovery_split_candidates=(
            "geometry_split_candidate",
            "sum",
        ),

        C1_recovery_geometry_refinable=(
            "geometry_refinable",
            "sum",
        ),

        G2_extra_units_all_recovery=(
            "G2_extra_units_vs_C1",
            "sum",
        ),
    )
)


# Need all 100 images, including any with zero outside-B0 C1 points.
b3_step2a_per_image_df = (
    dev100_identity_df[
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",
        ]
    ]
    .merge(
        b3_step2a_per_image_df,
        on="dataset_index",
        how="left",
        validate="one_to_one",
    )
    .merge(
        image_geometry_status_2a_df,
        on="dataset_index",
        how="left",
        validate="one_to_one",
    )
)


count_cols_2a = [
    "C1_recovery_count",
    "C1_recovery_split_candidates",
    "C1_recovery_geometry_refinable",
    "G2_extra_units_all_recovery",
]


b3_step2a_per_image_df[
    count_cols_2a
] = (
    b3_step2a_per_image_df[
        count_cols_2a
    ]
    .fillna(0)
    .astype(int)
)


b3_step2a_per_image_df[
    "G2_extra_units_refinable_only"
] = (
    b2_c1_recovery_map_2a_df[
        b2_c1_recovery_map_2a_df[
            "geometry_refinable"
        ]
    ]
    .groupby(
        "dataset_index"
    )[
        "G2_extra_units_vs_C1"
    ]
    .sum()
    .reindex(
        b3_step2a_per_image_df[
            "dataset_index"
        ],
        fill_value=0,
    )
    .to_numpy(
        dtype=int
    )
)


assert len(
    b3_step2a_per_image_df
) == 100


assert int(
    b3_step2a_per_image_df[
        "C1_recovery_count"
    ]
    .sum()
) == 1215


# ------------------------------------------------------------
# 13. Save B3 Step-2A bridge artifacts
# ------------------------------------------------------------

B3_STEP2A_COMPONENT_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2A_C1_to_M1_component_mapping.csv"
)

B3_STEP2A_RECOVERY_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2A_C1_recovery_geometry_mapping.csv"
)

B3_STEP2A_IMAGE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2A_C1_recovery_geometry_per_image.csv"
)

B3_STEP2A_SUMMARY_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2A_C1_recovery_geometry_summary.csv"
)


c1_component_map_2a_df.to_csv(
    B3_STEP2A_COMPONENT_FILE,
    index=False,
)

b2_c1_recovery_map_2a_df.to_csv(
    B3_STEP2A_RECOVERY_FILE,
    index=False,
)

b3_step2a_per_image_df.to_csv(
    B3_STEP2A_IMAGE_FILE,
    index=False,
)

b3_step2a_summary_df.to_csv(
    B3_STEP2A_SUMMARY_FILE,
    index=False,
)


# ------------------------------------------------------------
# 14. Report
# ------------------------------------------------------------

print("\nB2 C1 -> M1 component bridge")
print("----------------------------")

display(
    b3_step2a_summary_df
)


print("\nPer-image bridge — first 20")
print("---------------------------")

display(
    b3_step2a_per_image_df[
        [
            "dataset_index",
            "image_id",
            "density_stratum",
            "gt_count",

            "C1_recovery_count",
            "C1_recovery_split_candidates",
            "C1_recovery_geometry_refinable",

            "G2_extra_units_all_recovery",
            "G2_extra_units_refinable_only",

            "candidate_area_fraction",
            "M1_G2_gate_ON",
        ]
    ]
    .head(
        20
    )
)


# ------------------------------------------------------------
# 15. Protocol report
# ------------------------------------------------------------

print("\nFrozen C1 components mapped          : 2554/2554")
print("Frozen outside-B0 C1 recovery points: 1215")
print("Mapping rule                         : point_index + 1")
print("Centroid identity cross-check        : PASS")

print("\nStep-7A candidate status attached    : YES")
print("G2 component contribution attached  : YES")
print("M1 image gate attached              : YES")

print("\nGeometry added to B2 count           : NO")
print("B2 alpha changed                     : NO")
print("B2 semantic gate changed             : NO")
print("M1 thresholds changed                : NO")
print("GT used for inference decision       : NO")
print("Test set accessed                    : NO")

print("\nB3 Step 2A: PASS")

========================================================================================================================
B3 STEP 2A — MAP B2 C1 RECOVERY TO M1 / A3c COMPONENTS
========================================================================================================================

Loaded B2 recovery-point rows: 23018
C1 -> A3c component identity: 2554/2554 exact
C1 centroid reproduction     : 2554/2554 within 0.0001 px
Maximum centroid delta       : 3.2337694085248585e-05

B2 C1 -> M1 component bridge
----------------------------

,all_C1_components,C1_covered_by_B0,C1_outside_B0_recovery,recovery_step7A_candidates,recovery_in_M1_gate_ON_images,recovery_geometry_refinable,G2_extra_units_all_recovery,G2_extra_units_refinable_only
0,2554,1339,1215,345,739,209,2280,1567

Per-image bridge — first 20
---------------------------

,dataset_index,image_id,density_stratum,gt_count,C1_recovery_count,C1_recovery_split_candidates,C1_recovery_geometry_refinable,G2_extra_units_all_recovery,G2_extra_units_refinable_only,candidate_area_fraction,M1_G2_gate_ON
0,9,215.jpg,S6_95_100,259,5,1,1,5,5,0.979895,True
1,14,220.jpg,S4_60_80,59,32,9,9,34,34,0.968037,True
2,20,228.jpg,S4_60_80,44,22,4,4,8,8,0.962197,True
3,31,241.jpg,S3_40_60,35,2,1,1,1,1,0.971701,True
4,40,252.jpg,S3_40_60,22,1,1,1,2,2,1.000000,True
5,49,556.jpg,S2_20_40,14,8,3,3,15,15,0.851685,True
6,52,559.jpg,S2_20_40,20,16,5,0,15,0,0.680344,False
7,59,567.jpg,S1_0_20,10,8,3,0,9,0,0.692814,False
8,67,575.jpg,S1_0_20,12,9,3,3,19,19,0.925856,True
9,87,596.jpg,S2_20_40,14,10,3,0,13,0,0.819553,False
10,101,611.jpg,S2_20_40,14,11,1,1,1,1,0.882882,True
11,112,623.jpg,S1_0_20,9,6,0,0,0,0,0.744033,False
12,114,625.jpg,S2_20_40,14,8,2,2,3,3,0.914288,True
13,119,737.jpg,S1_0_20,9,3,1,1,6,6,0.987946,True
14,125,745.jpg,S4_60_80,60,0,0,0,0,0,0.945749,True
15,143,764.jpg,S5_80_95,85,49,13,0,59,0,0.826120,False
16,148,769.jpg,S2_20_40,13,28,6,0,37,0,0.838148,False
17,153,774.jpg,S1_0_20,8,3,2,2,6,6,0.999457,True
18,166,819.jpg,S4_60_80,40,0,0,0,0,0,0.721823,False
19,170,824.jpg,S1_0_20,9,1,1,1,7,7,0.963154,True

Frozen C1 components mapped          : 2554/2554
Frozen outside-B0 C1 recovery points: 1215
Mapping rule                         : point_index + 1
Centroid identity cross-check        : PASS

Step-7A candidate status attached    : YES
G2 component contribution attached  : YES
M1 image gate attached              : YES

Geometry added to B2 count           : NO
B2 alpha changed                     : NO
B2 semantic gate changed             : NO
M1 thresholds changed                : NO
GT used for inference decision       : NO
Test set accessed                    : NO

B3 Step 2A: PASS

In [ ]:
# ============================================================
# B3 Step 2A-Diagnostic — Why do C1 and M1 centroids differ?
# ============================================================

import numpy as np
import pandas as pd
from scipy.optimize import linear_sum_assignment


print("=" * 120)
print("B3 STEP 2A DIAGNOSTIC — C1 vs M1 CENTROID MAPPING")
print("=" * 120)


# ------------------------------------------------------------
# Use the objects already created before the failed assertion
# ------------------------------------------------------------

assert "c1_recovery_all_2a_df" in globals()
assert "component_info_2a_df" in globals()


diag_rows = []


for dataset_index in sorted(
    c1_recovery_all_2a_df[
        "dataset_index"
    ].unique()
):

    c1_img = (
        c1_recovery_all_2a_df[
            c1_recovery_all_2a_df[
                "dataset_index"
            ]
            ==
            dataset_index
        ]
        .sort_values(
            "point_index"
        )
        .reset_index(
            drop=True
        )
    )


    m1_img = (
        component_info_2a_df[
            component_info_2a_df[
                "dataset_index"
            ]
            ==
            dataset_index
        ]
        .sort_values(
            "original_component_id"
        )
        .reset_index(
            drop=True
        )
    )


    assert len(c1_img) == len(m1_img)


    c1_xy = (
        c1_img[
            [
                "x",
                "y",
            ]
        ]
        .to_numpy(
            dtype=np.float64
        )
    )


    m1_xy = (
        m1_img[
            [
                "centroid_x",
                "centroid_y",
            ]
        ]
        .to_numpy(
            dtype=np.float64
        )
    )


    # --------------------------------------------------------
    # A. Original assumed index mapping:
    #
    # C1 point_index i -> M1 component i+1
    # --------------------------------------------------------

    direct_delta = np.linalg.norm(
        c1_xy
        -
        m1_xy,
        axis=1,
    )


    # --------------------------------------------------------
    # B. True one-to-one minimum-distance centroid matching
    # --------------------------------------------------------

    dx = (
        c1_xy[
            :,
            None,
            0,
        ]
        -
        m1_xy[
            None,
            :,
            0,
        ]
    )

    dy = (
        c1_xy[
            :,
            None,
            1,
        ]
        -
        m1_xy[
            None,
            :,
            1,
        ]
    )

    distance_matrix = np.hypot(
        dx,
        dy,
    )


    row_ind, col_ind = (
        linear_sum_assignment(
            distance_matrix
        )
    )


    matched_delta = (
        distance_matrix[
            row_ind,
            col_ind,
        ]
    )


    # --------------------------------------------------------
    # Does one-to-one matching preserve point_index+1 labels?
    # --------------------------------------------------------

    expected_component_ids = (
        c1_img.iloc[
            row_ind
        ][
            "point_index"
        ]
        .to_numpy(
            dtype=int
        )
        +
        1
    )


    actual_component_ids = (
        m1_img.iloc[
            col_ind
        ][
            "original_component_id"
        ]
        .to_numpy(
            dtype=int
        )
    )


    same_numeric_label = (
        expected_component_ids
        ==
        actual_component_ids
    )


    for j in range(
        len(
            row_ind
        )
    ):

        diag_rows.append(
            {
                "dataset_index":
                    int(
                        dataset_index
                    ),

                "point_index":
                    int(
                        c1_img.iloc[
                            row_ind[j]
                        ][
                            "point_index"
                        ]
                    ),

                "expected_component_id_pointindex_plus1":
                    int(
                        expected_component_ids[j]
                    ),

                "matched_M1_component_id":
                    int(
                        actual_component_ids[j]
                    ),

                "direct_index_delta_px":
                    float(
                        direct_delta[
                            row_ind[j]
                        ]
                    ),

                "matched_centroid_delta_px":
                    float(
                        matched_delta[j]
                    ),

                "same_numeric_label":
                    bool(
                        same_numeric_label[j]
                    ),
            }
        )


centroid_mapping_diag_2a_df = (
    pd.DataFrame(
        diag_rows
    )
)


# ------------------------------------------------------------
# Report
# ------------------------------------------------------------

print(
    "\nTotal C1/M1 components:",
    len(
        centroid_mapping_diag_2a_df
    ),
)


print(
    "\nIf we assume point_index + 1:"
)

print(
    "  exact numeric label matches :",
    int(
        centroid_mapping_diag_2a_df[
            "same_numeric_label"
        ]
        .sum()
    ),
    "/",
    len(
        centroid_mapping_diag_2a_df
    ),
)

print(
    "  max centroid delta          :",
    float(
        centroid_mapping_diag_2a_df[
            "direct_index_delta_px"
        ]
        .max()
    ),
)

print(
    "  median centroid delta       :",
    float(
        centroid_mapping_diag_2a_df[
            "direct_index_delta_px"
        ]
        .median()
    ),
)


print(
    "\nAfter one-to-one centroid matching:"
)

print(
    "  max centroid delta          :",
    float(
        centroid_mapping_diag_2a_df[
            "matched_centroid_delta_px"
        ]
        .max()
    ),
)

print(
    "  median centroid delta       :",
    float(
        centroid_mapping_diag_2a_df[
            "matched_centroid_delta_px"
        ]
        .median()
    ),
)

print(
    "  <= 1e-4 px                  :",
    int(
        (
            centroid_mapping_diag_2a_df[
                "matched_centroid_delta_px"
            ]
            <=
            1e-4
        )
        .sum()
    ),
    "/",
    len(
        centroid_mapping_diag_2a_df
    ),
)

print(
    "  <= 1e-3 px                  :",
    int(
        (
            centroid_mapping_diag_2a_df[
                "matched_centroid_delta_px"
            ]
            <=
            1e-3
        )
        .sum()
    ),
    "/",
    len(
        centroid_mapping_diag_2a_df
    ),
)


print("\nLargest matched centroid differences:")

display(
    centroid_mapping_diag_2a_df
    .sort_values(
        "matched_centroid_delta_px",
        ascending=False,
    )
    .head(
        20
    )
)


print("\nStep 2A centroid diagnostic: COMPLETE")

========================================================================================================================
B3 STEP 2A DIAGNOSTIC — C1 vs M1 CENTROID MAPPING
========================================================================================================================

Total C1/M1 components: 2554

If we assume point_index + 1:
  exact numeric label matches : 2554 / 2554
  max centroid delta          : 3.2337694085248585e-05
  median centroid delta       : 6.539481006484493e-06

After one-to-one centroid matching:
  max centroid delta          : 3.2337694085248585e-05
  median centroid delta       : 6.539481006484493e-06
  <= 1e-4 px                  : 2554 / 2554
  <= 1e-3 px                  : 2554 / 2554

Largest matched centroid differences:

,dataset_index,point_index,expected_component_id_pointindex_plus1,matched_M1_component_id,direct_index_delta_px,matched_centroid_delta_px,same_numeric_label
2209,1187,79,80,80,0.000032,0.000032,True
1136,425,1,2,2,0.000031,0.000031,True
2084,1169,9,10,10,0.000031,0.000031,True
1540,683,27,28,28,0.000030,0.000030,True
70,31,6,7,7,0.000030,0.000030,True
621,184,19,20,20,0.000030,0.000030,True
710,227,19,20,20,0.000030,0.000030,True
1093,394,1,2,2,0.000030,0.000030,True
401,172,31,32,32,0.000030,0.000030,True
2350,1256,11,12,12,0.000030,0.000030,True
2436,1257,13,14,14,0.000029,0.000029,True
778,231,8,9,9,0.000029,0.000029,True
2419,1256,80,81,81,0.000029,0.000029,True
2024,1149,25,26,26,0.000029,0.000029,True
1220,488,37,38,38,0.000029,0.000029,True
693,227,2,3,3,0.000029,0.000029,True
2479,1257,56,57,57,0.000029,0.000029,True
98,59,0,1,1,0.000029,0.000029,True
2179,1187,49,50,50,0.000029,0.000029,True
2087,1169,12,13,13,0.000028,0.000028,True

Step 2A centroid diagnostic: COMPLETE

In [ ]:
# ============================================================
# B3 Step 2B — First Controlled Geometry Injection into B2-S
# ============================================================
#
# Purpose
# -------
# Test whether Marigold-derived multiplicity improves the
# existing frozen B2 semantic-only counter when geometry is
# applied ONLY inside existing C1 recovery components.
#
#
# Frozen B2-S:
#
#   B0 + C1 raw recovery
#      + 0.5 * gated Step3D D6B-T-native recovery
#
# Existing B2 semantic gate remains:
#
#   C1_added >= 10
#
#
# Geometry contribution:
#
#   For a C1 recovery component:
#
#       extra_geometry_units
#           = G2_count_contribution - 1
#
# because the original C1 component already contributes one
# unit in B2-S.
#
#
# Variants
# --------
#
# B2-S
#   Frozen semantic-only baseline.
#
# B3-SG-candidate
#   B2-S
#   + G2 extra units from all Step-7A candidate C1 recovery
#     components.
#
# B3-SG-gated
#   B2-S
#   + G2 extra units only when:
#
#       Step-7A split candidate
#       AND
#       M1 candidate_area_fraction >= 0.85
#
#
# IMPORTANT
# ---------
#
# Geometry is NOT an independent second counter here.
#
# It only replaces:
#
#       one C1 recovery component
#
# with:
#
#       one + G2 extra multiplicity
#
# inside that SAME semantic recovery component.
#
#
# No:
#   - B0 change
#   - C1 change
#   - D change
#   - B2 alpha change
#   - B2 semantic-gate change
#   - M1 threshold change
#   - geometry weighting
#   - density routing
#   - GT-based inference decision
#   - test-set access
#
# ============================================================

import numpy as np
import pandas as pd


print("=" * 120)
print("B3 STEP 2B — FIRST CONTROLLED GEOMETRY INJECTION INTO B2-S")
print("=" * 120)


# ------------------------------------------------------------
# 1. Guards
# ------------------------------------------------------------

assert "b2_reference_df" in globals(), (
    "b2_reference_df unavailable. Run Setup 0D first."
)

assert "b3_step2a_per_image_df" in globals(), (
    "b3_step2a_per_image_df unavailable. Run Step 2A first."
)

assert "b2_c1_recovery_map_2a_df" in globals(), (
    "b2_c1_recovery_map_2a_df unavailable. Run Step 2A first."
)

assert "B3_TABLES_DIR" in globals()


assert len(
    b2_reference_df
) == 100

assert len(
    b3_step2a_per_image_df
) == 100


# Frozen Step-2A structural identities
assert int(
    b3_step2a_per_image_df[
        "C1_recovery_count"
    ]
    .sum()
) == 1215


assert int(
    b3_step2a_per_image_df[
        "G2_extra_units_all_recovery"
    ]
    .sum()
) == 2280


assert int(
    b3_step2a_per_image_df[
        "G2_extra_units_refinable_only"
    ]
    .sum()
) == 1567


# ------------------------------------------------------------
# 2. Resolve frozen B2-S prediction column
# ------------------------------------------------------------

assert "predicted_count" in b2_reference_df.columns


# ------------------------------------------------------------
# 3. Build exact aligned integration table
# ------------------------------------------------------------

b3_step2b_df = (
    b2_reference_df[
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",
            "predicted_count",
        ]
    ]
    .rename(
        columns={
            "predicted_count":
                "B2_S_count",
        }
    )
    .merge(
        b3_step2a_per_image_df[
            [
                "dataset_index",

                "C1_recovery_count",
                "C1_recovery_split_candidates",
                "C1_recovery_geometry_refinable",

                "G2_extra_units_all_recovery",
                "G2_extra_units_refinable_only",

                "candidate_area_fraction",
                "M1_G2_gate_ON",
            ]
        ],
        on="dataset_index",
        how="left",
        validate="one_to_one",
    )
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


assert len(
    b3_step2b_df
) == 100


assert (
    b3_step2b_df
    .notna()
    .all()
    .all()
)


# ------------------------------------------------------------
# 4. Define integrated geometry variants
#
# IMPORTANT:
#
# No new scaling/weighting is introduced.
#
# Each retained geometric extra unit contributes +1.
# ------------------------------------------------------------

b3_step2b_df[
    "B3_SG_candidate_count"
] = (
    b3_step2b_df[
        "B2_S_count"
    ]
    +
    b3_step2b_df[
        "G2_extra_units_all_recovery"
    ]
)


b3_step2b_df[
    "B3_SG_gated_count"
] = (
    b3_step2b_df[
        "B2_S_count"
    ]
    +
    b3_step2b_df[
        "G2_extra_units_refinable_only"
    ]
)


# ------------------------------------------------------------
# 5. Structural sanity checks
# ------------------------------------------------------------

assert (
    b3_step2b_df[
        "B3_SG_candidate_count"
    ]
    >=
    b3_step2b_df[
        "B3_SG_gated_count"
    ]
).all()


assert (
    b3_step2b_df[
        "B3_SG_gated_count"
    ]
    >=
    b3_step2b_df[
        "B2_S_count"
    ]
).all()


# If M1 image gate is OFF, gated geometry must add nothing.
assert (
    b3_step2b_df.loc[
        ~b3_step2b_df[
            "M1_G2_gate_ON"
        ].astype(bool),
        "G2_extra_units_refinable_only",
    ]
    ==
    0
).all()


# ------------------------------------------------------------
# 6. Metric helper
# ------------------------------------------------------------

def count_metrics_b3_2b(
    df,
    pred_col,
    system_name,
):

    gt = (
        df[
            "gt_count"
        ]
        .to_numpy(
            dtype=float
        )
    )


    pred = (
        df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )


    signed = (
        pred
        -
        gt
    )


    abs_error = np.abs(
        signed
    )


    return {
        "system":
            system_name,

        "prediction_column":
            pred_col,

        "num_images":
            int(
                len(
                    df
                )
            ),

        "total_prediction":
            float(
                pred.sum()
            ),

        "mean_prediction":
            float(
                pred.mean()
            ),

        "MAE":
            float(
                abs_error.mean()
            ),

        "RMSE":
            float(
                np.sqrt(
                    np.mean(
                        signed ** 2
                    )
                )
            ),

        "mean_signed_error":
            float(
                signed.mean()
            ),

        "median_signed_error":
            float(
                np.median(
                    signed
                )
            ),

        "under_images":
            int(
                (
                    signed < 0
                )
                .sum()
            ),

        "exact_images":
            int(
                np.isclose(
                    signed,
                    0.0,
                )
                .sum()
            ),

        "over_images":
            int(
                (
                    signed > 0
                )
                .sum()
            ),
    }


# ------------------------------------------------------------
# 7. Overall comparison
# ------------------------------------------------------------

SYSTEMS_2B = [
    (
        "B2-S",
        "B2_S_count",
    ),

    (
        "B3-SG-candidate",
        "B3_SG_candidate_count",
    ),

    (
        "B3-SG-gated",
        "B3_SG_gated_count",
    ),
]


overall_rows_2b = []


for system_name, pred_col in (
    SYSTEMS_2B
):

    overall_rows_2b.append(
        count_metrics_b3_2b(
            df=
                b3_step2b_df,

            pred_col=
                pred_col,

            system_name=
                system_name,
        )
    )


b3_step2b_overall_df = (
    pd.DataFrame(
        overall_rows_2b
    )
)


# ------------------------------------------------------------
# 8. Add deltas vs frozen B2-S
# ------------------------------------------------------------

b2s_metrics_2b = (
    b3_step2b_overall_df[
        b3_step2b_overall_df[
            "system"
        ]
        ==
        "B2-S"
    ]
    .iloc[0]
)


b3_step2b_overall_df[
    "delta_MAE_vs_B2S"
] = (
    b3_step2b_overall_df[
        "MAE"
    ]
    -
    float(
        b2s_metrics_2b[
            "MAE"
        ]
    )
)


b3_step2b_overall_df[
    "delta_RMSE_vs_B2S"
] = (
    b3_step2b_overall_df[
        "RMSE"
    ]
    -
    float(
        b2s_metrics_2b[
            "RMSE"
        ]
    )
)


b3_step2b_overall_df[
    "delta_signed_error_vs_B2S"
] = (
    b3_step2b_overall_df[
        "mean_signed_error"
    ]
    -
    float(
        b2s_metrics_2b[
            "mean_signed_error"
        ]
    )
)


# ------------------------------------------------------------
# 9. Per-image help / tie / hurt relative to B2-S
# ------------------------------------------------------------

gt_2b = (
    b3_step2b_df[
        "gt_count"
    ]
    .to_numpy(
        dtype=float
    )
)


b2s_pred_2b = (
    b3_step2b_df[
        "B2_S_count"
    ]
    .to_numpy(
        dtype=float
    )
)


b2s_abs_error_2b = np.abs(
    b2s_pred_2b
    -
    gt_2b
)


help_hurt_rows_2b = []


for system_name, pred_col in [
    (
        "B3-SG-candidate",
        "B3_SG_candidate_count",
    ),

    (
        "B3-SG-gated",
        "B3_SG_gated_count",
    ),
]:

    pred = (
        b3_step2b_df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )


    abs_error = np.abs(
        pred
        -
        gt_2b
    )


    delta = (
        abs_error
        -
        b2s_abs_error_2b
    )


    b3_step2b_df[
        f"{system_name}_abs_error_delta_vs_B2S"
    ] = (
        delta
    )


    help_hurt_rows_2b.append(
        {
            "system":
                system_name,

            "improves_images":
                int(
                    (
                        delta
                        <
                        0
                    )
                    .sum()
                ),

            "ties_images":
                int(
                    np.isclose(
                        delta,
                        0.0,
                    )
                    .sum()
                ),

            "worsens_images":
                int(
                    (
                        delta
                        >
                        0
                    )
                    .sum()
                ),

            "mean_abs_error_delta_vs_B2S":
                float(
                    delta.mean()
                ),

            "median_abs_error_delta_vs_B2S":
                float(
                    np.median(
                        delta
                    )
                ),
        }
    )


b3_step2b_help_hurt_df = (
    pd.DataFrame(
        help_hurt_rows_2b
    )
)


# ------------------------------------------------------------
# 10. Density-stratum evaluation
#
# Density stratum is evaluation only.
# It is NOT used by either integration rule.
# ------------------------------------------------------------

STRATUM_ORDER_2B = [
    "S1_0_20",
    "S2_20_40",
    "S3_40_60",
    "S4_60_80",
    "S5_80_95",
    "S6_95_100",
]


stratum_rows_2b = []


for stratum in (
    STRATUM_ORDER_2B
):

    sdf = (
        b3_step2b_df[
            b3_step2b_df[
                "density_stratum"
            ]
            ==
            stratum
        ]
    )


    for system_name, pred_col in (
        SYSTEMS_2B
    ):

        gt = (
            sdf[
                "gt_count"
            ]
            .to_numpy(
                dtype=float
            )
        )


        pred = (
            sdf[
                pred_col
            ]
            .to_numpy(
                dtype=float
            )
        )


        signed = (
            pred
            -
            gt
        )


        stratum_rows_2b.append(
            {
                "density_stratum":
                    stratum,

                "system":
                    system_name,

                "num_images":
                    int(
                        len(
                            sdf
                        )
                    ),

                "MAE":
                    float(
                        np.abs(
                            signed
                        )
                        .mean()
                    ),

                "RMSE":
                    float(
                        np.sqrt(
                            np.mean(
                                signed ** 2
                            )
                        )
                    ),

                "mean_signed_error":
                    float(
                        signed.mean()
                    ),
            }
        )


b3_step2b_stratum_df = (
    pd.DataFrame(
        stratum_rows_2b
    )
)


# ------------------------------------------------------------
# 11. Geometry contribution summaries
# ------------------------------------------------------------

geometry_contribution_summary_2b_df = pd.DataFrame(
    [
        {
            "variant":
                "candidate_only",

            "geometry_extra_units":
                int(
                    b3_step2b_df[
                        "G2_extra_units_all_recovery"
                    ]
                    .sum()
                ),

            "images_with_geometry_addition":
                int(
                    (
                        b3_step2b_df[
                            "G2_extra_units_all_recovery"
                        ]
                        >
                        0
                    )
                    .sum()
                ),

            "mean_extra_units_per_image":
                float(
                    b3_step2b_df[
                        "G2_extra_units_all_recovery"
                    ]
                    .mean()
                ),

            "median_extra_units_per_image":
                float(
                    b3_step2b_df[
                        "G2_extra_units_all_recovery"
                    ]
                    .median()
                ),

            "max_extra_units_one_image":
                int(
                    b3_step2b_df[
                        "G2_extra_units_all_recovery"
                    ]
                    .max()
                ),
        },

        {
            "variant":
                "candidate_plus_image_gate",

            "geometry_extra_units":
                int(
                    b3_step2b_df[
                        "G2_extra_units_refinable_only"
                    ]
                    .sum()
                ),

            "images_with_geometry_addition":
                int(
                    (
                        b3_step2b_df[
                            "G2_extra_units_refinable_only"
                        ]
                        >
                        0
                    )
                    .sum()
                ),

            "mean_extra_units_per_image":
                float(
                    b3_step2b_df[
                        "G2_extra_units_refinable_only"
                    ]
                    .mean()
                ),

            "median_extra_units_per_image":
                float(
                    b3_step2b_df[
                        "G2_extra_units_refinable_only"
                    ]
                    .median()
                ),

            "max_extra_units_one_image":
                int(
                    b3_step2b_df[
                        "G2_extra_units_refinable_only"
                    ]
                    .max()
                ),
        },
    ]
)


# ------------------------------------------------------------
# 12. Largest improvements / worsenings for gated integration
# ------------------------------------------------------------

gated_delta_col_2b = (
    "B3-SG-gated_abs_error_delta_vs_B2S"
)


largest_improvements_2b_df = (
    b3_step2b_df
    .sort_values(
        gated_delta_col_2b,
        ascending=True,
    )
    [
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "B2_S_count",
            "B3_SG_gated_count",

            "C1_recovery_count",
            "C1_recovery_geometry_refinable",
            "G2_extra_units_refinable_only",

            "candidate_area_fraction",
            "M1_G2_gate_ON",

            gated_delta_col_2b,
        ]
    ]
    .head(
        15
    )
)


largest_worsenings_2b_df = (
    b3_step2b_df
    .sort_values(
        gated_delta_col_2b,
        ascending=False,
    )
    [
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "B2_S_count",
            "B3_SG_gated_count",

            "C1_recovery_count",
            "C1_recovery_geometry_refinable",
            "G2_extra_units_refinable_only",

            "candidate_area_fraction",
            "M1_G2_gate_ON",

            gated_delta_col_2b,
        ]
    ]
    .head(
        15
    )
)


# ------------------------------------------------------------
# 13. Save Step-2B artifacts
# ------------------------------------------------------------

B3_STEP2B_IMAGE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2B_geometry_injected_B2_per_image.csv"
)

B3_STEP2B_OVERALL_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2B_geometry_injected_B2_overall.csv"
)

B3_STEP2B_STRATUM_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2B_geometry_injected_B2_by_density.csv"
)

B3_STEP2B_HELP_HURT_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2B_geometry_injected_B2_help_hurt.csv"
)

B3_STEP2B_CONTRIBUTION_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2B_geometry_contribution_summary.csv"
)


b3_step2b_df.to_csv(
    B3_STEP2B_IMAGE_FILE,
    index=False,
)

b3_step2b_overall_df.to_csv(
    B3_STEP2B_OVERALL_FILE,
    index=False,
)

b3_step2b_stratum_df.to_csv(
    B3_STEP2B_STRATUM_FILE,
    index=False,
)

b3_step2b_help_hurt_df.to_csv(
    B3_STEP2B_HELP_HURT_FILE,
    index=False,
)

geometry_contribution_summary_2b_df.to_csv(
    B3_STEP2B_CONTRIBUTION_FILE,
    index=False,
)


# ------------------------------------------------------------
# 14. Report — overall
# ------------------------------------------------------------

print("\nOverall count-level comparison")
print("------------------------------")

display(
    b3_step2b_overall_df[
        [
            "system",
            "total_prediction",
            "mean_prediction",
            "MAE",
            "RMSE",
            "mean_signed_error",
            "under_images",
            "exact_images",
            "over_images",
            "delta_MAE_vs_B2S",
            "delta_RMSE_vs_B2S",
        ]
    ]
)


# ------------------------------------------------------------
# 15. Report — geometry contribution
# ------------------------------------------------------------

print("\nGeometry contribution summary")
print("-----------------------------")

display(
    geometry_contribution_summary_2b_df
)


# ------------------------------------------------------------
# 16. Report — help / tie / hurt
# ------------------------------------------------------------

print("\nPer-image comparison versus frozen B2-S")
print("----------------------------------------")

display(
    b3_step2b_help_hurt_df
)


# ------------------------------------------------------------
# 17. Report — density MAE
# ------------------------------------------------------------

print("\nMAE by density stratum")
print("----------------------")

display(
    b3_step2b_stratum_df
    .pivot(
        index=
            "density_stratum",

        columns=
            "system",

        values=
            "MAE",
    )
)


# ------------------------------------------------------------
# 18. Report — gated variant extreme cases
# ------------------------------------------------------------

print("\nB3-SG-gated — largest improvements")
print("----------------------------------")

display(
    largest_improvements_2b_df
)


print("\nB3-SG-gated — largest worsenings")
print("--------------------------------")

display(
    largest_worsenings_2b_df
)


# ------------------------------------------------------------
# 19. Protocol report
# ------------------------------------------------------------

print("\nFrozen B2-S reused                     : YES")
print("Frozen B0 unchanged                    : YES")
print("Frozen C1 recovery unchanged           : YES")
print("Frozen D Step3D recovery unchanged     : YES")
print("B2 alpha remains                       : 0.5")
print("B2 semantic gate remains               : C1_added >= 10")

print("\nGeometry source                         : G2")
print("Geometry satellite threshold            : 0.001")
print("Geometry Step-7A candidate rule         : frozen 75th percentile")
print("Geometry image gate                     : candidate_area_fraction >= 0.85")

print("\nGeometry applied as independent counter : NO")
print("Geometry applied within C1 recovery     : YES")
print("New geometry weight introduced          : NO")

print("\nGT used for inference decision           : NO")
print("Density routing used                     : NO")
print("New semantic evidence generated          : NO")
print("New SAM2 inference                       : NO")
print("New Marigold inference                   : NO")
print("Test set accessed                        : NO")

print("\nB3 Step 2B: PASS")

========================================================================================================================
B3 STEP 2B — FIRST CONTROLLED GEOMETRY INJECTION INTO B2-S
========================================================================================================================

Overall count-level comparison
------------------------------

,system,total_prediction,mean_prediction,MAE,RMSE,mean_signed_error,under_images,exact_images,over_images,delta_MAE_vs_B2S,delta_RMSE_vs_B2S
0,B2-S,3842.0,38.42,70.90,260.272722,-62.03,46,7,47,0.00,0.000000
1,B3-SG-candidate,6122.0,61.22,67.34,244.436556,-39.23,28,3,69,-3.56,-15.836166
2,B3-SG-gated,5409.0,54.09,63.44,245.066236,-46.36,38,5,57,-7.46,-15.206486

Geometry contribution summary
-----------------------------

,variant,geometry_extra_units,images_with_geometry_addition,mean_extra_units_per_image,median_extra_units_per_image,max_extra_units_one_image
0,candidate_only,2280,75,22.80,7.0,619
1,candidate_plus_image_gate,1567,44,15.67,0.0,619

Per-image comparison versus frozen B2-S
----------------------------------------

,system,improves_images,ties_images,worsens_images,mean_abs_error_delta_vs_B2S,median_abs_error_delta_vs_B2S
0,B3-SG-candidate,23,26,51,-3.56,1.0
1,B3-SG-gated,16,57,27,-7.46,0.0

MAE by density stratum
----------------------

system              B2-S  B3-SG-candidate  B3-SG-gated
density_stratum
S1_0_20            5.575           10.975        9.675
S2_20_40           7.950           18.200       11.550
S3_40_60           9.950           18.650       14.700
S4_60_80          21.225           32.175       21.325
S5_80_95          40.550           36.450       35.650
S6_95_100        579.050          476.950      484.250

B3-SG-gated — largest improvements
----------------------------------

,dataset_index,image_id,category,density_stratum,gt_count,B2_S_count,B3_SG_gated_count,C1_recovery_count,C1_recovery_geometry_refinable,G2_extra_units_refinable_only,candidate_area_fraction,M1_G2_gate_ON,B3-SG-gated_abs_error_delta_vs_B2S
32,253,975.jpg,birds,S6_95_100,718.0,137.5,756.5,107,27,619,0.860165,True,-542.0
93,1192,6969.jpg,birds,S6_95_100,949.0,66.5,302.5,53,14,236,0.957437,True,-236.0
92,1187,6931.jpg,birds,S6_95_100,355.0,122.0,257.0,96,25,135,0.915656,True,-135.0
34,298,1935.jpg,bottle caps,S5_80_95,175.0,83.5,107.5,23,8,24,0.857724,True,-24.0
99,1269,7060.jpg,pills,S4_60_80,65.0,32.0,54.0,14,4,22,0.970365,True,-22.0
24,183,838.jpg,books,S5_80_95,113.0,82.5,122.5,27,8,40,0.880721,True,-21.0
83,1061,6286.jpg,pills,S4_60_80,49.0,5.0,25.0,1,1,20,1.000000,True,-20.0
40,365,2316.jpg,camels,S4_60_80,58.0,32.5,66.5,28,8,34,0.919276,True,-17.0
77,938,5866.jpg,grapes,S6_95_100,267.0,76.0,93.0,18,4,17,0.933266,True,-17.0
56,535,3665.jpg,toilet paper rolls,S6_95_100,907.0,22.0,35.0,8,3,13,0.976449,True,-13.0
61,609,4535.jpg,flamingos,S3_40_60,22.0,9.0,26.0,9,3,17,0.927780,True,-9.0
42,394,2840.jpg,chairs,S3_40_60,35.0,8.0,14.0,3,1,6,0.850108,True,-6.0
0,9,215.jpg,grapes,S6_95_100,259.0,108.0,113.0,5,1,5,0.979895,True,-5.0
76,920,5740.jpg,polka dots,S5_80_95,87.0,16.0,20.0,10,3,4,0.976832,True,-4.0
4,40,252.jpg,grapes,S3_40_60,22.0,15.0,17.0,1,1,2,1.000000,True,-2.0

B3-SG-gated — largest worsenings
--------------------------------

,dataset_index,image_id,category,density_stratum,gt_count,B2_S_count,B3_SG_gated_count,C1_recovery_count,C1_recovery_geometry_refinable,G2_extra_units_refinable_only,candidate_area_fraction,M1_G2_gate_ON,B3-SG-gated_abs_error_delta_vs_B2S
1,14,220.jpg,grapes,S4_60_80,59.0,66.0,100.0,32,9,34,0.968037,True,34.0
90,1169,7421.jpg,horses,S1_0_20,10.0,35.0,67.0,24,7,32,0.946695,True,32.0
91,1183,7305.jpg,birds,S3_40_60,31.0,34.0,66.0,31,8,32,0.921792,True,32.0
58,564,3777.jpg,donuts tray,S2_20_40,14.0,26.5,50.5,20,6,24,0.973688,True,24.0
43,396,2846.jpg,chairs,S4_60_80,38.0,40.0,60.0,23,6,20,0.967373,True,20.0
48,488,3543.jpg,chicken wings,S3_40_60,30.0,42.0,62.0,12,6,20,0.891366,True,20.0
41,372,2412.jpg,horses,S2_20_40,15.0,16.0,35.0,1,1,19,0.999367,True,19.0
87,1149,6794.jpg,shirts,S3_40_60,27.0,34.5,50.5,18,5,16,0.875356,True,16.0
8,67,575.jpg,flamingos,S1_0_20,12.0,10.0,29.0,9,3,19,0.925856,True,15.0
39,360,2304.jpg,camels,S1_0_20,9.0,10.0,24.0,8,3,14,0.986788,True,14.0
67,822,5078.jpg,chicken wings,S2_20_40,20.0,29.5,40.5,10,3,11,0.876848,True,11.0
69,845,5101.jpg,chicken wings,S3_40_60,23.0,30.0,40.0,6,2,10,0.887222,True,10.0
23,180,835.jpg,books,S3_40_60,22.0,23.0,33.0,12,4,10,0.979546,True,10.0
37,331,1976.jpg,bottle caps,S3_40_60,32.0,42.5,51.5,17,5,9,0.932353,True,9.0
98,1260,7100.jpg,milk cartons,S3_40_60,27.0,48.0,57.0,8,3,9,0.987285,True,9.0

Frozen B2-S reused                     : YES
Frozen B0 unchanged                    : YES
Frozen C1 recovery unchanged           : YES
Frozen D Step3D recovery unchanged     : YES
B2 alpha remains                       : 0.5
B2 semantic gate remains               : C1_added >= 10

Geometry source                         : G2
Geometry satellite threshold            : 0.001
Geometry Step-7A candidate rule         : frozen 75th percentile
Geometry image gate                     : candidate_area_fraction >= 0.85

Geometry applied as independent counter : NO
Geometry applied within C1 recovery     : YES
New geometry weight introduced          : NO

GT used for inference decision           : NO
Density routing used                     : NO
New semantic evidence generated          : NO
New SAM2 inference                       : NO
New Marigold inference                   : NO
Test set accessed                        : NO

B3 Step 2B: PASS

### **Finding 15:**

Integrating Marigold-derived multiplicity directly within existing C1 semantic recovery improves the frozen B2 architecture, demonstrating complementary geometric information beyond B0-anchored semantic recovery.

The gated integration reduces MAE from 70.90 to 63.44 and RMSE from 260.27 to 245.07, outperforming both the semantic-only baseline and ungated geometry integration.

However, the improvement is strongly concentrated in a small number of dense, severely undercounted images, while geometry remains harmful in many sparse and moderate-density cases.

Therefore, **selective geometry integration is supported**, but the current **full-strength geometry contribution should not yet be treated** as the final rule.

In [ ]:
# ============================================================
# B3 Step 2C — Robustness, concentration, and adaptive-signal
#                  diagnostic for geometry-in-B2
# ============================================================
#
# Purpose
# -------
# Step 2B showed:
#
#   - geometry improves B2 overall
#   - benefit is strongest in S5-S6
#   - geometry hurts S1-S3
#   - one/few very dense images contribute strongly
#
# Step 2C asks:
#
#   1. How concentrated is the apparent improvement?
#   2. Does the result remain useful after removing the
#      strongest-rescue images?
#   3. Which INFERENCE-AVAILABLE quantities distinguish
#      helpful from harmful geometry?
#
#
# IMPORTANT
# ---------
#
# Density strata are used ONLY for post-hoc diagnosis.
#
# They are NOT candidate inference features.
#
# No routing rule is selected here.
# No threshold is tuned here.
#
# ============================================================

import numpy as np
import pandas as pd

from scipy.stats import spearmanr
from sklearn.metrics import roc_auc_score


print("=" * 120)
print("B3 STEP 2C — ROBUSTNESS / CONCENTRATION / ADAPTIVE-SIGNAL DIAGNOSTIC")
print("=" * 120)


# ------------------------------------------------------------
# 1. Guards
# ------------------------------------------------------------

assert "b3_step2b_df" in globals(), (
    "b3_step2b_df unavailable. Run Step 2B first."
)

assert len(
    b3_step2b_df
) == 100


required_cols_2c = {
    "dataset_index",
    "image_id",
    "category",
    "density_stratum",
    "gt_count",

    "B2_S_count",
    "B3_SG_gated_count",

    "C1_recovery_count",
    "C1_recovery_split_candidates",
    "C1_recovery_geometry_refinable",

    "G2_extra_units_refinable_only",

    "candidate_area_fraction",
    "M1_G2_gate_ON",
}


assert required_cols_2c.issubset(
    b3_step2b_df.columns
), (
    "Required Step-2B columns missing.\n"
    f"Missing: {sorted(required_cols_2c - set(b3_step2b_df.columns))}"
)


# ------------------------------------------------------------
# 2. Build per-image diagnostic table
# ------------------------------------------------------------

b3_step2c_df = (
    b3_step2b_df[
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "B2_S_count",
            "B3_SG_gated_count",

            "C1_recovery_count",
            "C1_recovery_split_candidates",
            "C1_recovery_geometry_refinable",

            "G2_extra_units_refinable_only",

            "candidate_area_fraction",
            "M1_G2_gate_ON",
        ]
    ]
    .copy()
)


# ------------------------------------------------------------
# 3. Error quantities
# ------------------------------------------------------------

b3_step2c_df[
    "B2_signed_error"
] = (
    b3_step2c_df[
        "B2_S_count"
    ]
    -
    b3_step2c_df[
        "gt_count"
    ]
)


b3_step2c_df[
    "B3_signed_error"
] = (
    b3_step2c_df[
        "B3_SG_gated_count"
    ]
    -
    b3_step2c_df[
        "gt_count"
    ]
)


b3_step2c_df[
    "B2_abs_error"
] = (
    b3_step2c_df[
        "B2_signed_error"
    ]
    .abs()
)


b3_step2c_df[
    "B3_abs_error"
] = (
    b3_step2c_df[
        "B3_signed_error"
    ]
    .abs()
)


# Negative = improvement
# Positive = worsening
b3_step2c_df[
    "abs_error_delta_vs_B2S"
] = (
    b3_step2c_df[
        "B3_abs_error"
    ]
    -
    b3_step2c_df[
        "B2_abs_error"
    ]
)


# Positive = number of absolute-error units saved
b3_step2c_df[
    "absolute_error_reduction"
] = (
    -1.0
    *
    b3_step2c_df[
        "abs_error_delta_vs_B2S"
    ]
)


b3_step2c_df[
    "geometry_improves"
] = (
    b3_step2c_df[
        "abs_error_delta_vs_B2S"
    ]
    <
    0
)


b3_step2c_df[
    "geometry_worsens"
] = (
    b3_step2c_df[
        "abs_error_delta_vs_B2S"
    ]
    >
    0
)


# ------------------------------------------------------------
# 4. Inference-visible derived quantities
#
# Do NOT use GT count or density stratum here.
# ------------------------------------------------------------

eps_2c = 1e-12


b3_step2c_df[
    "refinable_fraction_of_C1_recovery"
] = (
    b3_step2c_df[
        "C1_recovery_geometry_refinable"
    ]
    /
    np.maximum(
        b3_step2c_df[
            "C1_recovery_count"
        ],
        1,
    )
)


b3_step2c_df[
    "split_candidate_fraction_of_C1_recovery"
] = (
    b3_step2c_df[
        "C1_recovery_split_candidates"
    ]
    /
    np.maximum(
        b3_step2c_df[
            "C1_recovery_count"
        ],
        1,
    )
)


b3_step2c_df[
    "geometry_extra_per_C1_recovery"
] = (
    b3_step2c_df[
        "G2_extra_units_refinable_only"
    ]
    /
    np.maximum(
        b3_step2c_df[
            "C1_recovery_count"
        ],
        1,
    )
)


b3_step2c_df[
    "geometry_extra_per_refinable_component"
] = (
    b3_step2c_df[
        "G2_extra_units_refinable_only"
    ]
    /
    np.maximum(
        b3_step2c_df[
            "C1_recovery_geometry_refinable"
        ],
        1,
    )
)


# Geometry correction relative to existing B2 estimate
b3_step2c_df[
    "geometry_increment_relative_to_B2"
] = (
    b3_step2c_df[
        "G2_extra_units_refinable_only"
    ]
    /
    np.maximum(
        b3_step2c_df[
            "B2_S_count"
        ],
        1e-6,
    )
)


# ------------------------------------------------------------
# 5. Concentration of improvement
# ------------------------------------------------------------

improvement_only_2c_df = (
    b3_step2c_df[
        b3_step2c_df[
            "absolute_error_reduction"
        ]
        >
        0
    ]
    .sort_values(
        "absolute_error_reduction",
        ascending=False,
    )
    .reset_index(
        drop=True
    )
)


total_positive_gain_2c = float(
    improvement_only_2c_df[
        "absolute_error_reduction"
    ]
    .sum()
)


concentration_rows_2c = []


for k in [
    1,
    3,
    5,
    10,
]:

    top_gain = float(
        improvement_only_2c_df[
            "absolute_error_reduction"
        ]
        .head(
            k
        )
        .sum()
    )


    concentration_rows_2c.append(
        {
            "top_k_improving_images":
                k,

            "absolute_error_reduction":
                top_gain,

            "fraction_of_all_positive_gain":
                (
                    top_gain
                    /
                    total_positive_gain_2c
                    if total_positive_gain_2c > 0
                    else np.nan
                ),
        }
    )


gain_concentration_2c_df = (
    pd.DataFrame(
        concentration_rows_2c
    )
)


# ------------------------------------------------------------
# 6. Leave-top-K robustness
#
# Recompute B2 vs B3 MAE after removing the images with the
# largest B3 improvements.
#
# This shows whether the overall result survives without the
# strongest rescue examples.
# ------------------------------------------------------------

robustness_rows_2c = []


ranked_improvement_indices_2c = (
    improvement_only_2c_df[
        "dataset_index"
    ]
    .tolist()
)


for k in [
    0,
    1,
    3,
    5,
    10,
]:

    excluded_indices = set(
        ranked_improvement_indices_2c[
            :
            k
        ]
    )


    retained_df = (
        b3_step2c_df[
            ~b3_step2c_df[
                "dataset_index"
            ]
            .isin(
                excluded_indices
            )
        ]
    )


    b2_mae = float(
        retained_df[
            "B2_abs_error"
        ]
        .mean()
    )


    b3_mae = float(
        retained_df[
            "B3_abs_error"
        ]
        .mean()
    )


    robustness_rows_2c.append(
        {
            "excluded_top_improvement_images":
                k,

            "remaining_images":
                int(
                    len(
                        retained_df
                    )
                ),

            "B2_MAE":
                b2_mae,

            "B3_MAE":
                b3_mae,

            "delta_MAE_B3_minus_B2":
                float(
                    b3_mae
                    -
                    b2_mae
                ),
        }
    )


leave_topk_robustness_2c_df = (
    pd.DataFrame(
        robustness_rows_2c
    )
)


# ------------------------------------------------------------
# 7. Geometry contribution concentration
#
# How concentrated are the 1567 added geometry units?
# ------------------------------------------------------------

geometry_ranked_2c_df = (
    b3_step2c_df
    .sort_values(
        "G2_extra_units_refinable_only",
        ascending=False,
    )
    .reset_index(
        drop=True
    )
)


total_geometry_units_2c = float(
    geometry_ranked_2c_df[
        "G2_extra_units_refinable_only"
    ]
    .sum()
)


geometry_concentration_rows_2c = []


for k in [
    1,
    3,
    5,
    10,
]:

    top_units = float(
        geometry_ranked_2c_df[
            "G2_extra_units_refinable_only"
        ]
        .head(
            k
        )
        .sum()
    )


    geometry_concentration_rows_2c.append(
        {
            "top_k_images":
                k,

            "geometry_extra_units":
                top_units,

            "fraction_of_all_geometry_units":
                (
                    top_units
                    /
                    total_geometry_units_2c
                    if total_geometry_units_2c > 0
                    else np.nan
                ),
        }
    )


geometry_concentration_2c_df = (
    pd.DataFrame(
        geometry_concentration_rows_2c
    )
)


# ------------------------------------------------------------
# 8. Univariate inference-feature discrimination
#
# Label:
#
#   1 = geometry improves B2
#   0 = geometry does not improve B2
#
# Only images where the geometry gate is ON are useful for
# this discrimination analysis, because OFF images receive
# zero geometry and therefore tie B2.
# ------------------------------------------------------------

active_2c_df = (
    b3_step2c_df[
        b3_step2c_df[
            "M1_G2_gate_ON"
        ]
        .astype(bool)
    ]
    .copy()
)


assert len(
    active_2c_df
) == 57


INFERENCE_FEATURES_2C = [
    "candidate_area_fraction",

    "C1_recovery_count",

    "C1_recovery_split_candidates",

    "C1_recovery_geometry_refinable",

    "refinable_fraction_of_C1_recovery",

    "split_candidate_fraction_of_C1_recovery",

    "G2_extra_units_refinable_only",

    "geometry_extra_per_C1_recovery",

    "geometry_extra_per_refinable_component",

    "geometry_increment_relative_to_B2",

    "B2_S_count",
]


y_improve_2c = (
    active_2c_df[
        "geometry_improves"
    ]
    .astype(int)
    .to_numpy()
)


feature_rows_2c = []


for feature in (
    INFERENCE_FEATURES_2C
):

    x = (
        active_2c_df[
            feature
        ]
        .to_numpy(
            dtype=float
        )
    )


    # AUC only if feature has >1 distinct value
    if len(
        np.unique(
            x
        )
    ) > 1:

        raw_auc = float(
            roc_auc_score(
                y_improve_2c,
                x,
            )
        )

        oriented_auc = max(
            raw_auc,
            1.0 - raw_auc,
        )

        direction = (
            "HIGHER -> improvement"
            if raw_auc >= 0.5
            else
            "LOWER -> improvement"
        )

    else:

        raw_auc = np.nan
        oriented_auc = np.nan
        direction = "constant"


    rho, p_value = spearmanr(
        x,
        active_2c_df[
            "abs_error_delta_vs_B2S"
        ]
        .to_numpy(
            dtype=float
        ),
    )


    feature_rows_2c.append(
        {
            "feature":
                feature,

            "raw_AUC":
                raw_auc,

            "oriented_AUC":
                oriented_auc,

            "direction":
                direction,

            "spearman_rho_vs_abs_error_delta":
                float(
                    rho
                ),

            "spearman_p":
                float(
                    p_value
                ),
        }
    )


adaptive_feature_diag_2c_df = (
    pd.DataFrame(
        feature_rows_2c
    )
    .sort_values(
        "oriented_AUC",
        ascending=False,
    )
    .reset_index(
        drop=True
    )
)


# ------------------------------------------------------------
# 9. Improve / worsen medians for interpretable features
# ------------------------------------------------------------

group_summary_rows_2c = []


for feature in (
    INFERENCE_FEATURES_2C
):

    improve_values = (
        active_2c_df.loc[
            active_2c_df[
                "geometry_improves"
            ],
            feature,
        ]
    )


    worsen_values = (
        active_2c_df.loc[
            active_2c_df[
                "geometry_worsens"
            ],
            feature,
        ]
    )


    group_summary_rows_2c.append(
        {
            "feature":
                feature,

            "improve_median":
                float(
                    improve_values.median()
                )
                if len(improve_values)
                else np.nan,

            "worsen_median":
                float(
                    worsen_values.median()
                )
                if len(worsen_values)
                else np.nan,

            "improve_mean":
                float(
                    improve_values.mean()
                )
                if len(improve_values)
                else np.nan,

            "worsen_mean":
                float(
                    worsen_values.mean()
                )
                if len(worsen_values)
                else np.nan,
        }
    )


adaptive_feature_group_summary_2c_df = (
    pd.DataFrame(
        group_summary_rows_2c
    )
)


# ------------------------------------------------------------
# 10. Density-stratum help / tie / hurt
#
# POST-HOC diagnostic only.
# ------------------------------------------------------------

density_help_rows_2c = []


for stratum in [
    "S1_0_20",
    "S2_20_40",
    "S3_40_60",
    "S4_60_80",
    "S5_80_95",
    "S6_95_100",
]:

    sdf = (
        b3_step2c_df[
            b3_step2c_df[
                "density_stratum"
            ]
            ==
            stratum
        ]
    )


    density_help_rows_2c.append(
        {
            "density_stratum":
                stratum,

            "num_images":
                int(
                    len(
                        sdf
                    )
                ),

            "geometry_active_images":
                int(
                    sdf[
                        "M1_G2_gate_ON"
                    ]
                    .astype(bool)
                    .sum()
                ),

            "improves":
                int(
                    sdf[
                        "geometry_improves"
                    ]
                    .sum()
                ),

            "ties":
                int(
                    (
                        np.isclose(
                            sdf[
                                "abs_error_delta_vs_B2S"
                            ],
                            0.0,
                        )
                    )
                    .sum()
                ),

            "worsens":
                int(
                    sdf[
                        "geometry_worsens"
                    ]
                    .sum()
                ),

            "mean_abs_error_delta":
                float(
                    sdf[
                        "abs_error_delta_vs_B2S"
                    ]
                    .mean()
                ),

            "median_abs_error_delta":
                float(
                    sdf[
                        "abs_error_delta_vs_B2S"
                    ]
                    .median()
                ),
        }
    )


density_help_hurt_2c_df = (
    pd.DataFrame(
        density_help_rows_2c
    )
)


# ------------------------------------------------------------
# 11. Top extreme geometry corrections
# ------------------------------------------------------------

largest_geometry_corrections_2c_df = (
    b3_step2c_df
    .sort_values(
        "G2_extra_units_refinable_only",
        ascending=False,
    )
    [
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "B2_S_count",
            "B3_SG_gated_count",

            "G2_extra_units_refinable_only",

            "candidate_area_fraction",
            "C1_recovery_count",
            "C1_recovery_geometry_refinable",

            "geometry_increment_relative_to_B2",

            "B2_abs_error",
            "B3_abs_error",
            "abs_error_delta_vs_B2S",
        ]
    ]
    .head(
        20
    )
)


# ------------------------------------------------------------
# 12. Save outputs
# ------------------------------------------------------------

B3_STEP2C_IMAGE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2C_geometry_robustness_per_image.csv"
)

B3_STEP2C_GAIN_CONCENTRATION_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2C_gain_concentration.csv"
)

B3_STEP2C_ROBUSTNESS_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2C_leave_topk_robustness.csv"
)

B3_STEP2C_GEOMETRY_CONCENTRATION_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2C_geometry_concentration.csv"
)

B3_STEP2C_FEATURE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2C_adaptive_feature_diagnostic.csv"
)

B3_STEP2C_FEATURE_GROUP_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2C_adaptive_feature_group_summary.csv"
)

B3_STEP2C_DENSITY_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2C_density_help_hurt.csv"
)


b3_step2c_df.to_csv(
    B3_STEP2C_IMAGE_FILE,
    index=False,
)

gain_concentration_2c_df.to_csv(
    B3_STEP2C_GAIN_CONCENTRATION_FILE,
    index=False,
)

leave_topk_robustness_2c_df.to_csv(
    B3_STEP2C_ROBUSTNESS_FILE,
    index=False,
)

geometry_concentration_2c_df.to_csv(
    B3_STEP2C_GEOMETRY_CONCENTRATION_FILE,
    index=False,
)

adaptive_feature_diag_2c_df.to_csv(
    B3_STEP2C_FEATURE_FILE,
    index=False,
)

adaptive_feature_group_summary_2c_df.to_csv(
    B3_STEP2C_FEATURE_GROUP_FILE,
    index=False,
)

density_help_hurt_2c_df.to_csv(
    B3_STEP2C_DENSITY_FILE,
    index=False,
)


# ------------------------------------------------------------
# 13. Report
# ------------------------------------------------------------

print("\nImprovement concentration")
print("-------------------------")

display(
    gain_concentration_2c_df
)


print("\nLeave-top-K robustness")
print("----------------------")

display(
    leave_topk_robustness_2c_df
)


print("\nGeometry-unit concentration")
print("---------------------------")

display(
    geometry_concentration_2c_df
)


print("\nInference-visible adaptive features")
print("-----------------------------------")

display(
    adaptive_feature_diag_2c_df
)


print("\nImprove vs worsen feature medians")
print("---------------------------------")

display(
    adaptive_feature_group_summary_2c_df
)


print("\nPost-hoc density help / tie / hurt")
print("----------------------------------")

display(
    density_help_hurt_2c_df
)


print("\nLargest geometry corrections")
print("----------------------------")

display(
    largest_geometry_corrections_2c_df
)


# ------------------------------------------------------------
# 14. Protocol report
# ------------------------------------------------------------

print("\nGT density used for routing             : NO")
print("Density used post-hoc only              : YES")

print("\nInference-visible features analysed      : YES")
print("Routing threshold selected              : NO")
print("Adaptive rule selected                  : NO")
print("Geometry weight selected                : NO")
print("Geometry cap selected                   : NO")

print("\nB2 changed                               : NO")
print("M1 thresholds changed                   : NO")
print("New inference run                       : NO")
print("Test set accessed                       : NO")

print("\nB3 Step 2C: PASS")

========================================================================================================================
B3 STEP 2C — ROBUSTNESS / CONCENTRATION / ADAPTIVE-SIGNAL DIAGNOSTIC
========================================================================================================================

Improvement concentration
-------------------------

,top_k_improving_images,absolute_error_reduction,fraction_of_all_positive_gain
0,1,542.0,0.504655
1,3,913.0,0.850093
2,5,959.0,0.892924
3,10,1047.0,0.974860

Leave-top-K robustness
----------------------

,excluded_top_improvement_images,remaining_images,B2_MAE,B3_MAE,delta_MAE_B3_minus_B2
0,0,100,70.900000,63.440000,-7.460000
1,1,99,65.752525,63.691919,-2.060606
2,3,97,55.608247,57.329897,1.721649
3,5,95,55.468421,57.710526,2.242105
4,10,90,45.483333,48.827778,3.344444

Geometry-unit concentration
---------------------------

   top_k_images  geometry_extra_units  fraction_of_all_geometry_units
0             1                 619.0                        0.395022
1             3                 990.0                        0.631780
2             5                1064.0                        0.679004
3            10                1215.0                        0.775367

Inference-visible adaptive features
-----------------------------------

,feature,raw_AUC,oriented_AUC,direction,spearman_rho_vs_abs_error_delta,spearman_p
0,geometry_extra_per_refinable_component,0.768293,0.768293,HIGHER -> improvement,0.004109,0.975801
1,G2_extra_units_refinable_only,0.749238,0.749238,HIGHER -> improvement,0.080091,0.553698
2,geometry_extra_per_C1_recovery,0.743140,0.743140,HIGHER -> improvement,0.055201,0.683391
3,geometry_increment_relative_to_B2,0.724848,0.724848,HIGHER -> improvement,0.105077,0.436629
4,C1_recovery_geometry_refinable,0.713415,0.713415,HIGHER -> improvement,0.107101,0.427798
5,C1_recovery_split_candidates,0.713415,0.713415,HIGHER -> improvement,0.107101,0.427798
6,C1_recovery_count,0.698171,0.698171,HIGHER -> improvement,0.081964,0.544430
7,split_candidate_fraction_of_C1_recovery,0.667683,0.667683,HIGHER -> improvement,0.209452,0.117889
8,refinable_fraction_of_C1_recovery,0.667683,0.667683,HIGHER -> improvement,0.209452,0.117889
9,B2_S_count,0.652439,0.652439,HIGHER -> improvement,-0.046606,0.730652
10,candidate_area_fraction,0.551829,0.551829,HIGHER -> improvement,0.106402,0.430835

Improve vs worsen feature medians
---------------------------------

,feature,improve_median,worsen_median,improve_mean,worsen_mean
0,candidate_area_fraction,0.945351,0.932353,0.936086,0.936302
1,C1_recovery_count,12.000000,9.000000,25.312500,11.407407
2,C1_recovery_split_candidates,3.500000,3.000000,7.000000,3.444444
3,C1_recovery_geometry_refinable,3.500000,3.000000,7.000000,3.444444
4,refinable_fraction_of_C1_recovery,0.298148,0.307692,0.391021,0.365787
5,split_candidate_fraction_of_C1_recovery,0.298148,0.307692,0.391021,0.365787
6,G2_extra_units_refinable_only,18.500000,10.000000,74.687500,13.481481
7,geometry_extra_per_C1_recovery,1.526455,1.125000,2.957071,2.064745
8,geometry_extra_per_refinable_component,5.000000,3.666667,7.032275,4.299971
9,geometry_increment_relative_to_B2,0.639205,0.461538,1.223958,0.580619
10,B2_S_count,32.250000,25.500000,52.656250,27.166667

Post-hoc density help / tie / hurt
----------------------------------

,density_stratum,num_images,geometry_active_images,improves,ties,worsens,mean_abs_error_delta,median_abs_error_delta
0,S1_0_20,20,11,0,13,7,4.10,0.0
1,S2_20_40,20,11,0,11,9,3.60,0.0
2,S3_40_60,20,12,4,8,8,4.75,0.0
3,S4_60_80,20,12,3,14,3,0.10,0.0
4,S5_80_95,10,3,3,7,0,-4.90,0.0
5,S6_95_100,10,8,6,4,0,-94.80,-9.0

Largest geometry corrections
----------------------------

,dataset_index,image_id,category,density_stratum,gt_count,B2_S_count,B3_SG_gated_count,G2_extra_units_refinable_only,candidate_area_fraction,C1_recovery_count,C1_recovery_geometry_refinable,geometry_increment_relative_to_B2,B2_abs_error,B3_abs_error,abs_error_delta_vs_B2S
32,253,975.jpg,birds,S6_95_100,718.0,137.5,756.5,619,0.860165,107,27,4.501818,580.5,38.5,-542.0
93,1192,6969.jpg,birds,S6_95_100,949.0,66.5,302.5,236,0.957437,53,14,3.548872,882.5,646.5,-236.0
92,1187,6931.jpg,birds,S6_95_100,355.0,122.0,257.0,135,0.915656,96,25,1.106557,233.0,98.0,-135.0
24,183,838.jpg,books,S5_80_95,113.0,82.5,122.5,40,0.880721,27,8,0.484848,30.5,9.5,-21.0
1,14,220.jpg,grapes,S4_60_80,59.0,66.0,100.0,34,0.968037,32,9,0.515152,7.0,41.0,34.0
40,365,2316.jpg,camels,S4_60_80,58.0,32.5,66.5,34,0.919276,28,8,1.046154,25.5,8.5,-17.0
91,1183,7305.jpg,birds,S3_40_60,31.0,34.0,66.0,32,0.921792,31,8,0.941176,3.0,35.0,32.0
90,1169,7421.jpg,horses,S1_0_20,10.0,35.0,67.0,32,0.946695,24,7,0.914286,25.0,57.0,32.0
78,968,5896.jpg,grapes,S4_60_80,55.0,44.0,73.0,29,0.920295,9,3,0.659091,11.0,18.0,7.0
58,564,3777.jpg,donuts tray,S2_20_40,14.0,26.5,50.5,24,0.973688,20,6,0.905660,12.5,36.5,24.0
34,298,1935.jpg,bottle caps,S5_80_95,175.0,83.5,107.5,24,0.857724,23,8,0.287425,91.5,67.5,-24.0
99,1269,7060.jpg,pills,S4_60_80,65.0,32.0,54.0,22,0.970365,14,4,0.687500,33.0,11.0,-22.0
83,1061,6286.jpg,pills,S4_60_80,49.0,5.0,25.0,20,1.000000,1,1,4.000000,44.0,24.0,-20.0
43,396,2846.jpg,chairs,S4_60_80,38.0,40.0,60.0,20,0.967373,23,6,0.500000,2.0,22.0,20.0
48,488,3543.jpg,chicken wings,S3_40_60,30.0,42.0,62.0,20,0.891366,12,6,0.476190,12.0,32.0,20.0
8,67,575.jpg,flamingos,S1_0_20,12.0,10.0,29.0,19,0.925856,9,3,1.900000,2.0,17.0,15.0
41,372,2412.jpg,horses,S2_20_40,15.0,16.0,35.0,19,0.999367,1,1,1.187500,1.0,20.0,19.0
77,938,5866.jpg,grapes,S6_95_100,267.0,76.0,93.0,17,0.933266,18,4,0.223684,191.0,174.0,-17.0
61,609,4535.jpg,flamingos,S3_40_60,22.0,9.0,26.0,17,0.927780,9,3,1.888889,13.0,4.0,-9.0
87,1149,6794.jpg,shirts,S3_40_60,27.0,34.5,50.5,16,0.875356,18,5,0.463768,7.5,23.5,16.0

GT density used for routing             : NO
Density used post-hoc only              : YES

Inference-visible features analysed      : YES
Routing threshold selected              : NO
Adaptive rule selected                  : NO
Geometry weight selected                : NO
Geometry cap selected                   : NO

B2 changed                               : NO
M1 thresholds changed                   : NO
New inference run                       : NO
Test set accessed                       : NO

B3 Step 2C: PASS

### **Finding 16:**

The improvement from geometry-integrated B2 is highly concentrated: the single strongest rescue case accounts for approximately 50% of the total positive error reduction, and the top three account for approximately 85%.

Removing the strongest case leaves a modest geometry benefit, whereas removing the top three reverses the overall advantage.

Post-hoc density analysis confirms a systematic regime difference: geometry is consistently harmful in sparse S1–S2 cases but consistently beneficial among activated S5–S6 cases.

Importantly, this behaviour is partially identifiable using inference-available geometry–semantic interaction features.

The strongest diagnostic is the number of additional G2 units per geometry-refinable C1 component (AUC ≈ 0.77), whereas the earlier candidate-area-fraction gate provides little further discrimination once activated.

These findings support a **two-stage adaptive geometry mechanism** rather than global geometry injection.

In [ ]:
# ============================================================
# B3 Step 2D — Two-Stage Adaptive Geometry-Gating Sensitivity
# ============================================================
#
# Purpose
# -------
# Test whether the Step-2B geometry correction becomes more
# reliable when activated using TWO inference-available stages:
#
# Stage 1:
#
#   candidate_area_fraction >= 0.85
#
# Stage 2:
#
#   geometry_extra_per_refinable_component >= threshold
#
#
# Coarse thresholds:
#
#   3.0
#   4.0
#   5.0
#
#
# IMPORTANT
# ---------
#
# These are DEVELOPMENT sensitivity values.
#
# No fine-grained threshold search is performed.
#
# Geometry strength is defined entirely from inference-visible
# quantities:
#
#   G2 extra units
#   --------------------------------
#   number of geometry-refinable C1 components
#
#
# If both gates pass:
#
#   prediction = B2-S + full frozen G2 extra multiplicity
#
# Otherwise:
#
#   prediction = B2-S
#
#
# No:
#   - geometry re-weighting
#   - geometry capping
#   - density routing
#   - GT-count routing
#   - semantic rule change
#   - B2 alpha change
#   - new Marigold inference
#   - test-set access
#
# ============================================================

import numpy as np
import pandas as pd


print("=" * 120)
print("B3 STEP 2D — TWO-STAGE ADAPTIVE GEOMETRY-GATING SENSITIVITY")
print("=" * 120)


# ------------------------------------------------------------
# 1. Guards
# ------------------------------------------------------------

assert "b3_step2c_df" in globals(), (
    "b3_step2c_df unavailable. Run Step 2C first."
)

assert "B3_TABLES_DIR" in globals()

assert len(
    b3_step2c_df
) == 100


required_cols_2d = {
    "dataset_index",
    "image_id",
    "category",
    "density_stratum",
    "gt_count",

    "B2_S_count",

    "candidate_area_fraction",
    "M1_G2_gate_ON",

    "C1_recovery_geometry_refinable",
    "G2_extra_units_refinable_only",

    "geometry_extra_per_refinable_component",
}


assert required_cols_2d.issubset(
    b3_step2c_df.columns
), (
    "Required Step-2C columns missing.\n"
    f"Missing: {sorted(required_cols_2d - set(b3_step2c_df.columns))}"
)


# ------------------------------------------------------------
# 2. Freeze coarse Step-2D sensitivity grid
#
# No additional values should be added after seeing results
# unless explicitly reported as a later fine-tuning stage.
# ------------------------------------------------------------

GEOMETRY_STRENGTH_THRESHOLDS_2D = [
    3.0,
    4.0,
    5.0,
]


FIRST_STAGE_AREA_THRESHOLD_2D = 0.85


# ------------------------------------------------------------
# 3. Build evaluation table
# ------------------------------------------------------------

b3_step2d_df = (
    b3_step2c_df[
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "B2_S_count",

            "candidate_area_fraction",
            "M1_G2_gate_ON",

            "C1_recovery_geometry_refinable",
            "G2_extra_units_refinable_only",

            "geometry_extra_per_refinable_component",
        ]
    ]
    .copy()
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


assert len(
    b3_step2d_df
) == 100


# ------------------------------------------------------------
# 4. Reconfirm first-stage gate identity
# ------------------------------------------------------------

recomputed_stage1_2d = (
    b3_step2d_df[
        "candidate_area_fraction"
    ]
    >=
    FIRST_STAGE_AREA_THRESHOLD_2D
)


assert (
    recomputed_stage1_2d
    ==
    b3_step2d_df[
        "M1_G2_gate_ON"
    ]
    .astype(bool)
).all(), (
    "Stored M1 gate does not exactly reproduce "
    "candidate_area_fraction >= 0.85."
)


b3_step2d_df[
    "stage1_gate_ON"
] = (
    recomputed_stage1_2d
)


assert int(
    b3_step2d_df[
        "stage1_gate_ON"
    ]
    .sum()
) == 57


# ------------------------------------------------------------
# 5. Reference predictions
# ------------------------------------------------------------

b3_step2d_df[
    "B2_S_reference"
] = (
    b3_step2d_df[
        "B2_S_count"
    ]
)


# Current Step-2B gated integration:
#
# Stage-1 only, with no second-stage strength gate.
b3_step2d_df[
    "B3_SG_stage1_only"
] = (
    b3_step2d_df[
        "B2_S_count"
    ]
    +
    b3_step2d_df[
        "G2_extra_units_refinable_only"
    ]
)


# ------------------------------------------------------------
# 6. Build two-stage adaptive variants
# ------------------------------------------------------------

adaptive_policy_rows_2d = []


for threshold in (
    GEOMETRY_STRENGTH_THRESHOLDS_2D
):

    stage2_col = (
        f"stage2_strength_ge_{threshold:.1f}"
    )

    adaptive_on_col = (
        f"adaptive_ON_t{threshold:.1f}"
    )

    pred_col = (
        f"B3_SG_adaptive_t{threshold:.1f}"
    )


    # --------------------------------------------------------
    # Stage 2:
    #
    # require sufficiently strong geometry multiplicity
    # within the refinable semantic components.
    # --------------------------------------------------------

    b3_step2d_df[
        stage2_col
    ] = (
        b3_step2d_df[
            "geometry_extra_per_refinable_component"
        ]
        >=
        threshold
    )


    # --------------------------------------------------------
    # Final adaptive decision:
    #
    # Stage 1 AND Stage 2
    # --------------------------------------------------------

    b3_step2d_df[
        adaptive_on_col
    ] = (
        b3_step2d_df[
            "stage1_gate_ON"
        ]
        &
        b3_step2d_df[
            stage2_col
        ]
    )


    # --------------------------------------------------------
    # Inject full frozen G2 correction only where adaptive ON.
    # --------------------------------------------------------

    b3_step2d_df[
        pred_col
    ] = (
        b3_step2d_df[
            "B2_S_count"
        ]
        +
        np.where(
            b3_step2d_df[
                adaptive_on_col
            ],

            b3_step2d_df[
                "G2_extra_units_refinable_only"
            ],

            0,
        )
    )


    adaptive_policy_rows_2d.append(
        {
            "threshold":
                threshold,

            "stage1_ON_images":
                int(
                    b3_step2d_df[
                        "stage1_gate_ON"
                    ]
                    .sum()
                ),

            "adaptive_ON_images":
                int(
                    b3_step2d_df[
                        adaptive_on_col
                    ]
                    .sum()
                ),

            "geometry_extra_units_used":
                int(
                    b3_step2d_df.loc[
                        b3_step2d_df[
                            adaptive_on_col
                        ],
                        "G2_extra_units_refinable_only",
                    ]
                    .sum()
                ),
        }
    )


adaptive_activation_summary_2d_df = (
    pd.DataFrame(
        adaptive_policy_rows_2d
    )
)


# ------------------------------------------------------------
# 7. Metric helper
# ------------------------------------------------------------

def metrics_b3_2d(
    df,
    pred_col,
    system_name,
):

    gt = (
        df[
            "gt_count"
        ]
        .to_numpy(
            dtype=float
        )
    )


    pred = (
        df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )


    signed = (
        pred
        -
        gt
    )


    abs_error = np.abs(
        signed
    )


    return {
        "system":
            system_name,

        "prediction_column":
            pred_col,

        "num_images":
            int(
                len(
                    df
                )
            ),

        "total_prediction":
            float(
                pred.sum()
            ),

        "MAE":
            float(
                abs_error.mean()
            ),

        "RMSE":
            float(
                np.sqrt(
                    np.mean(
                        signed ** 2
                    )
                )
            ),

        "mean_signed_error":
            float(
                signed.mean()
            ),

        "median_signed_error":
            float(
                np.median(
                    signed
                )
            ),

        "under_images":
            int(
                (
                    signed < 0
                )
                .sum()
            ),

        "exact_images":
            int(
                np.isclose(
                    signed,
                    0.0,
                )
                .sum()
            ),

        "over_images":
            int(
                (
                    signed > 0
                )
                .sum()
            ),
    }


# ------------------------------------------------------------
# 8. Overall metrics
# ------------------------------------------------------------

SYSTEMS_2D = [
    (
        "B2-S",
        "B2_S_reference",
    ),

    (
        "B3-SG-stage1-only",
        "B3_SG_stage1_only",
    ),
]


for threshold in (
    GEOMETRY_STRENGTH_THRESHOLDS_2D
):

    SYSTEMS_2D.append(
        (
            f"B3-SG-adaptive-t{threshold:.1f}",
            f"B3_SG_adaptive_t{threshold:.1f}",
        )
    )


overall_rows_2d = []


for system_name, pred_col in (
    SYSTEMS_2D
):

    overall_rows_2d.append(
        metrics_b3_2d(
            df=
                b3_step2d_df,

            pred_col=
                pred_col,

            system_name=
                system_name,
        )
    )


b3_step2d_overall_df = (
    pd.DataFrame(
        overall_rows_2d
    )
)


# ------------------------------------------------------------
# 9. Deltas vs B2-S
# ------------------------------------------------------------

b2_ref_metrics_2d = (
    b3_step2d_overall_df[
        b3_step2d_overall_df[
            "system"
        ]
        ==
        "B2-S"
    ]
    .iloc[0]
)


for metric in [
    "MAE",
    "RMSE",
    "mean_signed_error",
]:

    b3_step2d_overall_df[
        f"delta_{metric}_vs_B2S"
    ] = (
        b3_step2d_overall_df[
            metric
        ]
        -
        float(
            b2_ref_metrics_2d[
                metric
            ]
        )
    )


# ------------------------------------------------------------
# 10. Help / tie / hurt per adaptive variant
# ------------------------------------------------------------

gt_2d = (
    b3_step2d_df[
        "gt_count"
    ]
    .to_numpy(
        dtype=float
    )
)


b2_abs_error_2d = np.abs(
    b3_step2d_df[
        "B2_S_reference"
    ]
    .to_numpy(
        dtype=float
    )
    -
    gt_2d
)


help_hurt_rows_2d = []


for system_name, pred_col in (
    SYSTEMS_2D[
        1:
    ]
):

    pred = (
        b3_step2d_df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )


    abs_error = np.abs(
        pred
        -
        gt_2d
    )


    delta = (
        abs_error
        -
        b2_abs_error_2d
    )


    b3_step2d_df[
        f"{system_name}_abs_error_delta_vs_B2S"
    ] = delta


    help_hurt_rows_2d.append(
        {
            "system":
                system_name,

            "improves_images":
                int(
                    (
                        delta < 0
                    )
                    .sum()
                ),

            "ties_images":
                int(
                    np.isclose(
                        delta,
                        0.0,
                    )
                    .sum()
                ),

            "worsens_images":
                int(
                    (
                        delta > 0
                    )
                    .sum()
                ),

            "mean_abs_error_delta":
                float(
                    delta.mean()
                ),

            "median_abs_error_delta":
                float(
                    np.median(
                        delta
                    )
                ),
        }
    )


b3_step2d_help_hurt_df = (
    pd.DataFrame(
        help_hurt_rows_2d
    )
)


# ------------------------------------------------------------
# 11. Post-hoc density evaluation
#
# Density is NEVER used in the adaptive rule.
# ------------------------------------------------------------

STRATUM_ORDER_2D = [
    "S1_0_20",
    "S2_20_40",
    "S3_40_60",
    "S4_60_80",
    "S5_80_95",
    "S6_95_100",
]


stratum_rows_2d = []


for stratum in (
    STRATUM_ORDER_2D
):

    sdf = (
        b3_step2d_df[
            b3_step2d_df[
                "density_stratum"
            ]
            ==
            stratum
        ]
    )


    for system_name, pred_col in (
        SYSTEMS_2D
    ):

        gt = (
            sdf[
                "gt_count"
            ]
            .to_numpy(
                dtype=float
            )
        )


        pred = (
            sdf[
                pred_col
            ]
            .to_numpy(
                dtype=float
            )
        )


        signed = (
            pred
            -
            gt
        )


        stratum_rows_2d.append(
            {
                "density_stratum":
                    stratum,

                "system":
                    system_name,

                "MAE":
                    float(
                        np.abs(
                            signed
                        )
                        .mean()
                    ),

                "RMSE":
                    float(
                        np.sqrt(
                            np.mean(
                                signed ** 2
                            )
                        )
                    ),

                "mean_signed_error":
                    float(
                        signed.mean()
                    ),
            }
        )


b3_step2d_stratum_df = (
    pd.DataFrame(
        stratum_rows_2d
    )
)


# ------------------------------------------------------------
# 12. Leave-top-K robustness for every policy
#
# IMPORTANT:
#
# Ranking is based on each policy's OWN improvement relative
# to B2-S.
# ------------------------------------------------------------

robustness_rows_2d = []


for system_name, pred_col in (
    SYSTEMS_2D[
        1:
    ]
):

    pred = (
        b3_step2d_df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )


    abs_error = np.abs(
        pred
        -
        gt_2d
    )


    error_reduction = (
        b2_abs_error_2d
        -
        abs_error
    )


    temp_rank_df = pd.DataFrame(
        {
            "dataset_index":
                b3_step2d_df[
                    "dataset_index"
                ]
                .to_numpy(),

            "error_reduction":
                error_reduction,
        }
    )


    positive_rank = (
        temp_rank_df[
            temp_rank_df[
                "error_reduction"
            ]
            >
            0
        ]
        .sort_values(
            "error_reduction",
            ascending=False,
        )
    )


    ranked_indices = (
        positive_rank[
            "dataset_index"
        ]
        .tolist()
    )


    for k in [
        0,
        1,
        3,
        5,
    ]:

        exclude = set(
            ranked_indices[
                :
                k
            ]
        )


        keep_mask = (
            ~b3_step2d_df[
                "dataset_index"
            ]
            .isin(
                exclude
            )
        )


        retained_gt = (
            b3_step2d_df.loc[
                keep_mask,
                "gt_count",
            ]
            .to_numpy(
                dtype=float
            )
        )


        retained_b2 = (
            b3_step2d_df.loc[
                keep_mask,
                "B2_S_reference",
            ]
            .to_numpy(
                dtype=float
            )
        )


        retained_pred = (
            b3_step2d_df.loc[
                keep_mask,
                pred_col,
            ]
            .to_numpy(
                dtype=float
            )
        )


        retained_b2_mae = float(
            np.mean(
                np.abs(
                    retained_b2
                    -
                    retained_gt
                )
            )
        )


        retained_policy_mae = float(
            np.mean(
                np.abs(
                    retained_pred
                    -
                    retained_gt
                )
            )
        )


        robustness_rows_2d.append(
            {
                "system":
                    system_name,

                "excluded_top_improvements":
                    k,

                "remaining_images":
                    int(
                        keep_mask.sum()
                    ),

                "B2_MAE":
                    retained_b2_mae,

                "policy_MAE":
                    retained_policy_mae,

                "delta_MAE_policy_minus_B2":
                    float(
                        retained_policy_mae
                        -
                        retained_b2_mae
                    ),
            }
        )


b3_step2d_robustness_df = (
    pd.DataFrame(
        robustness_rows_2d
    )
)


# ------------------------------------------------------------
# 13. Activation by density — diagnostic only
# ------------------------------------------------------------

activation_density_rows_2d = []


for threshold in (
    GEOMETRY_STRENGTH_THRESHOLDS_2D
):

    adaptive_col = (
        f"adaptive_ON_t{threshold:.1f}"
    )


    for stratum in (
        STRATUM_ORDER_2D
    ):

        sdf = (
            b3_step2d_df[
                b3_step2d_df[
                    "density_stratum"
                ]
                ==
                stratum
            ]
        )


        activation_density_rows_2d.append(
            {
                "threshold":
                    threshold,

                "density_stratum":
                    stratum,

                "num_images":
                    int(
                        len(
                            sdf
                        )
                    ),

                "adaptive_ON_images":
                    int(
                        sdf[
                            adaptive_col
                        ]
                        .sum()
                    ),

                "activation_fraction":
                    float(
                        sdf[
                            adaptive_col
                        ]
                        .mean()
                    ),
            }
        )


b3_step2d_activation_density_df = (
    pd.DataFrame(
        activation_density_rows_2d
    )
)


# ------------------------------------------------------------
# 14. Save artifacts
# ------------------------------------------------------------

B3_STEP2D_IMAGE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2D_adaptive_geometry_per_image.csv"
)

B3_STEP2D_OVERALL_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2D_adaptive_geometry_overall.csv"
)

B3_STEP2D_HELP_HURT_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2D_adaptive_geometry_help_hurt.csv"
)

B3_STEP2D_STRATUM_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2D_adaptive_geometry_by_density.csv"
)

B3_STEP2D_ROBUSTNESS_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2D_adaptive_geometry_robustness.csv"
)

B3_STEP2D_ACTIVATION_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2D_adaptive_activation_by_density.csv"
)

B3_STEP2D_SUMMARY_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2D_adaptive_activation_summary.csv"
)


b3_step2d_df.to_csv(
    B3_STEP2D_IMAGE_FILE,
    index=False,
)

b3_step2d_overall_df.to_csv(
    B3_STEP2D_OVERALL_FILE,
    index=False,
)

b3_step2d_help_hurt_df.to_csv(
    B3_STEP2D_HELP_HURT_FILE,
    index=False,
)

b3_step2d_stratum_df.to_csv(
    B3_STEP2D_STRATUM_FILE,
    index=False,
)

b3_step2d_robustness_df.to_csv(
    B3_STEP2D_ROBUSTNESS_FILE,
    index=False,
)

b3_step2d_activation_density_df.to_csv(
    B3_STEP2D_ACTIVATION_FILE,
    index=False,
)

adaptive_activation_summary_2d_df.to_csv(
    B3_STEP2D_SUMMARY_FILE,
    index=False,
)


# ------------------------------------------------------------
# 15. Reports
# ------------------------------------------------------------

print("\nAdaptive activation summary")
print("---------------------------")

display(
    adaptive_activation_summary_2d_df
)


print("\nOverall adaptive-gating sensitivity")
print("-----------------------------------")

display(
    b3_step2d_overall_df[
        [
            "system",
            "total_prediction",
            "MAE",
            "RMSE",
            "mean_signed_error",
            "under_images",
            "exact_images",
            "over_images",
            "delta_MAE_vs_B2S",
            "delta_RMSE_vs_B2S",
        ]
    ]
)


print("\nHelp / tie / hurt versus B2-S")
print("-----------------------------")

display(
    b3_step2d_help_hurt_df
)


print("\nMAE by density stratum")
print("----------------------")

display(
    b3_step2d_stratum_df
    .pivot(
        index=
            "density_stratum",

        columns=
            "system",

        values=
            "MAE",
    )
)


print("\nLeave-top-K robustness")
print("----------------------")

display(
    b3_step2d_robustness_df
)


print("\nAdaptive activation by density — POST-HOC ONLY")
print("----------------------------------------------")

display(
    b3_step2d_activation_density_df
)


# ------------------------------------------------------------
# 16. Protocol report
# ------------------------------------------------------------

print("\nFirst-stage gate                         : candidate_area_fraction >= 0.85")
print(
    "Second-stage thresholds                :",
    GEOMETRY_STRENGTH_THRESHOLDS_2D,
)

print(
    "Second-stage feature                   : "
    "geometry_extra_per_refinable_component"
)

print("\nGT used in routing                       : NO")
print("Density used in routing                  : NO")
print("Category used in routing                 : NO")

print("\nDevelopment sensitivity                  : YES")
print("Fine-grained threshold search            : NO")
print("Final adaptive threshold frozen          : NO")

print("\nGeometry weight changed                  : NO")
print("Geometry cap introduced                  : NO")
print("B2 semantic rule changed                 : NO")
print("B2 alpha changed                         : NO")
print("M1 thresholds changed                    : NO")

print("\nNew inference run                        : NO")
print("Test set accessed                        : NO")

print("\nB3 Step 2D: PASS")

========================================================================================================================
B3 STEP 2D — TWO-STAGE ADAPTIVE GEOMETRY-GATING SENSITIVITY
========================================================================================================================

Adaptive activation summary
---------------------------

   threshold  stage1_ON_images  adaptive_ON_images  geometry_extra_units_used
0        3.0                57                  32                       1515
1        4.0                57                  24                       1375
2        5.0                57                  16                       1205

Overall adaptive-gating sensitivity
-----------------------------------

,system,total_prediction,MAE,RMSE,mean_signed_error,under_images,exact_images,over_images,delta_MAE_vs_B2S,delta_RMSE_vs_B2S
0,B2-S,3842.0,70.90,260.272722,-62.03,46,7,47,0.00,0.000000
1,B3-SG-stage1-only,5409.0,63.44,245.066236,-46.36,38,5,57,-7.46,-15.206486
2,B3-SG-adaptive-t3.0,5357.0,63.14,245.065746,-46.88,39,6,55,-7.76,-15.206976
3,B3-SG-adaptive-t4.0,5217.0,62.22,245.055606,-48.28,39,7,54,-8.68,-15.217116
4,B3-SG-adaptive-t5.0,5047.0,61.63,245.550993,-49.98,40,7,53,-9.27,-14.721730

Help / tie / hurt versus B2-S
-----------------------------

,system,improves_images,ties_images,worsens_images,mean_abs_error_delta,median_abs_error_delta
0,B3-SG-stage1-only,16,57,27,-7.46,0.0
1,B3-SG-adaptive-t3.0,13,68,19,-7.76,0.0
2,B3-SG-adaptive-t4.0,12,76,12,-8.68,0.0
3,B3-SG-adaptive-t5.0,9,84,7,-9.27,0.0

MAE by density stratum
----------------------

system,B2-S,B3-SG-adaptive-t3.0,B3-SG-adaptive-t4.0,B3-SG-adaptive-t5.0,B3-SG-stage1-only
density_stratum,,,,,
S1_0_20,5.575,9.575,9.275,6.975,9.675
S2_20_40,7.950,11.100,10.550,9.150,11.550
S3_40_60,9.950,13.550,11.300,9.700,14.700
S4_60_80,21.225,21.325,18.625,19.475,21.325
S5_80_95,40.550,36.050,38.450,38.450,35.650
S6_95_100,579.050,484.250,484.250,487.250,484.250

Leave-top-K robustness
----------------------

,system,excluded_top_improvements,remaining_images,B2_MAE,policy_MAE,delta_MAE_policy_minus_B2
0,B3-SG-stage1-only,0,100,70.900000,63.440000,-7.460000
1,B3-SG-stage1-only,1,99,65.752525,63.691919,-2.060606
2,B3-SG-stage1-only,3,97,55.608247,57.329897,1.721649
3,B3-SG-stage1-only,5,95,55.468421,57.710526,2.242105
4,B3-SG-adaptive-t3.0,0,100,70.900000,63.140000,-7.760000
5,B3-SG-adaptive-t3.0,1,99,65.752525,63.388889,-2.363636
6,B3-SG-adaptive-t3.0,3,97,55.608247,57.020619,1.412371
7,B3-SG-adaptive-t3.0,5,95,55.468421,57.394737,1.926316
8,B3-SG-adaptive-t4.0,0,100,70.900000,62.220000,-8.680000
9,B3-SG-adaptive-t4.0,1,99,65.752525,62.459596,-3.292929
10,B3-SG-adaptive-t4.0,3,97,55.608247,56.072165,0.463918
11,B3-SG-adaptive-t4.0,5,95,56.110526,57.036842,0.926316
12,B3-SG-adaptive-t5.0,0,100,70.900000,61.630000,-9.270000
13,B3-SG-adaptive-t5.0,1,99,65.752525,61.863636,-3.888889
14,B3-SG-adaptive-t5.0,3,97,55.608247,55.463918,-0.144330
15,B3-SG-adaptive-t5.0,5,95,56.110526,56.415789,0.305263

Adaptive activation by density — POST-HOC ONLY
----------------------------------------------

,threshold,density_stratum,num_images,adaptive_ON_images,activation_fraction
0,3.0,S1_0_20,20,6,0.30
1,3.0,S2_20_40,20,5,0.25
2,3.0,S3_40_60,20,7,0.35
3,3.0,S4_60_80,20,6,0.30
4,3.0,S5_80_95,10,2,0.20
5,3.0,S6_95_100,10,6,0.60
6,4.0,S1_0_20,20,5,0.25
7,4.0,S2_20_40,20,4,0.20
8,4.0,S3_40_60,20,4,0.20
9,4.0,S4_60_80,20,4,0.20
10,4.0,S5_80_95,10,1,0.10
11,4.0,S6_95_100,10,6,0.60
12,5.0,S1_0_20,20,3,0.15
13,5.0,S2_20_40,20,2,0.10
14,5.0,S3_40_60,20,3,0.15
15,5.0,S4_60_80,20,3,0.15
16,5.0,S5_80_95,10,1,0.10
17,5.0,S6_95_100,10,4,0.40

First-stage gate                         : candidate_area_fraction >= 0.85
Second-stage thresholds                : [3.0, 4.0, 5.0]
Second-stage feature                   : geometry_extra_per_refinable_component

GT used in routing                       : NO
Density used in routing                  : NO
Category used in routing                 : NO

Development sensitivity                  : YES
Fine-grained threshold search            : NO
Final adaptive threshold frozen          : NO

Geometry weight changed                  : NO
Geometry cap introduced                  : NO
B2 semantic rule changed                 : NO
B2 alpha changed                         : NO
M1 thresholds changed                    : NO

New inference run                        : NO
Test set accessed                        : NO

B3 Step 2D: PASS

### **Finding 17:**

A two-stage adaptive geometry gate improves the reliability of geometry integration within B2.

Retaining the semantic eligibility gate (candidate_area_fraction ≥ 0.85) and adding a geometry-strength criterion based on additional G2 units per refinable C1 component progressively reduces harmful interventions.

Among the coarse thresholds tested, \(t=5\) achieves the lowest MAE (61.63), improving B2-S by 9.27 MAE while reducing the number of worsened images from 27 under the stage-1-only rule to 7.

The adaptive rule also improves robustness to extreme rescue cases and naturally concentrates activation in denser scenes without using GT density as an input.

These results support an **adaptive semantic→geometry gating architecture** rather than global geometry application.

In [ ]:
# ============================================================
# B3 Step 2E — Semantic / Geometry Factorial Ablation
# ============================================================
#
# Purpose
# -------
# Determine whether the existing activation-based D contribution
# remains useful after adaptive Marigold geometry is integrated.
#
#
# Factorial systems
# -----------------
#
# B0
#   Unguided SAM2 anchor.
#
# S
#   B0 + C1 raw recovery
#
# SD
#   B0 + C1 + effective D
#
#   This is EXACTLY the frozen B2-S system:
#
#       D effective contribution =
#       existing gated, alpha=0.5 Step3D contribution
#
# G is NOT included.
#
#
# SG
#   B0 + C1 + adaptive geometry
#
#   D is removed.
#
#
# SDG
#   B0 + C1 + effective D + adaptive geometry
#
#   This reproduces the provisional Step-2D adaptive t=5 system.
#
#
# IMPORTANT
# ---------
#
# D is NOT raw D evidence here.
#
# It is the effective D contribution already frozen inside B2-S:
#
#       D_eff = B2-S - (B0 + C1)
#
# Therefore this experiment changes no D configuration.
#
#
# Geometry G:
#
#   Stage 1:
#       candidate_area_fraction >= 0.85
#
#   Stage 2:
#       geometry_extra_per_refinable_component >= 5
#
#   Correction:
#       full frozen G2 extra multiplicity
#
#
# No:
#   - new semantic evidence
#   - new D threshold
#   - new D weight
#   - new geometry threshold
#   - geometry weighting
#   - density routing
#   - GT routing
#   - new inference
#   - test access
#
# ============================================================

import numpy as np
import pandas as pd


print("=" * 120)
print("B3 STEP 2E — SEMANTIC / GEOMETRY FACTORIAL ABLATION")
print("=" * 120)


# ------------------------------------------------------------
# 1. Guards
# ------------------------------------------------------------

assert "b3_step1_df" in globals(), (
    "b3_step1_df unavailable. Run B3 Step 1 first."
)

assert "b3_step2a_per_image_df" in globals(), (
    "b3_step2a_per_image_df unavailable. Run Step 2A first."
)

assert "b3_step2d_df" in globals(), (
    "b3_step2d_df unavailable. Run Step 2D first."
)

assert "B3_TABLES_DIR" in globals()


assert len(b3_step1_df) == 100
assert len(b3_step2a_per_image_df) == 100
assert len(b3_step2d_df) == 100


# ------------------------------------------------------------
# 2. Freeze the provisional geometry rule inherited from 2D
#
# This is an ABLATION of evidence sources.
# We do NOT tune t again here.
# ------------------------------------------------------------

GEOMETRY_THRESHOLD_2E = 5.0

ADAPTIVE_GATE_COL_2E = (
    "adaptive_ON_t5.0"
)

ADAPTIVE_PRED_COL_2E = (
    "B3_SG_adaptive_t5.0"
)


assert ADAPTIVE_GATE_COL_2E in b3_step2d_df.columns
assert ADAPTIVE_PRED_COL_2E in b3_step2d_df.columns


# ------------------------------------------------------------
# 3. Build aligned factorial table
# ------------------------------------------------------------

b3_step2e_df = (
    b3_step1_df[
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",
            "B0_count",
        ]
    ]
    .merge(
        b3_step2a_per_image_df[
            [
                "dataset_index",
                "C1_recovery_count",
            ]
        ],
        on="dataset_index",
        how="left",
        validate="one_to_one",
    )
    .merge(
        b3_step2d_df[
            [
                "dataset_index",

                "B2_S_reference",

                "candidate_area_fraction",
                "C1_recovery_geometry_refinable",
                "G2_extra_units_refinable_only",
                "geometry_extra_per_refinable_component",

                "stage1_gate_ON",
                ADAPTIVE_GATE_COL_2E,
                ADAPTIVE_PRED_COL_2E,
            ]
        ],
        on="dataset_index",
        how="left",
        validate="one_to_one",
    )
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


assert len(
    b3_step2e_df
) == 100


assert (
    b3_step2e_df
    .notna()
    .all()
    .all()
)


# ------------------------------------------------------------
# 4. S = B0 + C1
#
# This should reproduce the earlier raw C1 recovery experiment.
# ------------------------------------------------------------

b3_step2e_df[
    "S_B0_C1_count"
] = (
    b3_step2e_df[
        "B0_count"
    ]
    +
    b3_step2e_df[
        "C1_recovery_count"
    ]
)


# ------------------------------------------------------------
# 5. SD = frozen B2-S
#
# Recover the EFFECTIVE D contribution by subtraction.
#
# D_effective already incorporates:
#
#   - the frozen Step3D semantic rule
#   - D6B-T-native / C1-supported evidence
#   - alpha = 0.5
#   - C1_added >= 10 gate
#
# Nothing is recomputed here.
# ------------------------------------------------------------

b3_step2e_df[
    "D_effective_contribution"
] = (
    b3_step2e_df[
        "B2_S_reference"
    ]
    -
    b3_step2e_df[
        "S_B0_C1_count"
    ]
)


assert (
    b3_step2e_df[
        "D_effective_contribution"
    ]
    >=
    -1e-12
).all(), (
    "Frozen B2-S contains a negative effective D contribution."
)


# Clean numerical noise if any
b3_step2e_df[
    "D_effective_contribution"
] = (
    b3_step2e_df[
        "D_effective_contribution"
    ]
    .clip(
        lower=0.0
    )
)


b3_step2e_df[
    "SD_B0_C1_D_count"
] = (
    b3_step2e_df[
        "S_B0_C1_count"
    ]
    +
    b3_step2e_df[
        "D_effective_contribution"
    ]
)


# Exact B2-S identity
assert np.allclose(
    b3_step2e_df[
        "SD_B0_C1_D_count"
    ],
    b3_step2e_df[
        "B2_S_reference"
    ],
    rtol=0.0,
    atol=1e-12,
)


# ------------------------------------------------------------
# 6. G effective contribution
#
# Full frozen G2 extra multiplicity only where adaptive t=5
# is ON.
# ------------------------------------------------------------

b3_step2e_df[
    "G_effective_contribution"
] = np.where(
    b3_step2e_df[
        ADAPTIVE_GATE_COL_2E
    ]
    .astype(bool),

    b3_step2e_df[
        "G2_extra_units_refinable_only"
    ],

    0.0,
)


assert (
    b3_step2e_df[
        "G_effective_contribution"
    ]
    >=
    0
).all()


# ------------------------------------------------------------
# 7. SG = B0 + C1 + G
#
# D removed, geometry retained.
# ------------------------------------------------------------

b3_step2e_df[
    "SG_B0_C1_G_count"
] = (
    b3_step2e_df[
        "S_B0_C1_count"
    ]
    +
    b3_step2e_df[
        "G_effective_contribution"
    ]
)


# ------------------------------------------------------------
# 8. SDG = B0 + C1 + D + G
#
# This must reproduce Step-2D adaptive t=5 exactly.
# ------------------------------------------------------------

b3_step2e_df[
    "SDG_B0_C1_D_G_count"
] = (
    b3_step2e_df[
        "S_B0_C1_count"
    ]
    +
    b3_step2e_df[
        "D_effective_contribution"
    ]
    +
    b3_step2e_df[
        "G_effective_contribution"
    ]
)


assert np.allclose(
    b3_step2e_df[
        "SDG_B0_C1_D_G_count"
    ],
    b3_step2e_df[
        ADAPTIVE_PRED_COL_2E
    ],
    rtol=0.0,
    atol=1e-12,
), (
    "SDG does not exactly reproduce Step-2D adaptive t=5."
)


# ------------------------------------------------------------
# 9. Metric helper
# ------------------------------------------------------------

def metrics_b3_2e(
    df,
    pred_col,
    system_name,
    semantic_C1,
    activation_D,
    geometry_G,
):

    gt = (
        df[
            "gt_count"
        ]
        .to_numpy(
            dtype=float
        )
    )

    pred = (
        df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    signed = (
        pred
        -
        gt
    )

    return {
        "system":
            system_name,

        "C1":
            bool(
                semantic_C1
            ),

        "D":
            bool(
                activation_D
            ),

        "G":
            bool(
                geometry_G
            ),

        "num_images":
            int(
                len(
                    df
                )
            ),

        "total_prediction":
            float(
                pred.sum()
            ),

        "mean_prediction":
            float(
                pred.mean()
            ),

        "MAE":
            float(
                np.mean(
                    np.abs(
                        signed
                    )
                )
            ),

        "RMSE":
            float(
                np.sqrt(
                    np.mean(
                        signed ** 2
                    )
                )
            ),

        "mean_signed_error":
            float(
                signed.mean()
            ),

        "under_images":
            int(
                (
                    signed < 0
                )
                .sum()
            ),

        "exact_images":
            int(
                np.isclose(
                    signed,
                    0.0,
                )
                .sum()
            ),

        "over_images":
            int(
                (
                    signed > 0
                )
                .sum()
            ),
    }


# ------------------------------------------------------------
# 10. Factorial systems
# ------------------------------------------------------------

SYSTEMS_2E = [
    (
        "B0",
        "B0_count",
        False,
        False,
        False,
    ),

    (
        "S = B0+C1",
        "S_B0_C1_count",
        True,
        False,
        False,
    ),

    (
        "SD = B0+C1+D",
        "SD_B0_C1_D_count",
        True,
        True,
        False,
    ),

    (
        "SG = B0+C1+G",
        "SG_B0_C1_G_count",
        True,
        False,
        True,
    ),

    (
        "SDG = B0+C1+D+G",
        "SDG_B0_C1_D_G_count",
        True,
        True,
        True,
    ),
]


overall_rows_2e = []


for (
    system_name,
    pred_col,
    has_c1,
    has_d,
    has_g,
) in SYSTEMS_2E:

    overall_rows_2e.append(
        metrics_b3_2e(
            df=
                b3_step2e_df,

            pred_col=
                pred_col,

            system_name=
                system_name,

            semantic_C1=
                has_c1,

            activation_D=
                has_d,

            geometry_G=
                has_g,
        )
    )


b3_step2e_overall_df = (
    pd.DataFrame(
        overall_rows_2e
    )
)


# ------------------------------------------------------------
# 11. Regression checks against known checkpoints
# ------------------------------------------------------------

def get_metric_2e(
    system,
    metric,
):

    return float(
        b3_step2e_overall_df.loc[
            b3_step2e_overall_df[
                "system"
            ]
            ==
            system,
            metric,
        ]
        .iloc[0]
    )


# B0
assert np.isclose(
    get_metric_2e(
        "B0",
        "MAE",
    ),
    80.69,
    atol=1e-8,
)


# Raw C1 recovery
assert np.isclose(
    get_metric_2e(
        "S = B0+C1",
        "MAE",
    ),
    72.00,
    atol=1e-8,
), (
    "S = B0+C1 does not reproduce the frozen raw-C1 "
    "recovery checkpoint."
)


# Current frozen B2-S
assert np.isclose(
    get_metric_2e(
        "SD = B0+C1+D",
        "MAE",
    ),
    70.90,
    atol=1e-8,
)


# Step-2D adaptive t=5
assert np.isclose(
    get_metric_2e(
        "SDG = B0+C1+D+G",
        "MAE",
    ),
    61.63,
    atol=1e-8,
)


# ------------------------------------------------------------
# 12. Marginal contribution table
#
# MAE delta:
#
# negative = improves
# positive = worsens
# ------------------------------------------------------------

S_MAE_2E = get_metric_2e(
    "S = B0+C1",
    "MAE",
)

SD_MAE_2E = get_metric_2e(
    "SD = B0+C1+D",
    "MAE",
)

SG_MAE_2E = get_metric_2e(
    "SG = B0+C1+G",
    "MAE",
)

SDG_MAE_2E = get_metric_2e(
    "SDG = B0+C1+D+G",
    "MAE",
)


S_RMSE_2E = get_metric_2e(
    "S = B0+C1",
    "RMSE",
)

SD_RMSE_2E = get_metric_2e(
    "SD = B0+C1+D",
    "RMSE",
)

SG_RMSE_2E = get_metric_2e(
    "SG = B0+C1+G",
    "RMSE",
)

SDG_RMSE_2E = get_metric_2e(
    "SDG = B0+C1+D+G",
    "RMSE",
)


b3_step2e_marginal_df = pd.DataFrame(
    [
        {
            "comparison":
                "D added without G: S -> SD",

            "added_evidence":
                "D",

            "starting_system":
                "S",

            "ending_system":
                "SD",

            "delta_MAE":
                SD_MAE_2E
                -
                S_MAE_2E,

            "delta_RMSE":
                SD_RMSE_2E
                -
                S_RMSE_2E,
        },

        {
            "comparison":
                "D added with G: SG -> SDG",

            "added_evidence":
                "D",

            "starting_system":
                "SG",

            "ending_system":
                "SDG",

            "delta_MAE":
                SDG_MAE_2E
                -
                SG_MAE_2E,

            "delta_RMSE":
                SDG_RMSE_2E
                -
                SG_RMSE_2E,
        },

        {
            "comparison":
                "G added without D: S -> SG",

            "added_evidence":
                "G",

            "starting_system":
                "S",

            "ending_system":
                "SG",

            "delta_MAE":
                SG_MAE_2E
                -
                S_MAE_2E,

            "delta_RMSE":
                SG_RMSE_2E
                -
                S_RMSE_2E,
        },

        {
            "comparison":
                "G added with D: SD -> SDG",

            "added_evidence":
                "G",

            "starting_system":
                "SD",

            "ending_system":
                "SDG",

            "delta_MAE":
                SDG_MAE_2E
                -
                SD_MAE_2E,

            "delta_RMSE":
                SDG_RMSE_2E
                -
                SD_RMSE_2E,
        },
    ]
)


# ------------------------------------------------------------
# 13. Contribution / overlap structure
# ------------------------------------------------------------

b3_step2e_df[
    "D_active"
] = (
    b3_step2e_df[
        "D_effective_contribution"
    ]
    >
    0
)


b3_step2e_df[
    "G_active"
] = (
    b3_step2e_df[
        "G_effective_contribution"
    ]
    >
    0
)


b3_step2e_df[
    "evidence_activation_group"
] = np.select(
    [
        (
            ~b3_step2e_df[
                "D_active"
            ]
            &
            ~b3_step2e_df[
                "G_active"
            ]
        ),

        (
            b3_step2e_df[
                "D_active"
            ]
            &
            ~b3_step2e_df[
                "G_active"
            ]
        ),

        (
            ~b3_step2e_df[
                "D_active"
            ]
            &
            b3_step2e_df[
                "G_active"
            ]
        ),

        (
            b3_step2e_df[
                "D_active"
            ]
            &
            b3_step2e_df[
                "G_active"
            ]
        ),
    ],
    [
        "neither",
        "D_only",
        "G_only",
        "D_and_G",
    ],
    default="ERROR",
)


assert not (
    b3_step2e_df[
        "evidence_activation_group"
    ]
    ==
    "ERROR"
).any()


activation_rows_2e = []


for group in [
    "neither",
    "D_only",
    "G_only",
    "D_and_G",
]:

    gdf = (
        b3_step2e_df[
            b3_step2e_df[
                "evidence_activation_group"
            ]
            ==
            group
        ]
    )


    activation_rows_2e.append(
        {
            "activation_group":
                group,

            "num_images":
                int(
                    len(
                        gdf
                    )
                ),

            "total_D_effective":
                float(
                    gdf[
                        "D_effective_contribution"
                    ]
                    .sum()
                ),

            "total_G_effective":
                float(
                    gdf[
                        "G_effective_contribution"
                    ]
                    .sum()
                ),

            "mean_GT":
                float(
                    gdf[
                        "gt_count"
                    ]
                    .mean()
                )
                if len(gdf)
                else np.nan,
        }
    )


b3_step2e_activation_df = (
    pd.DataFrame(
        activation_rows_2e
    )
)


# ------------------------------------------------------------
# 14. Per-image marginal help / tie / hurt
# ------------------------------------------------------------

gt_2e = (
    b3_step2e_df[
        "gt_count"
    ]
    .to_numpy(
        dtype=float
    )
)


def per_image_comparison_2e(
    base_col,
    added_col,
    label,
):

    base_pred = (
        b3_step2e_df[
            base_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    added_pred = (
        b3_step2e_df[
            added_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    base_abs = np.abs(
        base_pred
        -
        gt_2e
    )

    added_abs = np.abs(
        added_pred
        -
        gt_2e
    )

    delta = (
        added_abs
        -
        base_abs
    )

    return {
        "comparison":
            label,

        "improves_images":
            int(
                (
                    delta < 0
                )
                .sum()
            ),

        "ties_images":
            int(
                np.isclose(
                    delta,
                    0.0,
                )
                .sum()
            ),

        "worsens_images":
            int(
                (
                    delta > 0
                )
                .sum()
            ),

        "mean_abs_error_delta":
            float(
                delta.mean()
            ),

        "median_abs_error_delta":
            float(
                np.median(
                    delta
                )
            ),
    }


b3_step2e_help_hurt_df = pd.DataFrame(
    [
        per_image_comparison_2e(
            "S_B0_C1_count",
            "SD_B0_C1_D_count",
            "D without G: S -> SD",
        ),

        per_image_comparison_2e(
            "SG_B0_C1_G_count",
            "SDG_B0_C1_D_G_count",
            "D with G: SG -> SDG",
        ),

        per_image_comparison_2e(
            "S_B0_C1_count",
            "SG_B0_C1_G_count",
            "G without D: S -> SG",
        ),

        per_image_comparison_2e(
            "SD_B0_C1_D_count",
            "SDG_B0_C1_D_G_count",
            "G with D: SD -> SDG",
        ),
    ]
)


# ------------------------------------------------------------
# 15. Density-stratum factorial comparison
#
# POST-HOC ONLY.
# ------------------------------------------------------------

STRATUM_ORDER_2E = [
    "S1_0_20",
    "S2_20_40",
    "S3_40_60",
    "S4_60_80",
    "S5_80_95",
    "S6_95_100",
]


stratum_rows_2e = []


for stratum in (
    STRATUM_ORDER_2E
):

    sdf = (
        b3_step2e_df[
            b3_step2e_df[
                "density_stratum"
            ]
            ==
            stratum
        ]
    )


    for (
        system_name,
        pred_col,
        _,
        _,
        _,
    ) in SYSTEMS_2E:

        gt = (
            sdf[
                "gt_count"
            ]
            .to_numpy(
                dtype=float
            )
        )

        pred = (
            sdf[
                pred_col
            ]
            .to_numpy(
                dtype=float
            )
        )

        signed = (
            pred
            -
            gt
        )


        stratum_rows_2e.append(
            {
                "density_stratum":
                    stratum,

                "system":
                    system_name,

                "MAE":
                    float(
                        np.mean(
                            np.abs(
                                signed
                            )
                        )
                    ),

                "RMSE":
                    float(
                        np.sqrt(
                            np.mean(
                                signed ** 2
                            )
                        )
                    ),

                "mean_signed_error":
                    float(
                        signed.mean()
                    ),
            }
        )


b3_step2e_stratum_df = (
    pd.DataFrame(
        stratum_rows_2e
    )
)


# ------------------------------------------------------------
# 16. Save artifacts
# ------------------------------------------------------------

B3_STEP2E_IMAGE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2E_semantic_geometry_factorial_per_image.csv"
)

B3_STEP2E_OVERALL_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2E_semantic_geometry_factorial_overall.csv"
)

B3_STEP2E_MARGINAL_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2E_semantic_geometry_marginal_effects.csv"
)

B3_STEP2E_HELP_HURT_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2E_semantic_geometry_help_hurt.csv"
)

B3_STEP2E_ACTIVATION_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2E_semantic_geometry_activation_overlap.csv"
)

B3_STEP2E_STRATUM_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2E_semantic_geometry_by_density.csv"
)


b3_step2e_df.to_csv(
    B3_STEP2E_IMAGE_FILE,
    index=False,
)

b3_step2e_overall_df.to_csv(
    B3_STEP2E_OVERALL_FILE,
    index=False,
)

b3_step2e_marginal_df.to_csv(
    B3_STEP2E_MARGINAL_FILE,
    index=False,
)

b3_step2e_help_hurt_df.to_csv(
    B3_STEP2E_HELP_HURT_FILE,
    index=False,
)

b3_step2e_activation_df.to_csv(
    B3_STEP2E_ACTIVATION_FILE,
    index=False,
)

b3_step2e_stratum_df.to_csv(
    B3_STEP2E_STRATUM_FILE,
    index=False,
)


# ------------------------------------------------------------
# 17. Reports
# ------------------------------------------------------------

print("\nFactorial overall comparison")
print("----------------------------")

display(
    b3_step2e_overall_df[
        [
            "system",
            "C1",
            "D",
            "G",
            "total_prediction",
            "MAE",
            "RMSE",
            "mean_signed_error",
            "under_images",
            "exact_images",
            "over_images",
        ]
    ]
)


print("\nMarginal evidence effects")
print("-------------------------")
print("Negative delta = improvement")

display(
    b3_step2e_marginal_df
)


print("\nPer-image help / tie / hurt")
print("---------------------------")

display(
    b3_step2e_help_hurt_df
)


print("\nD / G activation overlap")
print("------------------------")

display(
    b3_step2e_activation_df
)


print("\nMAE by density stratum")
print("----------------------")

display(
    b3_step2e_stratum_df
    .pivot(
        index=
            "density_stratum",

        columns=
            "system",

        values=
            "MAE",
    )
)


# ------------------------------------------------------------
# 18. Protocol report
# ------------------------------------------------------------

print("\nFactorial systems evaluated:")
print("  S   = B0 + C1")
print("  SD  = B0 + C1 + effective D")
print("  SG  = B0 + C1 + adaptive G")
print("  SDG = B0 + C1 + effective D + adaptive G")

print("\nD source                              : frozen B2 effective Step3D contribution")
print("D alpha                               : 0.5 unchanged")
print("D semantic gate                       : C1_added >= 10 unchanged")

print("\nG source                              : frozen G2")
print("G stage-1 gate                        : candidate_area_fraction >= 0.85")
print("G stage-2 threshold                   : 5.0 — inherited from Step 2D")
print("G weighting                           : none")

print("\nNew D tuning                          : NO")
print("New G tuning                          : NO")
print("Density routing                       : NO")
print("GT used in inference                  : NO")

print("\nS raw-C1 checkpoint reproduced        : YES — MAE 72.00")
print("SD frozen B2-S reproduced             : YES — MAE 70.90")
print("SDG Step-2D t5 reproduced             : YES — MAE 61.63")

print("\nNew inference run                     : NO")
print("Test set accessed                     : NO")

print("\nB3 Step 2E: PASS")

========================================================================================================================
B3 STEP 2E — SEMANTIC / GEOMETRY FACTORIAL ABLATION
========================================================================================================================

Factorial overall comparison
----------------------------

,system,C1,D,G,total_prediction,MAE,RMSE,mean_signed_error,under_images,exact_images,over_images
0,B0,False,False,False,2298.0,80.69,270.233880,-77.47,76,4,20
1,S = B0+C1,True,False,False,3513.0,72.00,262.235314,-65.32,52,5,43
2,SD = B0+C1+D,True,True,False,3842.0,70.90,260.272722,-62.03,46,7,47
3,SG = B0+C1+G,True,False,True,4718.0,61.93,246.585219,-53.27,47,5,48
4,SDG = B0+C1+D+G,True,True,True,5047.0,61.63,245.550993,-49.98,40,7,53

Marginal evidence effects
-------------------------
Negative delta = improvement

,comparison,added_evidence,starting_system,ending_system,delta_MAE,delta_RMSE
0,D added without G: S -> SD,D,S,SD,-1.10,-1.962592
1,D added with G: SG -> SDG,D,SG,SDG,-0.30,-1.034226
2,G added without D: S -> SG,G,S,SG,-10.07,-15.650096
3,G added with D: SD -> SDG,G,SD,SDG,-9.27,-14.721730

Per-image help / tie / hurt
---------------------------

,comparison,improves_images,ties_images,worsens_images,mean_abs_error_delta,median_abs_error_delta
0,D without G: S -> SD,20,65,15,-1.10,0.0
1,D with G: SG -> SDG,18,65,17,-0.30,0.0
2,G without D: S -> SG,9,84,7,-10.07,0.0
3,G with D: SD -> SDG,9,84,7,-9.27,0.0

D / G activation overlap
------------------------

,activation_group,num_images,total_D_effective,total_G_effective,mean_GT
0,neither,53,0.0,0.0,99.339623
1,D_only,31,242.5,0.0,67.032258
2,G_only,11,0.0,153.0,45.636364
3,D_and_G,5,86.5,1052.0,440.000000

MAE by density stratum
----------------------

system,B0,S = B0+C1,SD = B0+C1+D,SDG = B0+C1+D+G,SG = B0+C1+G
density_stratum,,,,,
S1_0_20,5.15,4.55,5.575,6.975,5.95
S2_20_40,6.55,5.60,7.950,9.150,6.80
S3_40_60,14.95,8.95,9.950,9.700,8.70
S4_60_80,34.30,24.15,21.225,19.475,22.40
S5_80_95,62.10,44.60,40.550,38.450,40.60
S6_95_100,622.90,588.90,579.050,487.250,491.00

Factorial systems evaluated:
  S   = B0 + C1
  SD  = B0 + C1 + effective D
  SG  = B0 + C1 + adaptive G
  SDG = B0 + C1 + effective D + adaptive G

D source                              : frozen B2 effective Step3D contribution
D alpha                               : 0.5 unchanged
D semantic gate                       : C1_added >= 10 unchanged

G source                              : frozen G2
G stage-1 gate                        : candidate_area_fraction >= 0.85
G stage-2 threshold                   : 5.0 — inherited from Step 2D
G weighting                           : none

New D tuning                          : NO
New G tuning                          : NO
Density routing                       : NO
GT used in inference                  : NO

S raw-C1 checkpoint reproduced        : YES — MAE 72.00
SD frozen B2-S reproduced             : YES — MAE 70.90
SDG Step-2D t5 reproduced             : YES — MAE 61.63

New inference run                     : NO
Test set accessed                     : NO

B3 Step 2E: PASS

### **Finding 18:**

Factorial ablation shows that adaptive geometric refinement contributes substantially more independent counting information than the existing activation-based D recovery branch.

Relative to B0+C1, adaptive geometry reduces MAE by 10.07, whereas D reduces MAE by only 1.10.

When geometry is already present, adding D provides only a further 0.30 MAE improvement, reducing MAE from 61.93 to 61.63.

Geometry therefore remains strongly beneficial irrespective of D, while D becomes largely marginal after geometric refinement.

Post-hoc density analysis nevertheless shows that D remains somewhat beneficial in denser S4–S6 scenes while degrading S1–S3, indicating that its remaining value is regime-dependent rather than uniformly additive.

In [ ]:
# ============================================================
# B3 Step 2F — Architecture Consolidation:
#              SG vs SDG Robustness of the Optional D Branch
# ============================================================
#
# Purpose
# -------
# Major architecture now under consideration:
#
#     B0 + C1 + adaptive geometry
#
# Two architectural variants:
#
#   SG:
#       B0 + C1 + G
#
#   SDG:
#       B0 + C1 + D + G
#
#
# Step 2E showed:
#
#   SG  MAE = 61.93
#   SDG MAE = 61.63
#
# so the remaining question is NOT whether D can improve the
# system at all.
#
# It is:
#
#   Is the small additional benefit from D robust enough to
#   justify retaining D as part of the major architecture?
#
#
# This step therefore examines:
#
#   1. paired image-level error changes;
#   2. total contribution of D after G;
#   3. robustness after removing strongest D-benefit cases;
#   4. paired bootstrap uncertainty for SDG - SG MAE;
#   5. post-hoc density behaviour.
#
#
# IMPORTANT
# ---------
#
# No architecture is permanently frozen here.
#
# SG can remain the simpler major architecture.
# SDG remains an optional architecture variant.
#
#
# No:
#   - new threshold tuning
#   - new D tuning
#   - new geometry tuning
#   - density routing
#   - GT routing
#   - new inference
#   - test access
#
# ============================================================

import numpy as np
import pandas as pd


print("=" * 120)
print("B3 STEP 2F — ARCHITECTURE CONSOLIDATION: SG vs SDG")
print("=" * 120)


# ------------------------------------------------------------
# 1. Guards
# ------------------------------------------------------------

assert "b3_step2e_df" in globals(), (
    "b3_step2e_df unavailable. Run Step 2E first."
)

assert "B3_TABLES_DIR" in globals()

assert len(
    b3_step2e_df
) == 100


required_cols_2f = {
    "dataset_index",
    "image_id",
    "category",
    "density_stratum",
    "gt_count",

    "SG_B0_C1_G_count",
    "SDG_B0_C1_D_G_count",

    "D_effective_contribution",
    "G_effective_contribution",
}


assert required_cols_2f.issubset(
    b3_step2e_df.columns
), (
    "Required Step-2E columns missing.\n"
    f"Missing: {sorted(required_cols_2f - set(b3_step2e_df.columns))}"
)


# ------------------------------------------------------------
# 2. Build paired SG / SDG diagnostic table
# ------------------------------------------------------------

b3_step2f_df = (
    b3_step2e_df[
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "SG_B0_C1_G_count",
            "SDG_B0_C1_D_G_count",

            "D_effective_contribution",
            "G_effective_contribution",
        ]
    ]
    .copy()
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


# ------------------------------------------------------------
# 3. Paired errors
# ------------------------------------------------------------

b3_step2f_df[
    "SG_signed_error"
] = (
    b3_step2f_df[
        "SG_B0_C1_G_count"
    ]
    -
    b3_step2f_df[
        "gt_count"
    ]
)


b3_step2f_df[
    "SDG_signed_error"
] = (
    b3_step2f_df[
        "SDG_B0_C1_D_G_count"
    ]
    -
    b3_step2f_df[
        "gt_count"
    ]
)


b3_step2f_df[
    "SG_abs_error"
] = (
    b3_step2f_df[
        "SG_signed_error"
    ]
    .abs()
)


b3_step2f_df[
    "SDG_abs_error"
] = (
    b3_step2f_df[
        "SDG_signed_error"
    ]
    .abs()
)


# Negative = D improves SG
# Positive = D worsens SG
b3_step2f_df[
    "D_abs_error_delta_on_top_of_G"
] = (
    b3_step2f_df[
        "SDG_abs_error"
    ]
    -
    b3_step2f_df[
        "SG_abs_error"
    ]
)


b3_step2f_df[
    "D_improves_on_top_of_G"
] = (
    b3_step2f_df[
        "D_abs_error_delta_on_top_of_G"
    ]
    <
    0
)


b3_step2f_df[
    "D_worsens_on_top_of_G"
] = (
    b3_step2f_df[
        "D_abs_error_delta_on_top_of_G"
    ]
    >
    0
)


b3_step2f_df[
    "D_active"
] = (
    b3_step2f_df[
        "D_effective_contribution"
    ]
    >
    0
)


# ------------------------------------------------------------
# 4. Overall SG / SDG metrics
# ------------------------------------------------------------

def metrics_2f(
    df,
    pred_col,
    system,
):

    gt = (
        df[
            "gt_count"
        ]
        .to_numpy(
            dtype=float
        )
    )

    pred = (
        df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    err = (
        pred
        -
        gt
    )

    return {
        "system":
            system,

        "MAE":
            float(
                np.mean(
                    np.abs(
                        err
                    )
                )
            ),

        "RMSE":
            float(
                np.sqrt(
                    np.mean(
                        err ** 2
                    )
                )
            ),

        "mean_signed_error":
            float(
                err.mean()
            ),

        "under_images":
            int(
                (
                    err < 0
                )
                .sum()
            ),

        "exact_images":
            int(
                np.isclose(
                    err,
                    0.0,
                )
                .sum()
            ),

        "over_images":
            int(
                (
                    err > 0
                )
                .sum()
            ),
    }


b3_step2f_overall_df = pd.DataFrame(
    [
        metrics_2f(
            b3_step2f_df,
            "SG_B0_C1_G_count",
            "SG = B0+C1+G",
        ),

        metrics_2f(
            b3_step2f_df,
            "SDG_B0_C1_D_G_count",
            "SDG = B0+C1+D+G",
        ),
    ]
)


# ------------------------------------------------------------
# 5. Direct incremental D summary
# ------------------------------------------------------------

delta_2f = (
    b3_step2f_df[
        "D_abs_error_delta_on_top_of_G"
    ]
    .to_numpy(
        dtype=float
    )
)


b3_step2f_D_summary_df = pd.DataFrame(
    [
        {
            "num_images":
                len(
                    b3_step2f_df
                ),

            "D_active_images":
                int(
                    b3_step2f_df[
                        "D_active"
                    ]
                    .sum()
                ),

            "D_improves_images":
                int(
                    (
                        delta_2f < 0
                    )
                    .sum()
                ),

            "D_ties_images":
                int(
                    np.isclose(
                        delta_2f,
                        0.0,
                    )
                    .sum()
                ),

            "D_worsens_images":
                int(
                    (
                        delta_2f > 0
                    )
                    .sum()
                ),

            "total_abs_error_change":
                float(
                    delta_2f.sum()
                ),

            "mean_abs_error_change":
                float(
                    delta_2f.mean()
                ),

            "median_abs_error_change":
                float(
                    np.median(
                        delta_2f
                    )
                ),

            "total_D_effective_count_added":
                float(
                    b3_step2f_df[
                        "D_effective_contribution"
                    ]
                    .sum()
                ),
        }
    ]
)


# ------------------------------------------------------------
# 6. D-active-only behaviour
# ------------------------------------------------------------

d_active_df_2f = (
    b3_step2f_df[
        b3_step2f_df[
            "D_active"
        ]
    ]
    .copy()
)


d_active_delta_2f = (
    d_active_df_2f[
        "D_abs_error_delta_on_top_of_G"
    ]
    .to_numpy(
        dtype=float
    )
)


b3_step2f_D_active_summary_df = pd.DataFrame(
    [
        {
            "D_active_images":
                int(
                    len(
                        d_active_df_2f
                    )
                ),

            "improves":
                int(
                    (
                        d_active_delta_2f < 0
                    )
                    .sum()
                ),

            "ties":
                int(
                    np.isclose(
                        d_active_delta_2f,
                        0.0,
                    )
                    .sum()
                ),

            "worsens":
                int(
                    (
                        d_active_delta_2f > 0
                    )
                    .sum()
                ),

            "mean_abs_error_change":
                float(
                    d_active_delta_2f.mean()
                ),

            "median_abs_error_change":
                float(
                    np.median(
                        d_active_delta_2f
                    )
                ),

            "total_abs_error_change":
                float(
                    d_active_delta_2f.sum()
                ),
        }
    ]
)


# ------------------------------------------------------------
# 7. Robustness to strongest D-benefit images
#
# Rank only images where D improves SG.
# ------------------------------------------------------------

d_benefit_df_2f = (
    b3_step2f_df[
        b3_step2f_df[
            "D_abs_error_delta_on_top_of_G"
        ]
        <
        0
    ]
    .sort_values(
        "D_abs_error_delta_on_top_of_G",
        ascending=True,
    )
    .reset_index(
        drop=True
    )
)


ranked_D_benefit_indices_2f = (
    d_benefit_df_2f[
        "dataset_index"
    ]
    .tolist()
)


robustness_rows_2f = []


for k in [
    0,
    1,
    3,
    5,
    10,
]:

    exclude = set(
        ranked_D_benefit_indices_2f[
            :
            k
        ]
    )


    rdf = (
        b3_step2f_df[
            ~b3_step2f_df[
                "dataset_index"
            ]
            .isin(
                exclude
            )
        ]
    )


    sg_mae = float(
        rdf[
            "SG_abs_error"
        ]
        .mean()
    )


    sdg_mae = float(
        rdf[
            "SDG_abs_error"
        ]
        .mean()
    )


    robustness_rows_2f.append(
        {
            "excluded_top_D_benefit_images":
                k,

            "remaining_images":
                int(
                    len(
                        rdf
                    )
                ),

            "SG_MAE":
                sg_mae,

            "SDG_MAE":
                sdg_mae,

            "delta_MAE_SDG_minus_SG":
                float(
                    sdg_mae
                    -
                    sg_mae
                ),
        }
    )


b3_step2f_robustness_df = (
    pd.DataFrame(
        robustness_rows_2f
    )
)


# ------------------------------------------------------------
# 8. Paired bootstrap uncertainty
#
# Quantity:
#
#   mean(
#       SDG absolute error
#       -
#       SG absolute error
#   )
#
# Negative favours SDG.
#
# Fixed seed => reproducible.
# ------------------------------------------------------------

BOOTSTRAP_SEED_2F = 0
BOOTSTRAP_REPS_2F = 10000


rng_2f = np.random.default_rng(
    BOOTSTRAP_SEED_2F
)


paired_delta_2f = (
    b3_step2f_df[
        "D_abs_error_delta_on_top_of_G"
    ]
    .to_numpy(
        dtype=float
    )
)


n_2f = len(
    paired_delta_2f
)


bootstrap_mean_delta_2f = np.empty(
    BOOTSTRAP_REPS_2F,
    dtype=float,
)


for i in range(
    BOOTSTRAP_REPS_2F
):

    idx = rng_2f.integers(
        0,
        n_2f,
        size=n_2f,
    )

    bootstrap_mean_delta_2f[i] = (
        paired_delta_2f[
            idx
        ]
        .mean()
    )


bootstrap_ci_low_2f = float(
    np.quantile(
        bootstrap_mean_delta_2f,
        0.025,
    )
)


bootstrap_ci_high_2f = float(
    np.quantile(
        bootstrap_mean_delta_2f,
        0.975,
    )
)


bootstrap_prob_sdg_better_2f = float(
    np.mean(
        bootstrap_mean_delta_2f
        <
        0
    )
)


b3_step2f_bootstrap_df = pd.DataFrame(
    [
        {
            "comparison":
                "SDG - SG paired MAE",

            "observed_mean_delta":
                float(
                    paired_delta_2f.mean()
                ),

            "bootstrap_reps":
                BOOTSTRAP_REPS_2F,

            "bootstrap_seed":
                BOOTSTRAP_SEED_2F,

            "CI_2.5pct":
                bootstrap_ci_low_2f,

            "CI_97.5pct":
                bootstrap_ci_high_2f,

            "bootstrap_fraction_delta_lt_0":
                bootstrap_prob_sdg_better_2f,
        }
    ]
)


# ------------------------------------------------------------
# 9. Post-hoc density behaviour
#
# Density is descriptive only.
# ------------------------------------------------------------

STRATUM_ORDER_2F = [
    "S1_0_20",
    "S2_20_40",
    "S3_40_60",
    "S4_60_80",
    "S5_80_95",
    "S6_95_100",
]


density_rows_2f = []


for stratum in (
    STRATUM_ORDER_2F
):

    sdf = (
        b3_step2f_df[
            b3_step2f_df[
                "density_stratum"
            ]
            ==
            stratum
        ]
    )


    sg_mae = float(
        sdf[
            "SG_abs_error"
        ]
        .mean()
    )


    sdg_mae = float(
        sdf[
            "SDG_abs_error"
        ]
        .mean()
    )


    delta = (
        sdf[
            "D_abs_error_delta_on_top_of_G"
        ]
        .to_numpy(
            dtype=float
        )
    )


    density_rows_2f.append(
        {
            "density_stratum":
                stratum,

            "num_images":
                int(
                    len(
                        sdf
                    )
                ),

            "D_active_images":
                int(
                    sdf[
                        "D_active"
                    ]
                    .sum()
                ),

            "SG_MAE":
                sg_mae,

            "SDG_MAE":
                sdg_mae,

            "delta_MAE_SDG_minus_SG":
                float(
                    sdg_mae
                    -
                    sg_mae
                ),

            "D_improves":
                int(
                    (
                        delta < 0
                    )
                    .sum()
                ),

            "D_ties":
                int(
                    np.isclose(
                        delta,
                        0.0,
                    )
                    .sum()
                ),

            "D_worsens":
                int(
                    (
                        delta > 0
                    )
                    .sum()
                ),
        }
    )


b3_step2f_density_df = (
    pd.DataFrame(
        density_rows_2f
    )
)


# ------------------------------------------------------------
# 10. Largest D benefits / harms after geometry
# ------------------------------------------------------------

largest_D_benefits_2f_df = (
    b3_step2f_df
    .sort_values(
        "D_abs_error_delta_on_top_of_G",
        ascending=True,
    )
    [
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "SG_B0_C1_G_count",
            "SDG_B0_C1_D_G_count",

            "D_effective_contribution",
            "G_effective_contribution",

            "SG_abs_error",
            "SDG_abs_error",

            "D_abs_error_delta_on_top_of_G",
        ]
    ]
    .head(
        15
    )
)


largest_D_harms_2f_df = (
    b3_step2f_df
    .sort_values(
        "D_abs_error_delta_on_top_of_G",
        ascending=False,
    )
    [
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "SG_B0_C1_G_count",
            "SDG_B0_C1_D_G_count",

            "D_effective_contribution",
            "G_effective_contribution",

            "SG_abs_error",
            "SDG_abs_error",

            "D_abs_error_delta_on_top_of_G",
        ]
    ]
    .head(
        15
    )
)


# ------------------------------------------------------------
# 11. Save artifacts
# ------------------------------------------------------------

B3_STEP2F_IMAGE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2F_SG_vs_SDG_per_image.csv"
)

B3_STEP2F_OVERALL_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2F_SG_vs_SDG_overall.csv"
)

B3_STEP2F_D_SUMMARY_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2F_D_increment_summary.csv"
)

B3_STEP2F_D_ACTIVE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2F_D_active_summary.csv"
)

B3_STEP2F_ROBUSTNESS_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2F_SG_vs_SDG_robustness.csv"
)

B3_STEP2F_BOOTSTRAP_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2F_SG_vs_SDG_bootstrap.csv"
)

B3_STEP2F_DENSITY_FILE = (
    B3_TABLES_DIR
    /
    "B3_step2F_SG_vs_SDG_by_density.csv"
)


b3_step2f_df.to_csv(
    B3_STEP2F_IMAGE_FILE,
    index=False,
)

b3_step2f_overall_df.to_csv(
    B3_STEP2F_OVERALL_FILE,
    index=False,
)

b3_step2f_D_summary_df.to_csv(
    B3_STEP2F_D_SUMMARY_FILE,
    index=False,
)

b3_step2f_D_active_summary_df.to_csv(
    B3_STEP2F_D_ACTIVE_FILE,
    index=False,
)

b3_step2f_robustness_df.to_csv(
    B3_STEP2F_ROBUSTNESS_FILE,
    index=False,
)

b3_step2f_bootstrap_df.to_csv(
    B3_STEP2F_BOOTSTRAP_FILE,
    index=False,
)

b3_step2f_density_df.to_csv(
    B3_STEP2F_DENSITY_FILE,
    index=False,
)


# ------------------------------------------------------------
# 12. Reports
# ------------------------------------------------------------

print("\nSG vs SDG overall")
print("-----------------")

display(
    b3_step2f_overall_df
)


print("\nIncremental D contribution after adaptive geometry")
print("--------------------------------------------------")

display(
    b3_step2f_D_summary_df
)


print("\nD-active images only")
print("--------------------")

display(
    b3_step2f_D_active_summary_df
)


print("\nLeave-top-D-benefit robustness")
print("------------------------------")

display(
    b3_step2f_robustness_df
)


print("\nPaired bootstrap: SDG MAE - SG MAE")
print("----------------------------------")
print("Negative favours SDG")

display(
    b3_step2f_bootstrap_df
)


print("\nPost-hoc density comparison")
print("---------------------------")

display(
    b3_step2f_density_df
)


print("\nLargest D benefits after geometry")
print("---------------------------------")

display(
    largest_D_benefits_2f_df
)


print("\nLargest D harms after geometry")
print("------------------------------")

display(
    largest_D_harms_2f_df
)


# ------------------------------------------------------------
# 13. Protocol report
# ------------------------------------------------------------

print("\nMajor architecture being consolidated:")
print("  B0 -> C1 recovery -> adaptive geometry")

print("\nPrimary simple variant:")
print("  SG  = B0 + C1 + adaptive G")

print("\nOptional D-enhanced variant:")
print("  SDG = B0 + C1 + D + adaptive G")

print("\nD retuned                             : NO")
print("Geometry retuned                      : NO")
print("New architectural component added     : NO")

print("\nBootstrap paired by image              : YES")
print("Bootstrap seed                         : 0")
print("Bootstrap repetitions                  : 10000")

print("\nDensity used for routing               : NO")
print("GT used for inference                  : NO")

print("\nFinal D inclusion decision frozen      : NO")
print("Major B0+C1+adaptive-G design fixed    : PROVISIONAL")
print("Test set accessed                      : NO")

print("\nB3 Step 2F: PASS")

========================================================================================================================
B3 STEP 2F — ARCHITECTURE CONSOLIDATION: SG vs SDG
========================================================================================================================

SG vs SDG overall
-----------------

,system,MAE,RMSE,mean_signed_error,under_images,exact_images,over_images
0,SG = B0+C1+G,61.93,246.585219,-53.27,47,5,48
1,SDG = B0+C1+D+G,61.63,245.550993,-49.98,40,7,53

Incremental D contribution after adaptive geometry
--------------------------------------------------

,num_images,D_active_images,D_improves_images,D_ties_images,D_worsens_images,total_abs_error_change,mean_abs_error_change,median_abs_error_change,total_D_effective_count_added
0,100,36,18,65,17,-30.0,-0.3,0.0,329.0

D-active images only
--------------------

,D_active_images,improves,ties,worsens,mean_abs_error_change,median_abs_error_change,total_abs_error_change
0,36,18,1,17,-0.833333,-1.0,-30.0

Leave-top-D-benefit robustness
------------------------------

,excluded_top_D_benefit_images,remaining_images,SG_MAE,SDG_MAE,delta_MAE_SDG_minus_SG
0,0,100,61.930000,61.630000,-0.300000
1,1,99,61.333333,61.262626,-0.070707
2,3,97,56.505155,56.788660,0.283505
3,5,95,50.568421,51.136842,0.568421
4,10,90,49.233333,50.350000,1.116667

Paired bootstrap: SDG MAE - SG MAE
----------------------------------
Negative favours SDG

,comparison,observed_mean_delta,bootstrap_reps,bootstrap_seed,CI_2.5pct,CI_97.5pct,bootstrap_fraction_delta_lt_0
0,SDG - SG paired MAE,-0.3,10000,0,-1.515,0.975,0.6823

Post-hoc density comparison
---------------------------

,density_stratum,num_images,D_active_images,SG_MAE,SDG_MAE,delta_MAE_SDG_minus_SG,D_improves,D_ties,D_worsens
0,S1_0_20,20,2,5.95,6.975,1.025,0,18,2
1,S2_20_40,20,8,6.80,9.150,2.350,1,12,7
2,S3_40_60,20,8,8.70,9.700,1.000,2,12,6
3,S4_60_80,20,8,22.40,19.475,-2.925,7,13,0
4,S5_80_95,10,5,40.60,38.450,-2.150,4,5,1
5,S6_95_100,10,5,491.00,487.250,-3.750,4,5,1

Largest D benefits after geometry
---------------------------------

,dataset_index,image_id,category,density_stratum,gt_count,SG_B0_C1_G_count,SDG_B0_C1_D_G_count,D_effective_contribution,G_effective_contribution,SG_abs_error,SDG_abs_error,D_abs_error_delta_on_top_of_G
92,1187,6931.jpg,birds,S6_95_100,355,234.0,257.0,23.0,135.0,121.0,98.0,-23.0
25,184,840.jpg,books,S6_95_100,637,61.0,81.5,20.5,0.0,576.0,555.5,-20.5
28,227,933.jpg,birds,S4_60_80,67,52.0,66.0,14.0,0.0,15.0,1.0,-14.0
93,1192,6969.jpg,birds,S6_95_100,949,289.0,302.5,13.5,236.0,660.0,646.5,-13.5
2,20,228.jpg,grapes,S4_60_80,44,27.0,40.0,13.0,0.0,17.0,4.0,-13.0
34,298,1935.jpg,bottle caps,S5_80_95,175,71.0,83.5,12.5,0.0,104.0,91.5,-12.5
77,938,5866.jpg,grapes,S6_95_100,267,65.0,76.0,11.0,0.0,202.0,191.0,-11.0
15,143,764.jpg,birds,S5_80_95,85,50.0,58.5,8.5,0.0,35.0,26.5,-8.5
94,1198,7418.jpg,birds,S4_60_80,39,25.0,32.5,7.5,0.0,14.0,6.5,-7.5
99,1269,7060.jpg,pills,S4_60_80,65,47.0,54.0,7.0,22.0,18.0,11.0,-7.0
66,683,4705.jpg,seagulls,S4_60_80,47,37.0,43.5,6.5,0.0,10.0,3.5,-6.5
43,396,2846.jpg,chairs,S4_60_80,38,30.0,40.0,10.0,0.0,8.0,2.0,-6.0
62,618,4544.jpg,flamingos,S3_40_60,33,28.0,33.0,5.0,0.0,5.0,0.0,-5.0
79,999,6061.jpg,seagulls,S5_80_95,104,81.0,86.0,5.0,0.0,23.0,18.0,-5.0
40,365,2316.jpg,camels,S4_60_80,58,28.0,32.5,4.5,0.0,30.0,25.5,-4.5

Largest D harms after geometry
------------------------------

,dataset_index,image_id,category,density_stratum,gt_count,SG_B0_C1_G_count,SDG_B0_C1_D_G_count,D_effective_contribution,G_effective_contribution,SG_abs_error,SDG_abs_error,D_abs_error_delta_on_top_of_G
32,253,975.jpg,birds,S6_95_100,718,726.0,756.5,30.5,619.0,8.0,38.5,30.5
16,148,769.jpg,books,S2_20_40,13,31.0,44.5,13.5,0.0,18.0,31.5,13.5
44,417,2873.jpg,chairs,S1_0_20,11,20.0,30.5,10.5,0.0,9.0,19.5,10.5
90,1169,7421.jpg,horses,S1_0_20,10,25.0,35.0,10.0,0.0,15.0,25.0,10.0
37,331,1976.jpg,bottle caps,S3_40_60,32,34.0,42.5,8.5,0.0,2.0,10.5,8.5
70,855,5112.jpg,chicken wings,S3_40_60,22,32.0,40.0,8.0,0.0,10.0,18.0,8.0
74,908,5667.jpg,donuts tray,S2_20_40,20,34.0,42.0,8.0,0.0,14.0,22.0,8.0
6,52,559.jpg,flamingos,S2_20_40,20,21.0,28.0,7.0,0.0,1.0,8.0,7.0
87,1149,6794.jpg,shirts,S3_40_60,27,26.0,34.5,8.5,0.0,1.0,7.5,6.5
58,564,3777.jpg,donuts tray,S2_20_40,14,20.0,26.5,6.5,0.0,6.0,12.5,6.5
24,183,838.jpg,books,S5_80_95,113,110.0,122.5,12.5,40.0,3.0,9.5,6.5
95,1219,7006.jpg,pills,S2_20_40,15,23.0,29.0,6.0,0.0,8.0,14.0,6.0
67,822,5078.jpg,chicken wings,S2_20_40,20,24.0,29.5,5.5,0.0,4.0,9.5,5.5
10,101,611.jpg,seagulls,S2_20_40,14,22.0,25.5,3.5,0.0,8.0,11.5,3.5
48,488,3543.jpg,chicken wings,S3_40_60,30,40.0,42.0,2.0,0.0,10.0,12.0,2.0

Major architecture being consolidated:
  B0 -> C1 recovery -> adaptive geometry

Primary simple variant:
  SG  = B0 + C1 + adaptive G

Optional D-enhanced variant:
  SDG = B0 + C1 + D + adaptive G

D retuned                             : NO
Geometry retuned                      : NO
New architectural component added     : NO

Bootstrap paired by image              : YES
Bootstrap seed                         : 0
Bootstrap repetitions                  : 10000

Density used for routing               : NO
GT used for inference                  : NO

Final D inclusion decision frozen      : NO
Major B0+C1+adaptive-G design fixed    : PROVISIONAL
Test set accessed                      : NO

B3 Step 2F: PASS

### **Finding 19:**

After adaptive geometry is introduced, the residual contribution of the activation-based D branch is small and statistically uncertain.

SDG improves MAE over SG by only 0.30, the paired bootstrap interval spans zero, and the advantage disappears when a few strongest D-benefit cases are removed.

D therefore remains a plausible optional architecture variant, particularly for denser scenes, but is not required to define the provisional major architecture.

The primary architecture is consequently treated as B0-anchored C1 semantic recovery with adaptive geometric refinement, while D is deferred to later variant evaluation.

# **Step 3 — Major Architecture Evaluation and Refinement**

 From Step 2, we chose SG as the provisional major architecture, and keep SDG as the optional variant for later evaluation.

 SG = B0 + C1 + adaptive geometry G

 and,

 SDG = B0 + C1 + D + adaptive geometry G

In [ ]:
# ============================================================
# B3 Step 3A — Freeze and Audit the Provisional SG Architecture
# ============================================================
#
# Purpose
# -------
# Formally define ONE canonical provisional SG reference for
# all subsequent Step-3 architecture evaluation/refinement.
#
#
# Primary provisional architecture:
#
#     SG = B0 + C1 + adaptive geometry G
#
#
# Optional later variant:
#
#     SDG = B0 + C1 + D + adaptive geometry G
#
#
# Step 3A performs NO new experiment.
#
# It:
#   1. records the exact SG configuration;
#   2. records where each choice came from;
#   3. distinguishes structural choices from development-selected
#      thresholds;
#   4. verifies that the frozen SG reference reproduces MAE 61.93;
#   5. saves a machine-readable manifest for later experiments.
#
#
# No:
#   - threshold search
#   - architecture change
#   - new inference
#   - test-set access
#
# ============================================================

import json
from pathlib import Path

import numpy as np
import pandas as pd


print("=" * 120)
print("B3 STEP 3A — FREEZE AND AUDIT THE PROVISIONAL SG ARCHITECTURE")
print("=" * 120)


# ------------------------------------------------------------
# 1. Guards
# ------------------------------------------------------------

assert "b3_step2e_df" in globals(), (
    "b3_step2e_df unavailable. Run Step 2E first."
)

assert "b3_step2f_overall_df" in globals(), (
    "b3_step2f_overall_df unavailable. Run Step 2F first."
)

assert "B3_METADATA_DIR" in globals()
assert "B3_TABLES_DIR" in globals()

assert len(
    b3_step2e_df
) == 100


# ------------------------------------------------------------
# 2. Verify frozen SG reference
# ------------------------------------------------------------

gt_3a = (
    b3_step2e_df[
        "gt_count"
    ]
    .to_numpy(
        dtype=float
    )
)


sg_pred_3a = (
    b3_step2e_df[
        "SG_B0_C1_G_count"
    ]
    .to_numpy(
        dtype=float
    )
)


sg_signed_3a = (
    sg_pred_3a
    -
    gt_3a
)


SG_REFERENCE_METRICS_3A = {
    "num_images":
        int(
            len(
                gt_3a
            )
        ),

    "total_prediction":
        float(
            sg_pred_3a.sum()
        ),

    "mean_prediction":
        float(
            sg_pred_3a.mean()
        ),

    "MAE":
        float(
            np.mean(
                np.abs(
                    sg_signed_3a
                )
            )
        ),

    "RMSE":
        float(
            np.sqrt(
                np.mean(
                    sg_signed_3a ** 2
                )
            )
        ),

    "mean_signed_error":
        float(
            sg_signed_3a.mean()
        ),

    "under_images":
        int(
            (
                sg_signed_3a < 0
            )
            .sum()
        ),

    "exact_images":
        int(
            np.isclose(
                sg_signed_3a,
                0.0,
            )
            .sum()
        ),

    "over_images":
        int(
            (
                sg_signed_3a > 0
            )
            .sum()
        ),
}


assert np.isclose(
    SG_REFERENCE_METRICS_3A[
        "MAE"
    ],
    61.93,
    atol=1e-8,
), (
    "Frozen SG reference does not reproduce MAE 61.93."
)


# ------------------------------------------------------------
# 3. Canonical provisional SG configuration
# ------------------------------------------------------------

B3_SG_PROVISIONAL_CONFIG = {

    # --------------------------------------------------------
    # Architecture identity
    # --------------------------------------------------------

    "architecture_id":
        "B3_SG_provisional_v1",

    "architecture_name":
        "B0 + C1 + adaptive geometry",

    "architecture_short_name":
        "SG",

    "status":
        "provisional_primary_architecture",

    "optional_variant":
        "SDG = B0 + C1 + D + adaptive geometry",


    # --------------------------------------------------------
    # B0 anchor
    # --------------------------------------------------------

    "B0": {
        "role":
            "unguided SAM2 anchor counter",

        "source":
            "frozen B0 experiment",

        "sam_model":
            "SAM2.1 Hiera-Small",

        "count_definition":
            "number of native AMG masks",

        "extra_post_filter":
            False,

        "status":
            "fixed_anchor",
    },


    # --------------------------------------------------------
    # Semantic recovery
    # --------------------------------------------------------

    "semantic": {
        "branch":
            "C",

        "candidate":
            "C1",

        "representation":
            "A3c connected components",

        "connectivity":
            4,

        "recovery_definition":
            "C1 components outside B0 coverage",

        "component_count_contribution":
            1.0,

        "status":
            "development_selected",

        "selection_stage":
            "B2 semantic recovery experiments",

        "note":
            (
                "C1 is the current semantic representation for the "
                "provisional SG architecture; semantic alternatives "
                "remain eligible for later controlled replacement."
            ),
    },


    # --------------------------------------------------------
    # Geometry source
    # --------------------------------------------------------

    "geometry": {
        "depth_model":
            "prs-eth/marigold-depth-v1-1",

        "depth_type":
            "relative normalized depth",

        "resolution":
            768,

        "inference_steps":
            4,

        "ensemble_size":
            1,

        "geometry_variant":
            "G2",

        "split_method":
            "2-cluster 1-D k-means on Marigold depth within A3c component",

        "kmeans_random_state":
            0,

        "kmeans_n_init":
            10,

        "spatial_reconstruction":
            "4-connected components after depth clustering",

        "status":
            "frozen_upstream_geometry_mechanism",
    },


    # --------------------------------------------------------
    # Geometry eligibility
    # --------------------------------------------------------

    "geometry_candidate_selection": {
        "feature":
            "within-image A3c component area quantile",

        "quantile":
            0.75,

        "interpretation":
            "large-component eligibility only; not proof that split is required",

        "status":
            "development_selected",

        "selection_stage":
            "M1 Step 7A",
    },


    # --------------------------------------------------------
    # G2 fragment retention
    # --------------------------------------------------------

    "geometry_fragment_retention": {
        "variant":
            "G2",

        "satellite_parent_area_fraction_threshold":
            0.001,

        "status":
            "development_selected",

        "selection_stage":
            "M1 Step 7C / 7D",

        "note":
            (
                "Chosen as the conservative retained-fragment configuration "
                "before B3 integration."
            ),
    },


    # --------------------------------------------------------
    # Adaptive geometry gate — Stage 1
    # --------------------------------------------------------

    "adaptive_gate_stage1": {
        "feature":
            "candidate_area_fraction",

        "operator":
            ">=",

        "threshold":
            0.85,

        "status":
            "development_selected",

        "selection_stage":
            "M1 Step 7D",

        "role":
            "image-level semantic/structural eligibility gate",
    },


    # --------------------------------------------------------
    # Adaptive geometry gate — Stage 2
    # --------------------------------------------------------

    "adaptive_gate_stage2": {
        "feature":
            "geometry_extra_per_refinable_component",

        "definition":
            (
                "G2_extra_units_refinable_only / "
                "C1_recovery_geometry_refinable"
            ),

        "operator":
            ">=",

        "threshold":
            5.0,

        "status":
            "development_selected_coarse",

        "selection_stage":
            "B3 Step 2D",

        "tested_values":
            [
                3.0,
                4.0,
                5.0,
            ],

        "note":
            (
                "5.0 was strongest among the predeclared coarse sensitivity "
                "values; no fine-grained search has been performed."
            ),
    },


    # --------------------------------------------------------
    # Geometry correction
    # --------------------------------------------------------

    "geometry_correction": {
        "definition":
            "full retained G2 extra multiplicity",

        "formula":
            "SG = B0 + C1 + G_effective",

        "weight":
            1.0,

        "cap":
            None,

        "status":
            "current_design_choice_not_yet_weight_refined",

        "note":
            (
                "No geometry weighting or cap has yet been selected. "
                "This remains a possible later refinement only if supported "
                "by controlled evidence."
            ),
    },


    # --------------------------------------------------------
    # D branch
    # --------------------------------------------------------

    "D_branch": {
        "included_in_primary_SG":
            False,

        "retained_as_optional_variant":
            True,

        "optional_variant_name":
            "SDG",

        "reason":
            (
                "Step 2F found only a small and statistically uncertain "
                "incremental benefit after adaptive geometry."
            ),

        "status":
            "deferred_optional_variant",
    },


    # --------------------------------------------------------
    # Inference constraints
    # --------------------------------------------------------

    "inference_constraints": {
        "uses_GT_count":
            False,

        "uses_GT_density":
            False,

        "uses_density_stratum":
            False,

        "uses_category_specific_routing":
            False,

        "test_set_accessed":
            False,
    },


    # --------------------------------------------------------
    # Development protocol
    # --------------------------------------------------------

    "development_protocol": {
        "current_subset":
            "FSC-147 validation dev100",

        "num_images":
            100,

        "test_set_reserved":
            True,

        "architecture_status":
            "provisional",

        "warning":
            (
                "Multiple architecture choices were developed on dev100. "
                "Further threshold refinement should therefore be limited "
                "and preferably confirmed on held-out validation data before "
                "final test evaluation."
            ),
    },


    # --------------------------------------------------------
    # Frozen reference metrics
    # --------------------------------------------------------

    "reference_metrics_dev100":
        SG_REFERENCE_METRICS_3A,
}


# ------------------------------------------------------------
# 4. Parameter provenance / audit table
# ------------------------------------------------------------

audit_rows_3a = [

    {
        "component":
            "B0 anchor",

        "parameter":
            "SAM2 unguided AMG anchor",

        "value":
            "SAM2.1 Hiera-Small",

        "choice_type":
            "structural/fixed",

        "origin":
            "B0",

        "needs_step3_recheck":
            False,
    },

    {
        "component":
            "Semantic recovery",

        "parameter":
            "semantic candidate",

        "value":
            "C1",

        "choice_type":
            "development-selected",

        "origin":
            "B2",

        "needs_step3_recheck":
            True,
    },

    {
        "component":
            "Geometry candidate selection",

        "parameter":
            "component area quantile",

        "value":
            0.75,

        "choice_type":
            "development-selected",

        "origin":
            "M1 Step 7A",

        "needs_step3_recheck":
            True,
    },

    {
        "component":
            "Geometry fragment retention",

        "parameter":
            "G2 satellite parent threshold",

        "value":
            0.001,

        "choice_type":
            "development-selected",

        "origin":
            "M1 Step 7C/7D",

        "needs_step3_recheck":
            True,
    },

    {
        "component":
            "Adaptive geometry gate",

        "parameter":
            "Stage-1 candidate_area_fraction",

        "value":
            0.85,

        "choice_type":
            "development-selected",

        "origin":
            "M1 Step 7D",

        "needs_step3_recheck":
            True,
    },

    {
        "component":
            "Adaptive geometry gate",

        "parameter":
            "Stage-2 geometry strength threshold",

        "value":
            5.0,

        "choice_type":
            "development-selected coarse",

        "origin":
            "B3 Step 2D",

        "needs_step3_recheck":
            True,
    },

    {
        "component":
            "Geometry correction",

        "parameter":
            "geometry multiplicity weight",

        "value":
            1.0,

        "choice_type":
            "current untuned design choice",

        "origin":
            "B3 Step 2B",

        "needs_step3_recheck":
            True,
    },

    {
        "component":
            "Geometry correction",

        "parameter":
            "geometry cap",

        "value":
            "None",

        "choice_type":
            "current untuned design choice",

        "origin":
            "B3 Step 2B",

        "needs_step3_recheck":
            True,
    },

    {
        "component":
            "D branch",

        "parameter":
            "included in primary architecture",

        "value":
            False,

        "choice_type":
            "architecture simplification",

        "origin":
            "B3 Step 2E/2F",

        "needs_step3_recheck":
            False,
    },
]


b3_step3a_audit_df = pd.DataFrame(
    audit_rows_3a
)


# ------------------------------------------------------------
# 5. Create compact architecture summary
# ------------------------------------------------------------

b3_step3a_architecture_df = pd.DataFrame(
    [
        {
            "architecture_id":
                B3_SG_PROVISIONAL_CONFIG[
                    "architecture_id"
                ],

            "architecture":
                "SG",

            "formula":
                "B0 + C1 + adaptive G",

            "semantic":
                "C1",

            "geometry_variant":
                "G2",

            "candidate_quantile":
                0.75,

            "G2_satellite_threshold":
                0.001,

            "stage1_feature":
                "candidate_area_fraction",

            "stage1_threshold":
                0.85,

            "stage2_feature":
                "geometry_extra_per_refinable_component",

            "stage2_threshold":
                5.0,

            "geometry_weight":
                1.0,

            "geometry_cap":
                "None",

            "D_included":
                False,

            "dev100_MAE":
                SG_REFERENCE_METRICS_3A[
                    "MAE"
                ],

            "dev100_RMSE":
                SG_REFERENCE_METRICS_3A[
                    "RMSE"
                ],

            "status":
                "PROVISIONAL",
        }
    ]
)


# ------------------------------------------------------------
# 6. Save manifest / audit artifacts
# ------------------------------------------------------------

B3_STEP3A_CONFIG_FILE = (
    B3_METADATA_DIR
    /
    "B3_step3A_provisional_SG_config.json"
)

B3_STEP3A_AUDIT_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3A_SG_parameter_audit.csv"
)

B3_STEP3A_ARCHITECTURE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3A_SG_architecture_summary.csv"
)


with open(
    B3_STEP3A_CONFIG_FILE,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        B3_SG_PROVISIONAL_CONFIG,
        f,
        indent=2,
    )


b3_step3a_audit_df.to_csv(
    B3_STEP3A_AUDIT_FILE,
    index=False,
)


b3_step3a_architecture_df.to_csv(
    B3_STEP3A_ARCHITECTURE_FILE,
    index=False,
)


# ------------------------------------------------------------
# 7. Report
# ------------------------------------------------------------

print("\nProvisional primary architecture")
print("--------------------------------")

display(
    b3_step3a_architecture_df
)


print("\nParameter provenance / audit")
print("----------------------------")

display(
    b3_step3a_audit_df
)


print("\nFrozen SG dev100 reference metrics")
print("----------------------------------")

display(
    pd.DataFrame(
        [
            SG_REFERENCE_METRICS_3A
        ]
    )
)


# ------------------------------------------------------------
# 8. Protocol summary
# ------------------------------------------------------------

print("\nArchitecture identity")
print("---------------------")
print("Primary provisional architecture : SG = B0 + C1 + adaptive G")
print("Optional later variant           : SDG = B0 + C1 + D + adaptive G")


print("\nCurrent SG settings")
print("-------------------")
print("C1 semantic recovery             : YES")
print("Geometry candidate quantile      : 0.75")
print("Geometry variant                 : G2")
print("G2 satellite threshold           : 0.001")
print("Stage-1 gate                     : candidate_area_fraction >= 0.85")
print("Stage-2 gate                     : geometry_extra_per_refinable_component >= 5.0")
print("Geometry weight                  : 1.0")
print("Geometry cap                     : none")
print("D included in primary SG         : NO")


print("\nDevelopment status")
print("------------------")
print("Major architecture shape frozen  : PROVISIONAL")
print("Internal settings fully final     : NO")
print("Step-3 controlled rechecks needed : YES")
print("New inference performed           : NO")
print("Test set accessed                 : NO")


print("\nSaved:")
print(
    " ",
    B3_STEP3A_CONFIG_FILE,
)
print(
    " ",
    B3_STEP3A_AUDIT_FILE,
)
print(
    " ",
    B3_STEP3A_ARCHITECTURE_FILE,
)


print("\nB3 Step 3A: PASS")

========================================================================================================================
B3 STEP 3A — FREEZE AND AUDIT THE PROVISIONAL SG ARCHITECTURE
========================================================================================================================

Provisional primary architecture
--------------------------------

,architecture_id,architecture,formula,semantic,geometry_variant,candidate_quantile,G2_satellite_threshold,stage1_feature,stage1_threshold,stage2_feature,stage2_threshold,geometry_weight,geometry_cap,D_included,dev100_MAE,dev100_RMSE,status
0,B3_SG_provisional_v1,SG,B0 + C1 + adaptive G,C1,G2,0.75,0.001,candidate_area_fraction,0.85,geometry_extra_per_refinable_component,5.0,1.0,None,False,61.93,246.585219,PROVISIONAL

Parameter provenance / audit
----------------------------

,component,parameter,value,choice_type,origin,needs_step3_recheck
0,B0 anchor,SAM2 unguided AMG anchor,SAM2.1 Hiera-Small,structural/fixed,B0,False
1,Semantic recovery,semantic candidate,C1,development-selected,B2,True
2,Geometry candidate selection,component area quantile,0.75,development-selected,M1 Step 7A,True
3,Geometry fragment retention,G2 satellite parent threshold,0.001,development-selected,M1 Step 7C/7D,True
4,Adaptive geometry gate,Stage-1 candidate_area_fraction,0.85,development-selected,M1 Step 7D,True
5,Adaptive geometry gate,Stage-2 geometry strength threshold,5.0,development-selected coarse,B3 Step 2D,True
6,Geometry correction,geometry multiplicity weight,1.0,current untuned design choice,B3 Step 2B,True
7,Geometry correction,geometry cap,None,current untuned design choice,B3 Step 2B,True
8,D branch,included in primary architecture,False,architecture simplification,B3 Step 2E/2F,False

Frozen SG dev100 reference metrics
----------------------------------

,num_images,total_prediction,mean_prediction,MAE,RMSE,mean_signed_error,under_images,exact_images,over_images
0,100,4718.0,47.18,61.93,246.585219,-53.27,47,5,48

Architecture identity
---------------------
Primary provisional architecture : SG = B0 + C1 + adaptive G
Optional later variant           : SDG = B0 + C1 + D + adaptive G

Current SG settings
-------------------
C1 semantic recovery             : YES
Geometry candidate quantile      : 0.75
Geometry variant                 : G2
G2 satellite threshold           : 0.001
Stage-1 gate                     : candidate_area_fraction >= 0.85
Stage-2 gate                     : geometry_extra_per_refinable_component >= 5.0
Geometry weight                  : 1.0
Geometry cap                     : none
D included in primary SG         : NO

Development status
------------------
Major architecture shape frozen  : PROVISIONAL
Internal settings fully final     : NO
Step-3 controlled rechecks needed : YES
New inference performed           : NO
Test set accessed                 : NO

Saved:
  /content/drive/MyDrive/MSc_Project_ZeroShot_Counting/results/B3_B0_B2_M_Geometry_Integration/metadata/B3_step3A_provisional_SG_config.json
  /content/drive/MyDrive/MSc_Project_ZeroShot_Counting/results/B3_B0_B2_M_Geometry_Integration/tables/B3_step3A_SG_parameter_audit.csv
  /content/drive/MyDrive/MSc_Project_ZeroShot_Counting/results/B3_B0_B2_M_Geometry_Integration/tables/B3_step3A_SG_architecture_summary.csv

B3 Step 3A: PASS

In [ ]:
# ============================================================
# B3 Step 3B — Adaptive Geometry Gate-Structure Ablation
# ============================================================
#
# Purpose
# -------
# Test whether the TWO-STAGE geometry gate is structurally
# justified, with all other SG settings frozen.
#
#
# Compare:
#
#   S
#       B0 + C1
#
#   S+G1
#       B0 + C1 + G
#       using Stage 1 only
#
#   S+G2
#       B0 + C1 + G
#       using Stage 2 only
#
#   S+G12
#       B0 + C1 + G
#       using Stage 1 AND Stage 2
#
#
# Frozen SG settings
# ------------------
#
#   semantic = C1
#   geometry variant = G2
#   candidate quantile = 0.75
#   satellite threshold = 0.001
#   Stage-1 threshold = 0.85
#   Stage-2 threshold = 5.0
#   geometry weight = 1.0
#   geometry cap = none
#   D excluded
#
#
# No:
#   - threshold tuning
#   - weight tuning
#   - cap tuning
#   - density routing
#   - GT routing
#   - new inference
#   - test access
#
# ============================================================

import numpy as np
import pandas as pd


print("=" * 120)
print("B3 STEP 3B — ADAPTIVE GEOMETRY GATE-STRUCTURE ABLATION")
print("=" * 120)


# ------------------------------------------------------------
# 1. Guards
# ------------------------------------------------------------

assert "b3_step2e_df" in globals(), (
    "b3_step2e_df unavailable. Run Step 2E first."
)

assert "b3_step2d_df" in globals(), (
    "b3_step2d_df unavailable. Run Step 2D first."
)

assert "B3_TABLES_DIR" in globals()

assert len(
    b3_step2e_df
) == 100

assert len(
    b3_step2d_df
) == 100


# ------------------------------------------------------------
# 2. Frozen thresholds
# ------------------------------------------------------------

STAGE1_THRESHOLD_3B = 0.85
STAGE2_THRESHOLD_3B = 5.0


# ------------------------------------------------------------
# 3. Build aligned Step-3B table
# ------------------------------------------------------------

b3_step3b_df = (
    b3_step2e_df[
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "B0_count",
            "S_B0_C1_count",

            "candidate_area_fraction",
            "C1_recovery_geometry_refinable",
            "G2_extra_units_refinable_only",
            "geometry_extra_per_refinable_component",
        ]
    ]
    .copy()
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


assert len(
    b3_step3b_df
) == 100


# ------------------------------------------------------------
# 4. Define Stage-1 and Stage-2 gates independently
# ------------------------------------------------------------

b3_step3b_df[
    "stage1_ON"
] = (
    b3_step3b_df[
        "candidate_area_fraction"
    ]
    >=
    STAGE1_THRESHOLD_3B
)


b3_step3b_df[
    "stage2_ON"
] = (
    b3_step3b_df[
        "geometry_extra_per_refinable_component"
    ]
    >=
    STAGE2_THRESHOLD_3B
)


b3_step3b_df[
    "stage12_ON"
] = (
    b3_step3b_df[
        "stage1_ON"
    ]
    &
    b3_step3b_df[
        "stage2_ON"
    ]
)


# ------------------------------------------------------------
# 5. Structural gate sanity checks
# ------------------------------------------------------------

assert int(
    b3_step3b_df[
        "stage1_ON"
    ]
    .sum()
) == 57


assert int(
    b3_step3b_df[
        "stage12_ON"
    ]
    .sum()
) == 16


# Reproduce Step-2D t=5 gate exactly
step2d_gate_t5_3b = (
    b3_step2d_df[
        [
            "dataset_index",
            "adaptive_ON_t5.0",
        ]
    ]
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


assert np.array_equal(
    b3_step3b_df[
        "stage12_ON"
    ]
    .to_numpy(
        dtype=bool
    ),

    step2d_gate_t5_3b[
        "adaptive_ON_t5.0"
    ]
    .to_numpy(
        dtype=bool
    ),
), (
    "Stage1+Stage2 gate does not reproduce Step-2D t=5."
)


# ------------------------------------------------------------
# 6. Build geometry contributions
# ------------------------------------------------------------

b3_step3b_df[
    "G_stage1_contribution"
] = np.where(
    b3_step3b_df[
        "stage1_ON"
    ],

    b3_step3b_df[
        "G2_extra_units_refinable_only"
    ],

    0.0,
)


b3_step3b_df[
    "G_stage2_contribution"
] = np.where(
    b3_step3b_df[
        "stage2_ON"
    ],

    b3_step3b_df[
        "G2_extra_units_refinable_only"
    ],

    0.0,
)


b3_step3b_df[
    "G_stage12_contribution"
] = np.where(
    b3_step3b_df[
        "stage12_ON"
    ],

    b3_step3b_df[
        "G2_extra_units_refinable_only"
    ],

    0.0,
)


# ------------------------------------------------------------
# 7. Build ablation predictions
# ------------------------------------------------------------

b3_step3b_df[
    "S_count"
] = (
    b3_step3b_df[
        "S_B0_C1_count"
    ]
)


b3_step3b_df[
    "SG_stage1_count"
] = (
    b3_step3b_df[
        "S_count"
    ]
    +
    b3_step3b_df[
        "G_stage1_contribution"
    ]
)


b3_step3b_df[
    "SG_stage2_count"
] = (
    b3_step3b_df[
        "S_count"
    ]
    +
    b3_step3b_df[
        "G_stage2_contribution"
    ]
)


b3_step3b_df[
    "SG_stage12_count"
] = (
    b3_step3b_df[
        "S_count"
    ]
    +
    b3_step3b_df[
        "G_stage12_contribution"
    ]
)


# ------------------------------------------------------------
# 8. Reproduce provisional SG exactly
# ------------------------------------------------------------

assert np.allclose(
    b3_step3b_df[
        "SG_stage12_count"
    ],

    b3_step2e_df[
        "SG_B0_C1_G_count"
    ],
    rtol=0.0,
    atol=1e-12,
), (
    "Stage1+Stage2 does not reproduce provisional SG."
)


# ------------------------------------------------------------
# 9. Metric helper
# ------------------------------------------------------------

def metrics_3b(
    df,
    pred_col,
    system_name,
):

    gt = (
        df[
            "gt_count"
        ]
        .to_numpy(
            dtype=float
        )
    )

    pred = (
        df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    signed = (
        pred
        -
        gt
    )

    return {
        "system":
            system_name,

        "prediction_column":
            pred_col,

        "num_images":
            int(
                len(
                    df
                )
            ),

        "total_prediction":
            float(
                pred.sum()
            ),

        "MAE":
            float(
                np.mean(
                    np.abs(
                        signed
                    )
                )
            ),

        "RMSE":
            float(
                np.sqrt(
                    np.mean(
                        signed ** 2
                    )
                )
            ),

        "mean_signed_error":
            float(
                signed.mean()
            ),

        "under_images":
            int(
                (
                    signed < 0
                )
                .sum()
            ),

        "exact_images":
            int(
                np.isclose(
                    signed,
                    0.0,
                )
                .sum()
            ),

        "over_images":
            int(
                (
                    signed > 0
                )
                .sum()
            ),
    }


# ------------------------------------------------------------
# 10. Overall comparison
# ------------------------------------------------------------

SYSTEMS_3B = [
    (
        "S = B0+C1",
        "S_count",
    ),

    (
        "SG-Stage1-only",
        "SG_stage1_count",
    ),

    (
        "SG-Stage2-only",
        "SG_stage2_count",
    ),

    (
        "SG-Stage1+Stage2",
        "SG_stage12_count",
    ),
]


overall_rows_3b = []


for system_name, pred_col in (
    SYSTEMS_3B
):

    overall_rows_3b.append(
        metrics_3b(
            b3_step3b_df,
            pred_col,
            system_name,
        )
    )


b3_step3b_overall_df = pd.DataFrame(
    overall_rows_3b
)


# ------------------------------------------------------------
# 11. Deltas vs semantic-only S
# ------------------------------------------------------------

S_MAE_3B = float(
    b3_step3b_overall_df.loc[
        b3_step3b_overall_df[
            "system"
        ]
        ==
        "S = B0+C1",
        "MAE",
    ]
    .iloc[0]
)


S_RMSE_3B = float(
    b3_step3b_overall_df.loc[
        b3_step3b_overall_df[
            "system"
        ]
        ==
        "S = B0+C1",
        "RMSE",
    ]
    .iloc[0]
)


b3_step3b_overall_df[
    "delta_MAE_vs_S"
] = (
    b3_step3b_overall_df[
        "MAE"
    ]
    -
    S_MAE_3B
)


b3_step3b_overall_df[
    "delta_RMSE_vs_S"
] = (
    b3_step3b_overall_df[
        "RMSE"
    ]
    -
    S_RMSE_3B
)


# ------------------------------------------------------------
# 12. Gate activation / contribution summary
# ------------------------------------------------------------

b3_step3b_gate_summary_df = pd.DataFrame(
    [
        {
            "variant":
                "Stage1-only",

            "gate_ON_images":
                int(
                    b3_step3b_df[
                        "stage1_ON"
                    ]
                    .sum()
                ),

            "geometry_extra_units_used":
                float(
                    b3_step3b_df[
                        "G_stage1_contribution"
                    ]
                    .sum()
                ),
        },

        {
            "variant":
                "Stage2-only",

            "gate_ON_images":
                int(
                    b3_step3b_df[
                        "stage2_ON"
                    ]
                    .sum()
                ),

            "geometry_extra_units_used":
                float(
                    b3_step3b_df[
                        "G_stage2_contribution"
                    ]
                    .sum()
                ),
        },

        {
            "variant":
                "Stage1+Stage2",

            "gate_ON_images":
                int(
                    b3_step3b_df[
                        "stage12_ON"
                    ]
                    .sum()
                ),

            "geometry_extra_units_used":
                float(
                    b3_step3b_df[
                        "G_stage12_contribution"
                    ]
                    .sum()
                ),
        },
    ]
)


# ------------------------------------------------------------
# 13. Help / tie / hurt vs semantic-only S
# ------------------------------------------------------------

gt_3b = (
    b3_step3b_df[
        "gt_count"
    ]
    .to_numpy(
        dtype=float
    )
)


S_abs_3b = np.abs(
    b3_step3b_df[
        "S_count"
    ]
    .to_numpy(
        dtype=float
    )
    -
    gt_3b
)


help_hurt_rows_3b = []


for system_name, pred_col in (
    SYSTEMS_3B[
        1:
    ]
):

    pred = (
        b3_step3b_df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    abs_err = np.abs(
        pred
        -
        gt_3b
    )

    delta = (
        abs_err
        -
        S_abs_3b
    )

    b3_step3b_df[
        f"{system_name}_abs_error_delta_vs_S"
    ] = delta


    help_hurt_rows_3b.append(
        {
            "system":
                system_name,

            "improves_images":
                int(
                    (
                        delta < 0
                    )
                    .sum()
                ),

            "ties_images":
                int(
                    np.isclose(
                        delta,
                        0.0,
                    )
                    .sum()
                ),

            "worsens_images":
                int(
                    (
                        delta > 0
                    )
                    .sum()
                ),

            "mean_abs_error_delta":
                float(
                    delta.mean()
                ),

            "median_abs_error_delta":
                float(
                    np.median(
                        delta
                    )
                ),
        }
    )


b3_step3b_help_hurt_df = (
    pd.DataFrame(
        help_hurt_rows_3b
    )
)


# ------------------------------------------------------------
# 14. Density-stratum comparison
#
# POST-HOC ONLY.
# ------------------------------------------------------------

STRATUM_ORDER_3B = [
    "S1_0_20",
    "S2_20_40",
    "S3_40_60",
    "S4_60_80",
    "S5_80_95",
    "S6_95_100",
]


density_rows_3b = []


for stratum in (
    STRATUM_ORDER_3B
):

    sdf = (
        b3_step3b_df[
            b3_step3b_df[
                "density_stratum"
            ]
            ==
            stratum
        ]
    )


    for system_name, pred_col in (
        SYSTEMS_3B
    ):

        gt = (
            sdf[
                "gt_count"
            ]
            .to_numpy(
                dtype=float
            )
        )

        pred = (
            sdf[
                pred_col
            ]
            .to_numpy(
                dtype=float
            )
        )

        signed = (
            pred
            -
            gt
        )


        density_rows_3b.append(
            {
                "density_stratum":
                    stratum,

                "system":
                    system_name,

                "MAE":
                    float(
                        np.mean(
                            np.abs(
                                signed
                            )
                        )
                    ),

                "RMSE":
                    float(
                        np.sqrt(
                            np.mean(
                                signed ** 2
                            )
                        )
                    ),

                "mean_signed_error":
                    float(
                        signed.mean()
                    ),
            }
        )


b3_step3b_density_df = (
    pd.DataFrame(
        density_rows_3b
    )
)


# ------------------------------------------------------------
# 15. Paired bootstrap comparisons
#
# Compare each gated variant against semantic-only S.
# Negative delta = gated variant better.
# ------------------------------------------------------------

BOOTSTRAP_SEED_3B = 0
BOOTSTRAP_REPS_3B = 10000

rng_3b = np.random.default_rng(
    BOOTSTRAP_SEED_3B
)


bootstrap_rows_3b = []


for system_name, pred_col in (
    SYSTEMS_3B[
        1:
    ]
):

    pred = (
        b3_step3b_df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    abs_err = np.abs(
        pred
        -
        gt_3b
    )

    paired_delta = (
        abs_err
        -
        S_abs_3b
    )


    boot_means = np.empty(
        BOOTSTRAP_REPS_3B,
        dtype=float,
    )


    for i in range(
        BOOTSTRAP_REPS_3B
    ):

        idx = rng_3b.integers(
            0,
            len(
                paired_delta
            ),
            size=len(
                paired_delta
            ),
        )

        boot_means[i] = (
            paired_delta[
                idx
            ]
            .mean()
        )


    bootstrap_rows_3b.append(
        {
            "system":
                system_name,

            "observed_mean_delta_MAE_vs_S":
                float(
                    paired_delta.mean()
                ),

            "CI_2.5pct":
                float(
                    np.quantile(
                        boot_means,
                        0.025,
                    )
                ),

            "CI_97.5pct":
                float(
                    np.quantile(
                        boot_means,
                        0.975,
                    )
                ),

            "bootstrap_fraction_delta_lt_0":
                float(
                    np.mean(
                        boot_means < 0
                    )
                ),
        }
    )


b3_step3b_bootstrap_df = (
    pd.DataFrame(
        bootstrap_rows_3b
    )
)


# ------------------------------------------------------------
# 16. Save artifacts
# ------------------------------------------------------------

B3_STEP3B_IMAGE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3B_gate_structure_per_image.csv"
)

B3_STEP3B_OVERALL_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3B_gate_structure_overall.csv"
)

B3_STEP3B_GATE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3B_gate_structure_activation.csv"
)

B3_STEP3B_HELP_HURT_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3B_gate_structure_help_hurt.csv"
)

B3_STEP3B_DENSITY_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3B_gate_structure_by_density.csv"
)

B3_STEP3B_BOOTSTRAP_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3B_gate_structure_bootstrap.csv"
)


b3_step3b_df.to_csv(
    B3_STEP3B_IMAGE_FILE,
    index=False,
)

b3_step3b_overall_df.to_csv(
    B3_STEP3B_OVERALL_FILE,
    index=False,
)

b3_step3b_gate_summary_df.to_csv(
    B3_STEP3B_GATE_FILE,
    index=False,
)

b3_step3b_help_hurt_df.to_csv(
    B3_STEP3B_HELP_HURT_FILE,
    index=False,
)

b3_step3b_density_df.to_csv(
    B3_STEP3B_DENSITY_FILE,
    index=False,
)

b3_step3b_bootstrap_df.to_csv(
    B3_STEP3B_BOOTSTRAP_FILE,
    index=False,
)


# ------------------------------------------------------------
# 17. Reports
# ------------------------------------------------------------

print("\nGate activation summary")
print("-----------------------")

display(
    b3_step3b_gate_summary_df
)


print("\nOverall gate-structure ablation")
print("------------------------------")

display(
    b3_step3b_overall_df[
        [
            "system",
            "total_prediction",
            "MAE",
            "RMSE",
            "mean_signed_error",
            "under_images",
            "exact_images",
            "over_images",
            "delta_MAE_vs_S",
            "delta_RMSE_vs_S",
        ]
    ]
)


print("\nHelp / tie / hurt versus S")
print("--------------------------")

display(
    b3_step3b_help_hurt_df
)


print("\nMAE by density stratum")
print("----------------------")

display(
    b3_step3b_density_df
    .pivot(
        index=
            "density_stratum",

        columns=
            "system",

        values=
            "MAE",
    )
)


print("\nPaired bootstrap versus S")
print("-------------------------")
print("Negative delta favours geometry variant")

display(
    b3_step3b_bootstrap_df
)


# ------------------------------------------------------------
# 18. Protocol report
# ------------------------------------------------------------

print("\nFrozen architecture inputs")
print("--------------------------")
print("Semantic candidate              : C1")
print("Geometry variant                : G2")
print("Candidate quantile              : 0.75")
print("Satellite threshold             : 0.001")
print("Stage-1 threshold               : 0.85")
print("Stage-2 threshold               : 5.0")
print("Geometry weight                 : 1.0")
print("Geometry cap                    : none")
print("D included                      : NO")

print("\nGate structures tested")
print("----------------------")
print("No G                             : YES")
print("Stage 1 only                     : YES")
print("Stage 2 only                     : YES")
print("Stage 1 + Stage 2                : YES")

print("\nThreshold tuning                 : NO")
print("Density routing                  : NO")
print("GT routing                       : NO")
print("New inference                    : NO")
print("Test set accessed                : NO")

print("\nB3 Step 3B: PASS")

========================================================================================================================
B3 STEP 3B — ADAPTIVE GEOMETRY GATE-STRUCTURE ABLATION
========================================================================================================================

Gate activation summary
-----------------------

         variant  gate_ON_images  geometry_extra_units_used
0    Stage1-only              57                     1567.0
1    Stage2-only              16                     1205.0
2  Stage1+Stage2              16                     1205.0

Overall gate-structure ablation
------------------------------

,system,total_prediction,MAE,RMSE,mean_signed_error,under_images,exact_images,over_images,delta_MAE_vs_S,delta_RMSE_vs_S
0,S = B0+C1,3513.0,72.00,262.235314,-65.32,52,5,43,0.00,0.000000
1,SG-Stage1-only,5080.0,63.17,246.008354,-49.65,42,3,55,-8.83,-16.226961
2,SG-Stage2-only,4718.0,61.93,246.585219,-53.27,47,5,48,-10.07,-15.650096
3,SG-Stage1+Stage2,4718.0,61.93,246.585219,-53.27,47,5,48,-10.07,-15.650096

Help / tie / hurt versus S
--------------------------

,system,improves_images,ties_images,worsens_images,mean_abs_error_delta,median_abs_error_delta
0,SG-Stage1-only,17,56,27,-8.83,0.0
1,SG-Stage2-only,9,84,7,-10.07,0.0
2,SG-Stage1+Stage2,9,84,7,-10.07,0.0

MAE by density stratum
----------------------

system           S = B0+C1  SG-Stage1+Stage2  SG-Stage1-only  SG-Stage2-only
density_stratum
S1_0_20               4.55              5.95            8.65            5.95
S2_20_40              5.60              6.80            9.20            6.80
S3_40_60              8.95              8.70           13.20            8.70
S4_60_80             24.15             22.40           21.90           22.40
S5_80_95             44.60             40.60           37.80           40.60
S6_95_100           588.90            491.00          488.00          491.00

Paired bootstrap versus S
-------------------------
Negative delta favours geometry variant

,system,observed_mean_delta_MAE_vs_S,CI_2.5pct,CI_97.5pct,bootstrap_fraction_delta_lt_0
0,SG-Stage1-only,-8.83,-23.73050,0.94025,0.9436
1,SG-Stage2-only,-10.07,-25.40050,-0.32000,0.9867
2,SG-Stage1+Stage2,-10.07,-24.71025,-0.31000,0.9847

Frozen architecture inputs
--------------------------
Semantic candidate              : C1
Geometry variant                : G2
Candidate quantile              : 0.75
Satellite threshold             : 0.001
Stage-1 threshold               : 0.85
Stage-2 threshold               : 5.0
Geometry weight                 : 1.0
Geometry cap                    : none
D included                      : NO

Gate structures tested
----------------------
No G                             : YES
Stage 1 only                     : YES
Stage 2 only                     : YES
Stage 1 + Stage 2                : YES

Threshold tuning                 : NO
Density routing                  : NO
GT routing                       : NO
New inference                    : NO
Test set accessed                : NO

B3 Step 3B: PASS

### **Finding 20:**

Gate-structure ablation shows that the current Stage-1 candidate_area_fraction ≥ 0.85 criterion is redundant once the Stage-2 geometry-strength gate is applied.

Stage2-only and Stage1+Stage2 activate the same 16 images, use the same geometry contribution, and produce identical MAE, RMSE, density-stratum behaviour, and per-image help/hurt results.

The provisional SG architecture can therefore be simplified to C1 semantic recovery followed directly by the Stage-2 geometry-strength gate and G2 multiplicity correction.

In [ ]:
# ============================================================
# B3 Step 3C — Stage-2 Threshold Sensitivity
# ============================================================
#
# Purpose
# -------
# Test whether the simplified SG architecture is robust to a
# small change around the current Stage-2 threshold.
#
#
# Current simplified SG:
#
#     B0 + C1 + adaptive G
#
# with:
#
#     geometry_extra_per_refinable_component >= t
#
#
# Coarse sensitivity values:
#
#     t = 4, 5, 6
#
#
# IMPORTANT
# ---------
#
# This is a robustness/sensitivity check, NOT a fine-grained
# threshold optimisation.
#
# All other SG settings remain frozen:
#
#   semantic = C1
#   geometry = G2
#   candidate quantile = 0.75
#   satellite threshold = 0.001
#   geometry weight = 1.0
#   geometry cap = none
#   D excluded
#   Stage 1 removed
#
#
# No:
#   - Stage-1 gate
#   - threshold sweep beyond {4,5,6}
#   - geometry re-weighting
#   - geometry cap
#   - density routing
#   - GT routing
#   - new inference
#   - test access
#
# ============================================================

import numpy as np
import pandas as pd


print("=" * 120)
print("B3 STEP 3C — STAGE-2 THRESHOLD SENSITIVITY")
print("=" * 120)


# ------------------------------------------------------------
# 1. Guards
# ------------------------------------------------------------

assert "b3_step3b_df" in globals(), (
    "b3_step3b_df unavailable. Run Step 3B first."
)

assert "B3_TABLES_DIR" in globals()

assert len(
    b3_step3b_df
) == 100


required_cols_3c = {
    "dataset_index",
    "image_id",
    "category",
    "density_stratum",
    "gt_count",

    "S_count",

    "G2_extra_units_refinable_only",
    "geometry_extra_per_refinable_component",
}


assert required_cols_3c.issubset(
    b3_step3b_df.columns
), (
    "Required Step-3B columns missing.\n"
    f"Missing: {sorted(required_cols_3c - set(b3_step3b_df.columns))}"
)


# ------------------------------------------------------------
# 2. Freeze sensitivity grid
# ------------------------------------------------------------

STAGE2_THRESHOLDS_3C = [
    4.0,
    5.0,
    6.0,
]


# ------------------------------------------------------------
# 3. Build Step-3C table
# ------------------------------------------------------------

b3_step3c_df = (
    b3_step3b_df[
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "S_count",

            "G2_extra_units_refinable_only",
            "geometry_extra_per_refinable_component",
        ]
    ]
    .copy()
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


assert len(
    b3_step3c_df
) == 100


# ------------------------------------------------------------
# 4. Construct threshold variants
# ------------------------------------------------------------

activation_rows_3c = []


for threshold in (
    STAGE2_THRESHOLDS_3C
):

    gate_col = (
        f"stage2_ON_t{threshold:.1f}"
    )

    contribution_col = (
        f"G_contribution_t{threshold:.1f}"
    )

    pred_col = (
        f"SG_t{threshold:.1f}_count"
    )


    b3_step3c_df[
        gate_col
    ] = (
        b3_step3c_df[
            "geometry_extra_per_refinable_component"
        ]
        >=
        threshold
    )


    b3_step3c_df[
        contribution_col
    ] = np.where(
        b3_step3c_df[
            gate_col
        ],

        b3_step3c_df[
            "G2_extra_units_refinable_only"
        ],

        0.0,
    )


    b3_step3c_df[
        pred_col
    ] = (
        b3_step3c_df[
            "S_count"
        ]
        +
        b3_step3c_df[
            contribution_col
        ]
    )


    activation_rows_3c.append(
        {
            "threshold":
                threshold,

            "gate_ON_images":
                int(
                    b3_step3c_df[
                        gate_col
                    ]
                    .sum()
                ),

            "geometry_extra_units_used":
                float(
                    b3_step3c_df[
                        contribution_col
                    ]
                    .sum()
                ),
        }
    )


b3_step3c_activation_df = (
    pd.DataFrame(
        activation_rows_3c
    )
)


# ------------------------------------------------------------
# 5. Confirm t=5 reproduces provisional SG
# ------------------------------------------------------------

assert np.allclose(
    b3_step3c_df[
        "SG_t5.0_count"
    ],

    b3_step3b_df[
        "SG_stage2_count"
    ],

    rtol=0.0,
    atol=1e-12,
), (
    "Step-3C t=5 does not reproduce Step-3B Stage2-only SG."
)


# ------------------------------------------------------------
# 6. Metric helper
# ------------------------------------------------------------

def metrics_3c(
    df,
    pred_col,
    system_name,
):

    gt = (
        df[
            "gt_count"
        ]
        .to_numpy(
            dtype=float
        )
    )

    pred = (
        df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    signed = (
        pred
        -
        gt
    )

    return {
        "system":
            system_name,

        "prediction_column":
            pred_col,

        "num_images":
            int(
                len(
                    df
                )
            ),

        "total_prediction":
            float(
                pred.sum()
            ),

        "MAE":
            float(
                np.mean(
                    np.abs(
                        signed
                    )
                )
            ),

        "RMSE":
            float(
                np.sqrt(
                    np.mean(
                        signed ** 2
                    )
                )
            ),

        "mean_signed_error":
            float(
                signed.mean()
            ),

        "under_images":
            int(
                (
                    signed < 0
                )
                .sum()
            ),

        "exact_images":
            int(
                np.isclose(
                    signed,
                    0.0,
                )
                .sum()
            ),

        "over_images":
            int(
                (
                    signed > 0
                )
                .sum()
            ),
    }


# ------------------------------------------------------------
# 7. Overall comparison
# ------------------------------------------------------------

SYSTEMS_3C = [
    (
        "S = B0+C1",
        "S_count",
    ),

    (
        "SG-t4",
        "SG_t4.0_count",
    ),

    (
        "SG-t5",
        "SG_t5.0_count",
    ),

    (
        "SG-t6",
        "SG_t6.0_count",
    ),
]


overall_rows_3c = []


for system_name, pred_col in (
    SYSTEMS_3C
):

    overall_rows_3c.append(
        metrics_3c(
            b3_step3c_df,
            pred_col,
            system_name,
        )
    )


b3_step3c_overall_df = (
    pd.DataFrame(
        overall_rows_3c
    )
)


# ------------------------------------------------------------
# 8. Delta vs S
# ------------------------------------------------------------

S_MAE_3C = float(
    b3_step3c_overall_df.loc[
        b3_step3c_overall_df[
            "system"
        ]
        ==
        "S = B0+C1",
        "MAE",
    ]
    .iloc[0]
)


S_RMSE_3C = float(
    b3_step3c_overall_df.loc[
        b3_step3c_overall_df[
            "system"
        ]
        ==
        "S = B0+C1",
        "RMSE",
    ]
    .iloc[0]
)


b3_step3c_overall_df[
    "delta_MAE_vs_S"
] = (
    b3_step3c_overall_df[
        "MAE"
    ]
    -
    S_MAE_3C
)


b3_step3c_overall_df[
    "delta_RMSE_vs_S"
] = (
    b3_step3c_overall_df[
        "RMSE"
    ]
    -
    S_RMSE_3C
)


# ------------------------------------------------------------
# 9. Help / tie / hurt vs S
# ------------------------------------------------------------

gt_3c = (
    b3_step3c_df[
        "gt_count"
    ]
    .to_numpy(
        dtype=float
    )
)


S_abs_3c = np.abs(
    b3_step3c_df[
        "S_count"
    ]
    .to_numpy(
        dtype=float
    )
    -
    gt_3c
)


help_hurt_rows_3c = []


for system_name, pred_col in (
    SYSTEMS_3C[
        1:
    ]
):

    pred = (
        b3_step3c_df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    abs_err = np.abs(
        pred
        -
        gt_3c
    )

    delta = (
        abs_err
        -
        S_abs_3c
    )


    b3_step3c_df[
        f"{system_name}_abs_error_delta_vs_S"
    ] = delta


    help_hurt_rows_3c.append(
        {
            "system":
                system_name,

            "improves_images":
                int(
                    (
                        delta < 0
                    )
                    .sum()
                ),

            "ties_images":
                int(
                    np.isclose(
                        delta,
                        0.0,
                    )
                    .sum()
                ),

            "worsens_images":
                int(
                    (
                        delta > 0
                    )
                    .sum()
                ),

            "mean_abs_error_delta":
                float(
                    delta.mean()
                ),

            "median_abs_error_delta":
                float(
                    np.median(
                        delta
                    )
                ),
        }
    )


b3_step3c_help_hurt_df = (
    pd.DataFrame(
        help_hurt_rows_3c
    )
)


# ------------------------------------------------------------
# 10. Density-stratum diagnostics
#
# POST-HOC ONLY.
# ------------------------------------------------------------

STRATUM_ORDER_3C = [
    "S1_0_20",
    "S2_20_40",
    "S3_40_60",
    "S4_60_80",
    "S5_80_95",
    "S6_95_100",
]


density_rows_3c = []


for stratum in (
    STRATUM_ORDER_3C
):

    sdf = (
        b3_step3c_df[
            b3_step3c_df[
                "density_stratum"
            ]
            ==
            stratum
        ]
    )


    for system_name, pred_col in (
        SYSTEMS_3C
    ):

        gt = (
            sdf[
                "gt_count"
            ]
            .to_numpy(
                dtype=float
            )
        )

        pred = (
            sdf[
                pred_col
            ]
            .to_numpy(
                dtype=float
            )
        )

        signed = (
            pred
            -
            gt
        )


        density_rows_3c.append(
            {
                "density_stratum":
                    stratum,

                "system":
                    system_name,

                "MAE":
                    float(
                        np.mean(
                            np.abs(
                                signed
                            )
                        )
                    ),

                "RMSE":
                    float(
                        np.sqrt(
                            np.mean(
                                signed ** 2
                            )
                        )
                    ),

                "mean_signed_error":
                    float(
                        signed.mean()
                    ),
            }
        )


b3_step3c_density_df = (
    pd.DataFrame(
        density_rows_3c
    )
)


# ------------------------------------------------------------
# 11. Paired bootstrap vs S
#
# Negative delta = geometry variant better.
# ------------------------------------------------------------

BOOTSTRAP_SEED_3C = 0
BOOTSTRAP_REPS_3C = 10000


bootstrap_rows_3c = []


for j, (
    system_name,
    pred_col,
) in enumerate(
    SYSTEMS_3C[
        1:
    ]
):

    pred = (
        b3_step3c_df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    abs_err = np.abs(
        pred
        -
        gt_3c
    )

    paired_delta = (
        abs_err
        -
        S_abs_3c
    )


    # Separate deterministic seed stream per threshold.
    rng = np.random.default_rng(
        BOOTSTRAP_SEED_3C + j
    )


    boot_means = np.empty(
        BOOTSTRAP_REPS_3C,
        dtype=float,
    )


    for i in range(
        BOOTSTRAP_REPS_3C
    ):

        idx = rng.integers(
            0,
            len(
                paired_delta
            ),
            size=len(
                paired_delta
            ),
        )

        boot_means[i] = (
            paired_delta[
                idx
            ]
            .mean()
        )


    bootstrap_rows_3c.append(
        {
            "system":
                system_name,

            "observed_mean_delta_MAE_vs_S":
                float(
                    paired_delta.mean()
                ),

            "CI_2.5pct":
                float(
                    np.quantile(
                        boot_means,
                        0.025,
                    )
                ),

            "CI_97.5pct":
                float(
                    np.quantile(
                        boot_means,
                        0.975,
                    )
                ),

            "bootstrap_fraction_delta_lt_0":
                float(
                    np.mean(
                        boot_means < 0
                    )
                ),
        }
    )


b3_step3c_bootstrap_df = (
    pd.DataFrame(
        bootstrap_rows_3c
    )
)


# ------------------------------------------------------------
# 12. Pairwise differences between t=4,5,6
#
# This directly measures sensitivity around the current value.
# ------------------------------------------------------------

PAIRWISE_3C = [
    (
        "t5 - t4",
        "SG_t4.0_count",
        "SG_t5.0_count",
    ),

    (
        "t6 - t5",
        "SG_t5.0_count",
        "SG_t6.0_count",
    ),
]


pairwise_rows_3c = []


for label, base_col, alt_col in (
    PAIRWISE_3C
):

    base_abs = np.abs(
        b3_step3c_df[
            base_col
        ]
        .to_numpy(
            dtype=float
        )
        -
        gt_3c
    )

    alt_abs = np.abs(
        b3_step3c_df[
            alt_col
        ]
        .to_numpy(
            dtype=float
        )
        -
        gt_3c
    )

    delta = (
        alt_abs
        -
        base_abs
    )


    pairwise_rows_3c.append(
        {
            "comparison":
                label,

            "mean_abs_error_delta":
                float(
                    delta.mean()
                ),

            "improves_images":
                int(
                    (
                        delta < 0
                    )
                    .sum()
                ),

            "ties_images":
                int(
                    np.isclose(
                        delta,
                        0.0,
                    )
                    .sum()
                ),

            "worsens_images":
                int(
                    (
                        delta > 0
                    )
                    .sum()
                ),
        }
    )


b3_step3c_pairwise_df = (
    pd.DataFrame(
        pairwise_rows_3c
    )
)


# ------------------------------------------------------------
# 13. Save artifacts
# ------------------------------------------------------------

B3_STEP3C_IMAGE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3C_stage2_threshold_per_image.csv"
)

B3_STEP3C_OVERALL_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3C_stage2_threshold_overall.csv"
)

B3_STEP3C_ACTIVATION_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3C_stage2_threshold_activation.csv"
)

B3_STEP3C_HELP_HURT_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3C_stage2_threshold_help_hurt.csv"
)

B3_STEP3C_DENSITY_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3C_stage2_threshold_by_density.csv"
)

B3_STEP3C_BOOTSTRAP_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3C_stage2_threshold_bootstrap.csv"
)

B3_STEP3C_PAIRWISE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3C_stage2_threshold_pairwise.csv"
)


b3_step3c_df.to_csv(
    B3_STEP3C_IMAGE_FILE,
    index=False,
)

b3_step3c_overall_df.to_csv(
    B3_STEP3C_OVERALL_FILE,
    index=False,
)

b3_step3c_activation_df.to_csv(
    B3_STEP3C_ACTIVATION_FILE,
    index=False,
)

b3_step3c_help_hurt_df.to_csv(
    B3_STEP3C_HELP_HURT_FILE,
    index=False,
)

b3_step3c_density_df.to_csv(
    B3_STEP3C_DENSITY_FILE,
    index=False,
)

b3_step3c_bootstrap_df.to_csv(
    B3_STEP3C_BOOTSTRAP_FILE,
    index=False,
)

b3_step3c_pairwise_df.to_csv(
    B3_STEP3C_PAIRWISE_FILE,
    index=False,
)


# ------------------------------------------------------------
# 14. Reports
# ------------------------------------------------------------

print("\nThreshold activation summary")
print("----------------------------")

display(
    b3_step3c_activation_df
)


print("\nOverall Stage-2 sensitivity")
print("---------------------------")

display(
    b3_step3c_overall_df[
        [
            "system",
            "total_prediction",
            "MAE",
            "RMSE",
            "mean_signed_error",
            "under_images",
            "exact_images",
            "over_images",
            "delta_MAE_vs_S",
            "delta_RMSE_vs_S",
        ]
    ]
)


print("\nHelp / tie / hurt versus S")
print("--------------------------")

display(
    b3_step3c_help_hurt_df
)


print("\nMAE by density stratum")
print("----------------------")

display(
    b3_step3c_density_df
    .pivot(
        index=
            "density_stratum",

        columns=
            "system",

        values=
            "MAE",
    )
)


print("\nPaired bootstrap versus S")
print("-------------------------")

display(
    b3_step3c_bootstrap_df
)


print("\nPairwise sensitivity around t=5")
print("--------------------------------")

display(
    b3_step3c_pairwise_df
)


# ------------------------------------------------------------
# 15. Protocol report
# ------------------------------------------------------------

print("\nSimplified SG architecture")
print("--------------------------")
print("Semantic candidate             : C1")
print("Geometry variant               : G2")
print("Candidate quantile             : 0.75")
print("Satellite threshold            : 0.001")
print("Stage-1 gate                   : REMOVED")
print("Stage-2 feature                : geometry_extra_per_refinable_component")
print("Thresholds tested              : [4.0, 5.0, 6.0]")
print("Geometry weight                : 1.0")
print("Geometry cap                   : none")
print("D included                     : NO")

print("\nPurpose                         : robustness / sensitivity")
print("Fine-grained optimisation       : NO")
print("Density routing                 : NO")
print("GT routing                      : NO")
print("New inference                   : NO")
print("Test set accessed               : NO")

print("\nB3 Step 3C: PASS")

========================================================================================================================
B3 STEP 3C — STAGE-2 THRESHOLD SENSITIVITY
========================================================================================================================

Threshold activation summary
----------------------------

   threshold  gate_ON_images  geometry_extra_units_used
0        4.0              24                     1375.0
1        5.0              16                     1205.0
2        6.0               9                      961.0

Overall Stage-2 sensitivity
---------------------------

,system,total_prediction,MAE,RMSE,mean_signed_error,under_images,exact_images,over_images,delta_MAE_vs_S,delta_RMSE_vs_S
0,S = B0+C1,3513.0,72.00,262.235314,-65.32,52,5,43,0.00,0.000000
1,SG-t4,4888.0,62.43,246.057453,-51.57,46,5,49,-9.57,-16.177862
2,SG-t5,4718.0,61.93,246.585219,-53.27,47,5,48,-10.07,-15.650096
3,SG-t6,4474.0,63.89,247.704683,-55.71,49,5,46,-8.11,-14.530631

Help / tie / hurt versus S
--------------------------

,system,improves_images,ties_images,worsens_images,mean_abs_error_delta,median_abs_error_delta
0,SG-t4,12,76,12,-9.57,0.0
1,SG-t5,9,84,7,-10.07,0.0
2,SG-t6,4,91,5,-8.11,0.0

MAE by density stratum
----------------------

system           S = B0+C1   SG-t4   SG-t5   SG-t6
density_stratum
S1_0_20               4.55    8.25    5.95    5.95
S2_20_40              5.60    8.20    6.80    6.55
S3_40_60              8.95   10.30    8.70    8.65
S4_60_80             24.15   21.10   22.40   23.50
S5_80_95             44.60   40.60   40.60   44.60
S6_95_100           588.90  488.00  491.00  505.00

Paired bootstrap versus S
-------------------------

,system,observed_mean_delta_MAE_vs_S,CI_2.5pct,CI_97.5pct,bootstrap_fraction_delta_lt_0
0,SG-t4,-9.57,-24.39075,0.07,0.9732
1,SG-t5,-10.07,-25.41025,-0.35,0.9855
2,SG-t6,-8.11,-23.20100,0.59,0.8913

Pairwise sensitivity around t=5
--------------------------------

,comparison,mean_abs_error_delta,improves_images,ties_images,worsens_images
0,t5 - t4,-0.50,5,92,3
1,t6 - t5,1.96,2,93,5

Simplified SG architecture
--------------------------
Semantic candidate             : C1
Geometry variant               : G2
Candidate quantile             : 0.75
Satellite threshold            : 0.001
Stage-1 gate                   : REMOVED
Stage-2 feature                : geometry_extra_per_refinable_component
Thresholds tested              : [4.0, 5.0, 6.0]
Geometry weight                : 1.0
Geometry cap                   : none
D included                     : NO

Purpose                         : robustness / sensitivity
Fine-grained optimisation       : NO
Density routing                 : NO
GT routing                      : NO
New inference                   : NO
Test set accessed               : NO

B3 Step 3C: PASS

### **Finding 21:**

The simplified Stage-2 geometry gate is reasonably stable around the current threshold. \(t=5\) gives the lowest dev100 MAE (61.93), while \(t=4\) produces similar predictions and slightly lower RMSE but higher MAE.

Raising the threshold to \(t=6\) reduces geometry activation from 16 to 9 images and degrades performance, particularly in denser scenes.

The current threshold \(t=5\) is therefore retained as the provisional SG setting without further fine-grained tuning.

In [ ]:
# ============================================================
# B3 Step 3D — Geometry Correction Magnitude
# ============================================================
#
# Purpose
# -------
# Test whether the simplified SG architecture should apply:
#
#     full geometry multiplicity     w_G = 1.0
#
# or:
#
#     conservative half correction  w_G = 0.5
#
#
# Frozen architecture
# -------------------
#
#   semantic = C1
#   geometry = G2
#   candidate quantile = 0.75
#   satellite threshold = 0.001
#   Stage-1 gate = removed
#   Stage-2 threshold = 5.0
#   D = excluded
#
#
# Prediction:
#
#     SG = S + w_G * G_effective
#
#
# IMPORTANT
# ---------
#
# This is a correction-magnitude ablation.
#
# No:
#   - threshold tuning
#   - cap
#   - alternative gate
#   - density routing
#   - GT routing
#   - new inference
#   - test access
#
# ============================================================

import numpy as np
import pandas as pd


print("=" * 120)
print("B3 STEP 3D — GEOMETRY CORRECTION MAGNITUDE")
print("=" * 120)


# ------------------------------------------------------------
# 1. Guards
# ------------------------------------------------------------

assert "b3_step3c_df" in globals(), (
    "b3_step3c_df unavailable. Run Step 3C first."
)

assert "B3_TABLES_DIR" in globals()

assert len(
    b3_step3c_df
) == 100


required_cols_3d = {
    "dataset_index",
    "image_id",
    "category",
    "density_stratum",
    "gt_count",

    "S_count",

    "stage2_ON_t5.0",
    "G_contribution_t5.0",
    "SG_t5.0_count",
}


assert required_cols_3d.issubset(
    b3_step3c_df.columns
), (
    "Required Step-3C columns missing.\n"
    f"Missing: {sorted(required_cols_3d - set(b3_step3c_df.columns))}"
)


# ------------------------------------------------------------
# 2. Frozen correction weights
# ------------------------------------------------------------

GEOMETRY_WEIGHTS_3D = [
    0.5,
    1.0,
]


# ------------------------------------------------------------
# 3. Build Step-3D table
# ------------------------------------------------------------

b3_step3d_df = (
    b3_step3c_df[
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "S_count",

            "stage2_ON_t5.0",
            "G_contribution_t5.0",
        ]
    ]
    .copy()
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


# ------------------------------------------------------------
# 4. Construct weighted SG variants
# ------------------------------------------------------------

for weight in (
    GEOMETRY_WEIGHTS_3D
):

    pred_col = (
        f"SG_w{weight:.2f}_count"
    )

    b3_step3d_df[
        pred_col
    ] = (
        b3_step3d_df[
            "S_count"
        ]
        +
        weight
        *
        b3_step3d_df[
            "G_contribution_t5.0"
        ]
    )


# ------------------------------------------------------------
# 5. Confirm w=1.0 reproduces current provisional SG
# ------------------------------------------------------------

assert np.allclose(
    b3_step3d_df[
        "SG_w1.00_count"
    ],

    b3_step3c_df[
        "SG_t5.0_count"
    ],

    rtol=0.0,
    atol=1e-12,
), (
    "Step-3D w=1.0 does not reproduce Step-3C SG-t5."
)


# ------------------------------------------------------------
# 6. Metric helper
# ------------------------------------------------------------

def metrics_3d(
    df,
    pred_col,
    system_name,
):

    gt = (
        df[
            "gt_count"
        ]
        .to_numpy(
            dtype=float
        )
    )

    pred = (
        df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    signed = (
        pred
        -
        gt
    )

    return {
        "system":
            system_name,

        "num_images":
            int(
                len(
                    df
                )
            ),

        "total_prediction":
            float(
                pred.sum()
            ),

        "MAE":
            float(
                np.mean(
                    np.abs(
                        signed
                    )
                )
            ),

        "RMSE":
            float(
                np.sqrt(
                    np.mean(
                        signed ** 2
                    )
                )
            ),

        "mean_signed_error":
            float(
                signed.mean()
            ),

        "under_images":
            int(
                (
                    signed < 0
                )
                .sum()
            ),

        "exact_images":
            int(
                np.isclose(
                    signed,
                    0.0,
                )
                .sum()
            ),

        "over_images":
            int(
                (
                    signed > 0
                )
                .sum()
            ),
    }


# ------------------------------------------------------------
# 7. Overall comparison
# ------------------------------------------------------------

SYSTEMS_3D = [
    (
        "S = B0+C1",
        "S_count",
    ),

    (
        "SG-w0.5",
        "SG_w0.50_count",
    ),

    (
        "SG-w1.0",
        "SG_w1.00_count",
    ),
]


overall_rows_3d = []


for system_name, pred_col in (
    SYSTEMS_3D
):

    overall_rows_3d.append(
        metrics_3d(
            b3_step3d_df,
            pred_col,
            system_name,
        )
    )


b3_step3d_overall_df = pd.DataFrame(
    overall_rows_3d
)


# ------------------------------------------------------------
# 8. Delta vs semantic-only S
# ------------------------------------------------------------

S_MAE_3D = float(
    b3_step3d_overall_df.loc[
        b3_step3d_overall_df[
            "system"
        ]
        ==
        "S = B0+C1",
        "MAE",
    ]
    .iloc[0]
)


S_RMSE_3D = float(
    b3_step3d_overall_df.loc[
        b3_step3d_overall_df[
            "system"
        ]
        ==
        "S = B0+C1",
        "RMSE",
    ]
    .iloc[0]
)


b3_step3d_overall_df[
    "delta_MAE_vs_S"
] = (
    b3_step3d_overall_df[
        "MAE"
    ]
    -
    S_MAE_3D
)


b3_step3d_overall_df[
    "delta_RMSE_vs_S"
] = (
    b3_step3d_overall_df[
        "RMSE"
    ]
    -
    S_RMSE_3D
)


# ------------------------------------------------------------
# 9. Help / tie / hurt vs S
# ------------------------------------------------------------

gt_3d = (
    b3_step3d_df[
        "gt_count"
    ]
    .to_numpy(
        dtype=float
    )
)


S_abs_3d = np.abs(
    b3_step3d_df[
        "S_count"
    ]
    .to_numpy(
        dtype=float
    )
    -
    gt_3d
)


help_hurt_rows_3d = []


for system_name, pred_col in (
    SYSTEMS_3D[
        1:
    ]
):

    pred = (
        b3_step3d_df[
            pred_col
        ]
        .to_numpy(
            dtype=float
        )
    )

    abs_err = np.abs(
        pred
        -
        gt_3d
    )

    delta = (
        abs_err
        -
        S_abs_3d
    )


    b3_step3d_df[
        f"{system_name}_abs_error_delta_vs_S"
    ] = delta


    help_hurt_rows_3d.append(
        {
            "system":
                system_name,

            "improves_images":
                int(
                    (
                        delta < 0
                    )
                    .sum()
                ),

            "ties_images":
                int(
                    np.isclose(
                        delta,
                        0.0,
                    )
                    .sum()
                ),

            "worsens_images":
                int(
                    (
                        delta > 0
                    )
                    .sum()
                ),

            "mean_abs_error_delta":
                float(
                    delta.mean()
                ),

            "median_abs_error_delta":
                float(
                    np.median(
                        delta
                    )
                ),
        }
    )


b3_step3d_help_hurt_df = pd.DataFrame(
    help_hurt_rows_3d
)


# ------------------------------------------------------------
# 10. Direct w=0.5 vs w=1.0 comparison
#
# Negative = full weight improves over half weight
# Positive = full weight worsens over half weight
# ------------------------------------------------------------

half_abs_3d = np.abs(
    b3_step3d_df[
        "SG_w0.50_count"
    ]
    .to_numpy(
        dtype=float
    )
    -
    gt_3d
)


full_abs_3d = np.abs(
    b3_step3d_df[
        "SG_w1.00_count"
    ]
    .to_numpy(
        dtype=float
    )
    -
    gt_3d
)


full_vs_half_delta_3d = (
    full_abs_3d
    -
    half_abs_3d
)


b3_step3d_pairwise_df = pd.DataFrame(
    [
        {
            "comparison":
                "w1.0 - w0.5",

            "mean_abs_error_delta":
                float(
                    full_vs_half_delta_3d.mean()
                ),

            "improves_images":
                int(
                    (
                        full_vs_half_delta_3d < 0
                    )
                    .sum()
                ),

            "ties_images":
                int(
                    np.isclose(
                        full_vs_half_delta_3d,
                        0.0,
                    )
                    .sum()
                ),

            "worsens_images":
                int(
                    (
                        full_vs_half_delta_3d > 0
                    )
                    .sum()
                ),
        }
    ]
)


# ------------------------------------------------------------
# 11. Density-stratum diagnostics
#
# POST-HOC ONLY.
# ------------------------------------------------------------

STRATUM_ORDER_3D = [
    "S1_0_20",
    "S2_20_40",
    "S3_40_60",
    "S4_60_80",
    "S5_80_95",
    "S6_95_100",
]


density_rows_3d = []


for stratum in (
    STRATUM_ORDER_3D
):

    sdf = (
        b3_step3d_df[
            b3_step3d_df[
                "density_stratum"
            ]
            ==
            stratum
        ]
    )


    for system_name, pred_col in (
        SYSTEMS_3D
    ):

        gt = (
            sdf[
                "gt_count"
            ]
            .to_numpy(
                dtype=float
            )
        )

        pred = (
            sdf[
                pred_col
            ]
            .to_numpy(
                dtype=float
            )
        )

        signed = (
            pred
            -
            gt
        )


        density_rows_3d.append(
            {
                "density_stratum":
                    stratum,

                "system":
                    system_name,

                "MAE":
                    float(
                        np.mean(
                            np.abs(
                                signed
                            )
                        )
                    ),

                "RMSE":
                    float(
                        np.sqrt(
                            np.mean(
                                signed ** 2
                            )
                        )
                    ),

                "mean_signed_error":
                    float(
                        signed.mean()
                    ),
            }
        )


b3_step3d_density_df = pd.DataFrame(
    density_rows_3d
)


# ------------------------------------------------------------
# 12. Paired bootstrap:
#     full weight vs half weight
#
# Negative = full weight better.
# ------------------------------------------------------------

BOOTSTRAP_SEED_3D = 0
BOOTSTRAP_REPS_3D = 10000


rng_3d = np.random.default_rng(
    BOOTSTRAP_SEED_3D
)


boot_means_3d = np.empty(
    BOOTSTRAP_REPS_3D,
    dtype=float,
)


for i in range(
    BOOTSTRAP_REPS_3D
):

    idx = rng_3d.integers(
        0,
        len(
            full_vs_half_delta_3d
        ),
        size=len(
            full_vs_half_delta_3d
        ),
    )

    boot_means_3d[i] = (
        full_vs_half_delta_3d[
            idx
        ]
        .mean()
    )


b3_step3d_bootstrap_df = pd.DataFrame(
    [
        {
            "comparison":
                "w1.0 - w0.5 paired MAE",

            "observed_mean_delta":
                float(
                    full_vs_half_delta_3d.mean()
                ),

            "CI_2.5pct":
                float(
                    np.quantile(
                        boot_means_3d,
                        0.025,
                    )
                ),

            "CI_97.5pct":
                float(
                    np.quantile(
                        boot_means_3d,
                        0.975,
                    )
                ),

            "bootstrap_fraction_delta_lt_0":
                float(
                    np.mean(
                        boot_means_3d < 0
                    )
                ),
        }
    ]
)


# ------------------------------------------------------------
# 13. Inspect largest differences between full and half
# ------------------------------------------------------------

b3_step3d_df[
    "w1_minus_w0.5_abs_error_delta"
] = (
    full_vs_half_delta_3d
)


largest_full_benefits_3d_df = (
    b3_step3d_df
    .sort_values(
        "w1_minus_w0.5_abs_error_delta",
        ascending=True,
    )
    [
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "S_count",
            "G_contribution_t5.0",

            "SG_w0.50_count",
            "SG_w1.00_count",

            "w1_minus_w0.5_abs_error_delta",
        ]
    ]
    .head(
        12
    )
)


largest_full_harms_3d_df = (
    b3_step3d_df
    .sort_values(
        "w1_minus_w0.5_abs_error_delta",
        ascending=False,
    )
    [
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",

            "S_count",
            "G_contribution_t5.0",

            "SG_w0.50_count",
            "SG_w1.00_count",

            "w1_minus_w0.5_abs_error_delta",
        ]
    ]
    .head(
        12
    )
)


# ------------------------------------------------------------
# 14. Save artifacts
# ------------------------------------------------------------

B3_STEP3D_IMAGE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3D_geometry_weight_per_image.csv"
)

B3_STEP3D_OVERALL_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3D_geometry_weight_overall.csv"
)

B3_STEP3D_HELP_HURT_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3D_geometry_weight_help_hurt.csv"
)

B3_STEP3D_PAIRWISE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3D_geometry_weight_pairwise.csv"
)

B3_STEP3D_DENSITY_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3D_geometry_weight_by_density.csv"
)

B3_STEP3D_BOOTSTRAP_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3D_geometry_weight_bootstrap.csv"
)


b3_step3d_df.to_csv(
    B3_STEP3D_IMAGE_FILE,
    index=False,
)

b3_step3d_overall_df.to_csv(
    B3_STEP3D_OVERALL_FILE,
    index=False,
)

b3_step3d_help_hurt_df.to_csv(
    B3_STEP3D_HELP_HURT_FILE,
    index=False,
)

b3_step3d_pairwise_df.to_csv(
    B3_STEP3D_PAIRWISE_FILE,
    index=False,
)

b3_step3d_density_df.to_csv(
    B3_STEP3D_DENSITY_FILE,
    index=False,
)

b3_step3d_bootstrap_df.to_csv(
    B3_STEP3D_BOOTSTRAP_FILE,
    index=False,
)


# ------------------------------------------------------------
# 15. Reports
# ------------------------------------------------------------

print("\nOverall geometry-weight ablation")
print("--------------------------------")

display(
    b3_step3d_overall_df[
        [
            "system",
            "total_prediction",
            "MAE",
            "RMSE",
            "mean_signed_error",
            "under_images",
            "exact_images",
            "over_images",
            "delta_MAE_vs_S",
            "delta_RMSE_vs_S",
        ]
    ]
)


print("\nHelp / tie / hurt versus S")
print("--------------------------")

display(
    b3_step3d_help_hurt_df
)


print("\nDirect full-vs-half comparison")
print("------------------------------")
print("Negative mean delta favours full weight")

display(
    b3_step3d_pairwise_df
)


print("\nMAE by density stratum")
print("----------------------")

display(
    b3_step3d_density_df
    .pivot(
        index=
            "density_stratum",

        columns=
            "system",

        values=
            "MAE",
    )
)


print("\nPaired bootstrap: full weight vs half weight")
print("---------------------------------------------")
print("Negative delta favours full weight")

display(
    b3_step3d_bootstrap_df
)


print("\nLargest benefits from full weight")
print("---------------------------------")

display(
    largest_full_benefits_3d_df
)


print("\nLargest harms from full weight")
print("------------------------------")

display(
    largest_full_harms_3d_df
)


# ------------------------------------------------------------
# 16. Protocol report
# ------------------------------------------------------------

print("\nFrozen architecture")
print("-------------------")
print("Semantic candidate              : C1")
print("Geometry variant                : G2")
print("Candidate quantile              : 0.75")
print("Satellite threshold             : 0.001")
print("Stage-1 gate                    : REMOVED")
print("Stage-2 threshold               : 5.0")
print("Geometry weights tested         : [0.5, 1.0]")
print("Geometry cap                    : none")
print("D included                      : NO")

print("\nPurpose                         : correction-magnitude ablation")
print("Threshold tuning                : NO")
print("Cap tuning                      : NO")
print("Density routing                 : NO")
print("GT routing                      : NO")
print("New inference                   : NO")
print("Test set accessed               : NO")

print("\nB3 Step 3D: PASS")

========================================================================================================================
B3 STEP 3D — GEOMETRY CORRECTION MAGNITUDE
========================================================================================================================

Overall geometry-weight ablation
--------------------------------

,system,total_prediction,MAE,RMSE,mean_signed_error,under_images,exact_images,over_images,delta_MAE_vs_S,delta_RMSE_vs_S
0,S = B0+C1,3513.0,72.000,262.235314,-65.320,52,5,43,0.000,0.000000
1,SG-w0.5,4115.5,66.665,252.252042,-59.295,49,5,46,-5.335,-9.983273
2,SG-w1.0,4718.0,61.930,246.585219,-53.270,47,5,48,-10.070,-15.650096

Help / tie / hurt versus S
--------------------------

,system,improves_images,ties_images,worsens_images,mean_abs_error_delta,median_abs_error_delta
0,SG-w0.5,11,84,5,-5.335,0.0
1,SG-w1.0,9,84,7,-10.070,0.0

Direct full-vs-half comparison
------------------------------
Negative mean delta favours full weight

,comparison,mean_abs_error_delta,improves_images,ties_images,worsens_images
0,w1.0 - w0.5,-4.735,9,84,7

MAE by density stratum
----------------------

system           S = B0+C1  SG-w0.5  SG-w1.0
density_stratum
S1_0_20               4.55    5.150     5.95
S2_20_40              5.60    5.950     6.80
S3_40_60              8.95    8.625     8.70
S4_60_80             24.15   22.725    22.40
S5_80_95             44.60   42.600    40.60
S6_95_100           588.90  539.150   491.00

Paired bootstrap: full weight vs half weight
---------------------------------------------
Negative delta favours full weight

,comparison,observed_mean_delta,CI_2.5pct,CI_97.5pct,bootstrap_fraction_delta_lt_0
0,w1.0 - w0.5 paired MAE,-4.735,-11.985,-0.015,0.9762

Largest benefits from full weight
---------------------------------

,dataset_index,image_id,category,density_stratum,gt_count,S_count,G_contribution_t5.0,SG_w0.50_count,SG_w1.00_count,w1_minus_w0.5_abs_error_delta
32,253,975.jpg,birds,S6_95_100,718,107,619.0,416.5,726.0,-293.5
93,1192,6969.jpg,birds,S6_95_100,949,53,236.0,171.0,289.0,-118.0
92,1187,6931.jpg,birds,S6_95_100,355,99,135.0,166.5,234.0,-67.5
24,183,838.jpg,books,S5_80_95,113,70,40.0,90.0,110.0,-20.0
99,1269,7060.jpg,pills,S4_60_80,65,25,22.0,36.0,47.0,-11.0
83,1061,6286.jpg,pills,S4_60_80,49,5,20.0,15.0,25.0,-10.0
42,394,2840.jpg,chairs,S3_40_60,35,8,6.0,11.0,14.0,-3.0
0,9,215.jpg,grapes,S6_95_100,259,108,5.0,110.5,113.0,-2.5
61,609,4535.jpg,flamingos,S3_40_60,22,9,17.0,17.5,26.0,-0.5
10,101,611.jpg,seagulls,S2_20_40,14,22,0.0,22.0,22.0,0.0
11,112,623.jpg,seagulls,S1_0_20,9,9,0.0,9.0,9.0,0.0
12,114,625.jpg,seagulls,S2_20_40,14,14,0.0,14.0,14.0,0.0

Largest harms from full weight
------------------------------

,dataset_index,image_id,category,density_stratum,gt_count,S_count,G_contribution_t5.0,SG_w0.50_count,SG_w1.00_count,w1_minus_w0.5_abs_error_delta
78,968,5896.jpg,grapes,S4_60_80,55,44,29.0,58.5,73.0,14.5
8,67,575.jpg,flamingos,S1_0_20,12,10,19.0,19.5,29.0,9.5
41,372,2412.jpg,horses,S2_20_40,15,16,19.0,25.5,35.0,9.5
5,49,556.jpg,flamingos,S2_20_40,14,9,15.0,16.5,24.0,7.5
69,845,5101.jpg,chicken wings,S3_40_60,23,30,10.0,35.0,40.0,5.0
19,170,824.jpg,bottle caps,S1_0_20,9,18,7.0,21.5,25.0,3.5
13,119,737.jpg,ants,S1_0_20,9,13,6.0,16.0,19.0,3.0
20,172,826.jpg,bottle caps,S4_60_80,70,73,0.0,73.0,73.0,0.0
7,59,567.jpg,flamingos,S1_0_20,10,8,0.0,8.0,8.0,0.0
3,31,241.jpg,grapes,S3_40_60,35,27,0.0,27.0,27.0,0.0
2,20,228.jpg,grapes,S4_60_80,44,27,0.0,27.0,27.0,0.0
1,14,220.jpg,grapes,S4_60_80,59,52,0.0,52.0,52.0,0.0

Frozen architecture
-------------------
Semantic candidate              : C1
Geometry variant                : G2
Candidate quantile              : 0.75
Satellite threshold             : 0.001
Stage-1 gate                    : REMOVED
Stage-2 threshold               : 5.0
Geometry weights tested         : [0.5, 1.0]
Geometry cap                    : none
D included                      : NO

Purpose                         : correction-magnitude ablation
Threshold tuning                : NO
Cap tuning                      : NO
Density routing                 : NO
GT routing                      : NO
New inference                   : NO
Test set accessed               : NO

B3 Step 3D: PASS

### **Finding 22:**

Full G2 multiplicity is retained as the provisional geometry correction.

A conservative half-weight correction improves over semantic-only recovery but substantially reduces the geometry benefit, particularly for severe dense-scene undercount cases.

Full weighting gives lower overall MAE and RMSE than half weighting, with paired bootstrap evidence favoring the full correction.

Its advantage is nevertheless concentrated in a small number of high-impact images, so robustness should be confirmed on held-out FSC-147 validation data.

In [ ]:
# ============================================================
# B3 Step 3E-A — Semantic Representation Recheck
#                 under Frozen B0 Anchor
# ============================================================
#
# Purpose
# -------
# Re-evaluate the three frozen Group-C semantic representations:
#
#   C1  = A3c 4-connected components
#   C2b = A3c spatial watershed, alpha = 0.010
#   C2c = A3c spatial watershed, alpha = 0.020
#
# in the SAME B0-anchored recovery role.
#
#
# IMPORTANT
# ---------
#
# Geometry is deliberately NOT applied to C2b/C2c here.
#
# Reason:
#   current G2 geometry was defined relative to C1/A3c
#   connected components. C2b/C2c already introduce their own
#   spatial subdivision of those components.
#
# Adding frozen C1-derived G directly to C2b/C2c would therefore
# confound semantic-region choice with two different splitting
# mechanisms.
#
#
# Step 3E-A asks only:
#
#   "Was C1 still the appropriate semantic representation
#    for B0-anchored recovery?"
#
#
# Frozen:
#   - B0 masks/counts
#   - A3c semantic mask
#   - C1/C2b/C2c candidate generation
#   - dev100
#
# No:
#   - new SAN inference
#   - new SAM2 inference
#   - new Marigold inference
#   - geometry tuning
#   - density routing
#   - GT routing
#   - test access
#
# ============================================================

from pathlib import Path
import ast

import numpy as np
import pandas as pd


print("=" * 120)
print("B3 STEP 3E-A — SEMANTIC REPRESENTATION RECHECK")
print("=" * 120)


# ------------------------------------------------------------
# 1. Preconditions / paths
# ------------------------------------------------------------

assert "PROJECT_ROOT" in globals()
assert "B3_TABLES_DIR" in globals()
assert "b3_step3d_df" in globals()

B1_RESULTS_ROOT_3E = (
    PROJECT_ROOT
    / "results"
    / "B1_experiments"
)

B2_ROOT_3E = (
    B1_RESULTS_ROOT_3E
    / "B2_B0_Anchored_Semantic_Validation"
)

C_CANDIDATE_FILE_3E = (
    B1_RESULTS_ROOT_3E
    / "Group_C"
    / "B1_Group_C_E_candidates_per_image.csv"
)

B0_PER_IMAGE_FILE_3E = (
    PROJECT_ROOT
    / "results"
    / "B0_dev100"
    / "B0_dev100_per_image.csv"
)

B0_MASK_INDEX_FILE_3E = (
    B2_ROOT_3E
    / "tables"
    / "B0_mask_cache_index.csv"
)


for path in [
    C_CANDIDATE_FILE_3E,
    B0_PER_IMAGE_FILE_3E,
    B0_MASK_INDEX_FILE_3E,
]:
    assert path.exists(), path


# ------------------------------------------------------------
# 2. Load frozen inputs
# ------------------------------------------------------------

c3e_df = pd.read_csv(
    C_CANDIDATE_FILE_3E
)

b0_3e_df = pd.read_csv(
    B0_PER_IMAGE_FILE_3E
)

b0_cache_3e_df = pd.read_csv(
    B0_MASK_INDEX_FILE_3E
)


CANDIDATES_3E = [
    "C1",
    "C2b",
    "C2c",
]


assert sorted(
    c3e_df[
        "candidate_id"
    ]
    .unique()
    .tolist()
) == sorted(
    CANDIDATES_3E
)


assert len(
    b0_3e_df
) == 100

assert len(
    b0_cache_3e_df
) == 100


# ------------------------------------------------------------
# 3. Parse frozen semantic point lists
# ------------------------------------------------------------

def parse_points_3e(
    value,
):

    if (
        value is None
        or
        (
            isinstance(
                value,
                float,
            )
            and
            np.isnan(
                value
            )
        )
    ):
        return np.empty(
            (0, 2),
            dtype=np.float32,
        )

    if isinstance(
        value,
        str,
    ):

        value = value.strip()

        if (
            value == ""
            or
            value == "[]"
        ):
            return np.empty(
                (0, 2),
                dtype=np.float32,
            )

        try:
            value = ast.literal_eval(
                value
            )

        except Exception:

            import json

            value = json.loads(
                value
            )

    arr = np.asarray(
        value,
        dtype=np.float32,
    )

    if arr.size == 0:

        return np.empty(
            (0, 2),
            dtype=np.float32,
        )

    return arr.reshape(
        -1,
        2,
    )


# ------------------------------------------------------------
# 4. Decode frozen B0 mask cache
# ------------------------------------------------------------

def load_b0_masks_3e(
    cache_path,
):

    with np.load(
        cache_path,
        allow_pickle=False,
    ) as data:

        packed_masks = data[
            "packed_masks"
        ]

        h = int(
            data[
                "image_height"
            ]
        )

        w = int(
            data[
                "image_width"
            ]
        )

        n = int(
            data[
                "num_masks"
            ]
        )


        num_pixels = (
            h
            *
            w
        )


        if n > 0:

            masks = (
                np.unpackbits(
                    packed_masks,
                    axis=1,
                    bitorder="little",
                )[
                    :,
                    :num_pixels
                ]
                .reshape(
                    n,
                    h,
                    w,
                )
                .astype(
                    bool
                )
            )

        else:

            masks = np.empty(
                (
                    0,
                    h,
                    w,
                ),
                dtype=bool,
            )


    return {
        "masks":
            masks,

        "height":
            h,

        "width":
            w,

        "num_masks":
            n,
    }


# ------------------------------------------------------------
# 5. Build B0/cache lookups
# ------------------------------------------------------------

B0_KEY_COLS_3E = [
    "dataset_index",
    "image_id",
    "category",
    "density_stratum",
    "gt_count",
]


b0_lookup_3e = (
    b0_3e_df
    .set_index(
        "dataset_index"
    )
)


cache_lookup_3e = (
    b0_cache_3e_df
    .set_index(
        "dataset_index"
    )[
        "cache_file"
    ]
    .to_dict()
)


assert b0_lookup_3e.index.is_unique
assert len(
    cache_lookup_3e
) == 100


# ------------------------------------------------------------
# 6. Classify every C point as:
#
#      covered by B0
#      OR
#      recovery candidate
#
# Uses the same point->pixel convention as B2:
#
#      np.rint + clip
# ------------------------------------------------------------

point_rows_3e = []
image_rows_3e = []


for dataset_index in sorted(
    b0_3e_df[
        "dataset_index"
    ]
    .astype(
        int
    )
    .tolist()
):

    b0_row = b0_lookup_3e.loc[
        dataset_index
    ]


    cache = load_b0_masks_3e(
        cache_lookup_3e[
            dataset_index
        ]
    )


    masks = cache[
        "masks"
    ]

    h = cache[
        "height"
    ]

    w = cache[
        "width"
    ]


    b0_count = int(
        b0_row[
            "pred_count"
        ]
    )


    assert (
        b0_count
        ==
        cache[
            "num_masks"
        ]
    )


    for candidate_id in (
        CANDIDATES_3E
    ):

        rows = (
            c3e_df[
                (
                    c3e_df[
                        "dataset_index"
                    ]
                    ==
                    dataset_index
                )
                &
                (
                    c3e_df[
                        "candidate_id"
                    ]
                    ==
                    candidate_id
                )
            ]
        )


        assert len(
            rows
        ) == 1


        row = rows.iloc[
            0
        ]


        points_xy = parse_points_3e(
            row[
                "pred_points_xy"
            ]
        )


        assert len(
            points_xy
        ) == int(
            row[
                "pred_count"
            ]
        )


        covered_count = 0
        recovery_count = 0


        for point_index, (
            x,
            y,
        ) in enumerate(
            points_xy
        ):

            px = int(
                np.clip(
                    np.rint(
                        x
                    ),
                    0,
                    w - 1,
                )
            )

            py = int(
                np.clip(
                    np.rint(
                        y
                    ),
                    0,
                    h - 1,
                )
            )


            if len(
                masks
            ) > 0:

                inside = bool(
                    masks[
                        :,
                        py,
                        px,
                    ]
                    .any()
                )

            else:

                inside = False


            recovery_candidate = (
                not inside
            )


            covered_count += int(
                inside
            )

            recovery_count += int(
                recovery_candidate
            )


            point_rows_3e.append(
                {
                    "dataset_index":
                        int(
                            dataset_index
                        ),

                    "image_id":
                        row[
                            "image_id"
                        ],

                    "category":
                        row[
                            "category"
                        ],

                    "density_stratum":
                        row[
                            "density_stratum"
                        ],

                    "gt_count":
                        int(
                            row[
                                "gt_count"
                            ]
                        ),

                    "candidate_id":
                        candidate_id,

                    "point_index":
                        int(
                            point_index
                        ),

                    "x":
                        float(
                            x
                        ),

                    "y":
                        float(
                            y
                        ),

                    "covered_by_B0":
                        bool(
                            inside
                        ),

                    "recovery_candidate":
                        bool(
                            recovery_candidate
                        ),
                }
            )


        semantic_recovery_pred = (
            b0_count
            +
            recovery_count
        )


        image_rows_3e.append(
            {
                "dataset_index":
                    int(
                        dataset_index
                    ),

                "image_id":
                    row[
                        "image_id"
                    ],

                "category":
                    row[
                        "category"
                    ],

                "density_stratum":
                    row[
                        "density_stratum"
                    ],

                "gt_count":
                    int(
                        row[
                            "gt_count"
                    ]
                ),

                "candidate_id":
                    candidate_id,

                "B0_count":
                    b0_count,

                "semantic_candidate_count":
                    int(
                        len(
                            points_xy
                        )
                    ),

                "semantic_points_covered_by_B0":
                    int(
                        covered_count
                    ),

                "semantic_recovery_count":
                    int(
                        recovery_count
                    ),

                "B0_plus_semantic_count":
                    float(
                        semantic_recovery_pred
                    ),
            }
        )


b3_step3e_point_df = pd.DataFrame(
    point_rows_3e
)


b3_step3e_df = pd.DataFrame(
    image_rows_3e
)


# ------------------------------------------------------------
# 7. Integrity checks
# ------------------------------------------------------------

assert len(
    b3_step3e_df
) == 300


assert (
    b3_step3e_df
    .groupby(
        "candidate_id"
    )[
        "dataset_index"
    ]
    .nunique()
    .eq(
        100
    )
    .all()
)


assert (
    b3_step3e_df[
        "semantic_candidate_count"
    ]
    ==
    (
        b3_step3e_df[
            "semantic_points_covered_by_B0"
        ]
        +
        b3_step3e_df[
            "semantic_recovery_count"
        ]
    )
).all()


# ------------------------------------------------------------
# 8. Confirm C1 exactly reproduces frozen semantic-only S
# ------------------------------------------------------------

c1_3e = (
    b3_step3e_df[
        b3_step3e_df[
            "candidate_id"
        ]
        ==
        "C1"
    ]
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


frozen_s_3e = (
    b3_step3d_df[
        [
            "dataset_index",
            "S_count",
        ]
    ]
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


assert np.array_equal(
    c1_3e[
        "dataset_index"
    ]
    .to_numpy(),

    frozen_s_3e[
        "dataset_index"
    ]
    .to_numpy(),
)


assert np.allclose(
    c1_3e[
        "B0_plus_semantic_count"
    ]
    .to_numpy(
        dtype=float
    ),

    frozen_s_3e[
        "S_count"
    ]
    .to_numpy(
        dtype=float
    ),

    rtol=0.0,
    atol=1e-12,
), (
    "C1 reconstruction does not reproduce frozen S."
)


# ------------------------------------------------------------
# 9. Overall semantic-representation metrics
# ------------------------------------------------------------

overall_rows_3e = []


for candidate_id in (
    CANDIDATES_3E
):

    sdf = (
        b3_step3e_df[
            b3_step3e_df[
                "candidate_id"
            ]
            ==
            candidate_id
        ]
    )


    gt = sdf[
        "gt_count"
    ].to_numpy(
        dtype=float
    )


    pred = sdf[
        "B0_plus_semantic_count"
    ].to_numpy(
        dtype=float
    )


    err = (
        pred
        -
        gt
    )


    overall_rows_3e.append(
        {
            "candidate_id":
                candidate_id,

            "total_semantic_points":
                int(
                    sdf[
                        "semantic_candidate_count"
                    ]
                    .sum()
                ),

            "total_B0_covered":
                int(
                    sdf[
                        "semantic_points_covered_by_B0"
                    ]
                    .sum()
                ),

            "total_recovery_points":
                int(
                    sdf[
                        "semantic_recovery_count"
                    ]
                    .sum()
                ),

            "total_prediction":
                float(
                    pred.sum()
                ),

            "MAE":
                float(
                    np.mean(
                        np.abs(
                            err
                        )
                    )
                ),

            "RMSE":
                float(
                    np.sqrt(
                        np.mean(
                            err ** 2
                        )
                    )
                ),

            "mean_signed_error":
                float(
                    err.mean()
                ),

            "under_images":
                int(
                    (
                        err < 0
                    )
                    .sum()
                ),

            "exact_images":
                int(
                    np.isclose(
                        err,
                        0.0,
                    )
                    .sum()
                ),

            "over_images":
                int(
                    (
                        err > 0
                    )
                    .sum()
                ),
        }
    )


b3_step3e_overall_df = pd.DataFrame(
    overall_rows_3e
)


# ------------------------------------------------------------
# 10. Pairwise comparison against C1
# ------------------------------------------------------------

c1_lookup_3e = (
    c1_3e
    .set_index(
        "dataset_index"
    )
)


pairwise_rows_3e = []


for candidate_id in [
    "C2b",
    "C2c",
]:

    alt = (
        b3_step3e_df[
            b3_step3e_df[
                "candidate_id"
            ]
            ==
            candidate_id
        ]
        .set_index(
            "dataset_index"
        )
    )


    common_idx = (
        c1_lookup_3e.index
        .intersection(
            alt.index
        )
    )


    gt = (
        c1_lookup_3e.loc[
            common_idx,
            "gt_count",
        ]
        .to_numpy(
            dtype=float
        )
    )


    c1_abs = np.abs(
        c1_lookup_3e.loc[
            common_idx,
            "B0_plus_semantic_count",
        ]
        .to_numpy(
            dtype=float
        )
        -
        gt
    )


    alt_abs = np.abs(
        alt.loc[
            common_idx,
            "B0_plus_semantic_count",
        ]
        .to_numpy(
            dtype=float
        )
        -
        gt
    )


    delta = (
        alt_abs
        -
        c1_abs
    )


    pairwise_rows_3e.append(
        {
            "comparison":
                f"{candidate_id} - C1",

            "mean_abs_error_delta":
                float(
                    delta.mean()
                ),

            "improves_images":
                int(
                    (
                        delta < 0
                    )
                    .sum()
                ),

            "ties_images":
                int(
                    np.isclose(
                        delta,
                        0.0,
                    )
                    .sum()
                ),

            "worsens_images":
                int(
                    (
                        delta > 0
                    )
                    .sum()
                ),
        }
    )


b3_step3e_pairwise_df = pd.DataFrame(
    pairwise_rows_3e
)


# ------------------------------------------------------------
# 11. Density-stratum comparison
# ------------------------------------------------------------

DENSITY_ORDER_3E = [
    "S1_0_20",
    "S2_20_40",
    "S3_40_60",
    "S4_60_80",
    "S5_80_95",
    "S6_95_100",
]


density_rows_3e = []


for stratum in (
    DENSITY_ORDER_3E
):

    for candidate_id in (
        CANDIDATES_3E
    ):

        sdf = (
            b3_step3e_df[
                (
                    b3_step3e_df[
                        "density_stratum"
                    ]
                    ==
                    stratum
                )
                &
                (
                    b3_step3e_df[
                        "candidate_id"
                    ]
                    ==
                    candidate_id
                )
            ]
        )


        gt = sdf[
            "gt_count"
        ].to_numpy(
            dtype=float
        )


        pred = sdf[
            "B0_plus_semantic_count"
        ].to_numpy(
            dtype=float
        )


        err = (
            pred
            -
            gt
        )


        density_rows_3e.append(
            {
                "density_stratum":
                    stratum,

                "candidate_id":
                    candidate_id,

                "MAE":
                    float(
                        np.mean(
                            np.abs(
                                err
                            )
                        )
                    ),

                "RMSE":
                    float(
                        np.sqrt(
                            np.mean(
                                err ** 2
                            )
                        )
                    ),

                "mean_signed_error":
                    float(
                        err.mean()
                    ),
            }
        )


b3_step3e_density_df = pd.DataFrame(
    density_rows_3e
)


# ------------------------------------------------------------
# 12. Paired bootstrap: C2b/C2c vs C1
#
# Negative delta = alternative better than C1.
# ------------------------------------------------------------

BOOTSTRAP_REPS_3E = 10000
BOOTSTRAP_SEED_3E = 0


bootstrap_rows_3e = []


for j, candidate_id in enumerate(
    [
        "C2b",
        "C2c",
    ]
):

    alt = (
        b3_step3e_df[
            b3_step3e_df[
                "candidate_id"
            ]
            ==
            candidate_id
        ]
        .set_index(
            "dataset_index"
        )
    )


    common_idx = (
        c1_lookup_3e.index
        .intersection(
            alt.index
        )
    )


    gt = (
        c1_lookup_3e.loc[
            common_idx,
            "gt_count",
        ]
        .to_numpy(
            dtype=float
        )
    )


    c1_abs = np.abs(
        c1_lookup_3e.loc[
            common_idx,
            "B0_plus_semantic_count",
        ]
        .to_numpy(
            dtype=float
        )
        -
        gt
    )


    alt_abs = np.abs(
        alt.loc[
            common_idx,
            "B0_plus_semantic_count",
        ]
        .to_numpy(
            dtype=float
        )
        -
        gt
    )


    delta = (
        alt_abs
        -
        c1_abs
    )


    rng = np.random.default_rng(
        BOOTSTRAP_SEED_3E
        +
        j
    )


    boot_means = np.empty(
        BOOTSTRAP_REPS_3E,
        dtype=float,
    )


    for i in range(
        BOOTSTRAP_REPS_3E
    ):

        idx = rng.integers(
            0,
            len(
                delta
            ),
            size=len(
                delta
            ),
        )

        boot_means[
            i
        ] = (
            delta[
                idx
            ]
            .mean()
        )


    bootstrap_rows_3e.append(
        {
            "comparison":
                f"{candidate_id} - C1",

            "observed_mean_delta":
                float(
                    delta.mean()
                ),

            "CI_2.5pct":
                float(
                    np.quantile(
                        boot_means,
                        0.025,
                    )
                ),

            "CI_97.5pct":
                float(
                    np.quantile(
                        boot_means,
                        0.975,
                    )
                ),

            "bootstrap_fraction_delta_lt_0":
                float(
                    np.mean(
                        boot_means < 0
                    )
                ),
        }
    )


b3_step3e_bootstrap_df = pd.DataFrame(
    bootstrap_rows_3e
)


# ------------------------------------------------------------
# 13. Current SG reference for context only
# ------------------------------------------------------------

current_sg_3e = (
    b3_step3d_df[
        [
            "dataset_index",
            "gt_count",
            "SG_w1.00_count",
        ]
    ]
    .copy()
)


gt_sg_3e = (
    current_sg_3e[
        "gt_count"
    ]
    .to_numpy(
        dtype=float
    )
)


pred_sg_3e = (
    current_sg_3e[
        "SG_w1.00_count"
    ]
    .to_numpy(
        dtype=float
    )
)


current_sg_metrics_3e = pd.DataFrame(
    [
        {
            "system":
                "Current SG = B0+C1+G",

            "MAE":
                float(
                    np.mean(
                        np.abs(
                            pred_sg_3e
                            -
                            gt_sg_3e
                        )
                    )
                ),

            "RMSE":
                float(
                    np.sqrt(
                        np.mean(
                            (
                                pred_sg_3e
                                -
                                gt_sg_3e
                            )
                            ** 2
                        )
                    )
                ),
        }
    ]
)


# ------------------------------------------------------------
# 14. Save artifacts
# ------------------------------------------------------------

B3_STEP3E_POINT_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3E_semantic_recheck_points.csv"
)

B3_STEP3E_IMAGE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3E_semantic_recheck_per_image.csv"
)

B3_STEP3E_OVERALL_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3E_semantic_recheck_overall.csv"
)

B3_STEP3E_PAIRWISE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3E_semantic_recheck_pairwise.csv"
)

B3_STEP3E_DENSITY_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3E_semantic_recheck_by_density.csv"
)

B3_STEP3E_BOOTSTRAP_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3E_semantic_recheck_bootstrap.csv"
)


b3_step3e_point_df.to_csv(
    B3_STEP3E_POINT_FILE,
    index=False,
)

b3_step3e_df.to_csv(
    B3_STEP3E_IMAGE_FILE,
    index=False,
)

b3_step3e_overall_df.to_csv(
    B3_STEP3E_OVERALL_FILE,
    index=False,
)

b3_step3e_pairwise_df.to_csv(
    B3_STEP3E_PAIRWISE_FILE,
    index=False,
)

b3_step3e_density_df.to_csv(
    B3_STEP3E_DENSITY_FILE,
    index=False,
)

b3_step3e_bootstrap_df.to_csv(
    B3_STEP3E_BOOTSTRAP_FILE,
    index=False,
)


# ------------------------------------------------------------
# 15. Reports
# ------------------------------------------------------------

print("\nSemantic candidate totals / B0 recovery")
print("---------------------------------------")

display(
    b3_step3e_overall_df
)


print("\nPairwise semantic comparison against C1")
print("---------------------------------------")
print("Negative mean delta favours C2b/C2c")

display(
    b3_step3e_pairwise_df
)


print("\nMAE by density stratum")
print("----------------------")

display(
    b3_step3e_density_df
    .pivot(
        index=
            "density_stratum",

        columns=
            "candidate_id",

        values=
            "MAE",
    )
)


print("\nPaired bootstrap against C1")
print("---------------------------")
print("Negative delta favours alternative semantic representation")

display(
    b3_step3e_bootstrap_df
)


print("\nCurrent SG reference — context only")
print("-----------------------------------")

display(
    current_sg_metrics_3e
)


# ------------------------------------------------------------
# 16. Protocol report
# ------------------------------------------------------------

print("\nSemantic representations tested")
print("-------------------------------")
print("C1                           : 4-connected A3c components")
print("C2b                          : spatial watershed alpha=0.010")
print("C2c                          : spatial watershed alpha=0.020")

print("\nArchitecture scope")
print("------------------")
print("B0 anchor frozen              : YES")
print("Semantic evidence frozen      : YES")
print("Geometry applied in 3E-A      : NO")
print("Reason                        : avoid confounding C2 watershed split with C1-derived G2 split")

print("\nC1 reproduces frozen S         : PASS")
print("New SAN inference              : NO")
print("New SAM2 inference             : NO")
print("New Marigold inference         : NO")
print("Density routing                : NO")
print("GT routing                     : NO")
print("Test set accessed              : NO")

print("\nB3 Step 3E-A: PASS")

========================================================================================================================
B3 STEP 3E-A — SEMANTIC REPRESENTATION RECHECK
========================================================================================================================

Semantic candidate totals / B0 recovery
---------------------------------------

,candidate_id,total_semantic_points,total_B0_covered,total_recovery_points,total_prediction,MAE,RMSE,mean_signed_error,under_images,exact_images,over_images
0,C1,2554,1339,1215,3513.0,72.00,262.235314,-65.32,52,5,43
1,C2b,6074,2949,3125,5423.0,77.64,257.181376,-46.22,28,2,70
2,C2c,4171,2080,2091,4389.0,72.76,259.554002,-56.56,35,3,62

Pairwise semantic comparison against C1
---------------------------------------
Negative mean delta favours C2b/C2c

,comparison,mean_abs_error_delta,improves_images,ties_images,worsens_images
0,C2b - C1,5.64,29,21,50
1,C2c - C1,0.76,32,25,43

MAE by density stratum
----------------------

candidate_id         C1     C2b     C2c
density_stratum
S1_0_20            4.55   16.25   10.10
S2_20_40           5.60   19.30   11.15
S3_40_60           8.95   28.90   15.20
S4_60_80          24.15   23.65   20.55
S5_80_95          44.60   39.30   37.30
S6_95_100        588.90  560.90  576.30

Paired bootstrap against C1
---------------------------
Negative delta favours alternative semantic representation

,comparison,observed_mean_delta,CI_2.5pct,CI_97.5pct,bootstrap_fraction_delta_lt_0
0,C2b - C1,5.64,1.11000,10.1305,0.0085
1,C2c - C1,0.76,-1.37025,2.8900,0.2435

Current SG reference — context only
-----------------------------------

                 system    MAE        RMSE
0  Current SG = B0+C1+G  61.93  246.585219

Semantic representations tested
-------------------------------
C1                           : 4-connected A3c components
C2b                          : spatial watershed alpha=0.010
C2c                          : spatial watershed alpha=0.020

Architecture scope
------------------
B0 anchor frozen              : YES
Semantic evidence frozen      : YES
Geometry applied in 3E-A      : NO
Reason                        : avoid confounding C2 watershed split with C1-derived G2 split

C1 reproduces frozen S         : PASS
New SAN inference              : NO
New SAM2 inference             : NO
New Marigold inference         : NO
Density routing                : NO
GT routing                     : NO
Test set accessed              : NO

B3 Step 3E-A: PASS

### **Finding 23:**

The semantic-representation recheck confirms the earlier trade-off observed during Group-C development.

C1 remains the most balanced representation overall and is substantially more reliable in sparse and moderate-density scenes.

C2b/C2c can improve dense-scene recovery, but their more aggressive subdivision increases over-counting and degrades S1–S3 performance.

Since C2c does not provide a robust overall improvement over C1, and C2b is clearly worse overall, C1 is retained as the semantic representation for the primary SG architecture.

In [ ]:
# ============================================================
# B3 Step 3F — Final SG Candidate Freeze and Ablation Summary
# ============================================================
#
# Purpose
# -------
# Consolidate the completed B3 development evidence and freeze
# the primary SG candidate for held-out FSC-147 validation.
#
#
# Primary frozen candidate:
#
#     SG_v1 = B0 + C1 + adaptive G2
#
# where:
#
#   B0  = unguided SAM2 anchor
#   C1  = A3c 4-connected semantic recovery
#   G2  = Marigold geometry refinement
#
# Geometry rule:
#
#   apply full G2 extra multiplicity when
#
#       geometry_extra_per_refinable_component >= 5.0
#
#
# Frozen settings
# ---------------
#   semantic candidate          = C1
#   candidate quantile          = 0.75
#   G2 satellite threshold      = 0.001
#   Stage-1 gate                = removed
#   Stage-2 threshold           = 5.0
#   geometry weight             = 1.0
#   geometry cap                = none
#   D in primary SG             = no
#
#
# Optional architecture variant:
#
#     SDG = B0 + C1 + D + G
#
#
# IMPORTANT
# ---------
#
# Step 3F performs:
#   - NO parameter tuning
#   - NO new inference
#   - NO test access
#
# It freezes the development-stage candidate for:
#
#   NEXT STAGE:
#       held-out FSC-147 validation
#
# ============================================================

import json
from pathlib import Path

import numpy as np
import pandas as pd


print("=" * 120)
print("B3 STEP 3F — FINAL SG CANDIDATE FREEZE AND ABLATION SUMMARY")
print("=" * 120)


# ------------------------------------------------------------
# 1. Guards
# ------------------------------------------------------------

required_globals_3f = [
    "b3_step2e_df",
    "b3_step3b_overall_df",
    "b3_step3c_overall_df",
    "b3_step3d_df",
    "b3_step3d_overall_df",
    "b3_step3e_overall_df",
    "B3_TABLES_DIR",
    "B3_METADATA_DIR",
]

for name in required_globals_3f:
    assert name in globals(), (
        f"{name} unavailable. Run the corresponding earlier B3 step first."
    )


assert len(
    b3_step3d_df
) == 100


# ------------------------------------------------------------
# 2. Canonical per-image architecture table
# ------------------------------------------------------------

# Primary B0/S/SG values come from the final Step-3D state.
b3_step3f_df = (
    b3_step3d_df[
        [
            "dataset_index",
            "image_id",
            "category",
            "density_stratum",
            "gt_count",
            "S_count",
            "SG_w1.00_count",
        ]
    ]
    .copy()
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


# Recover B0 and optional SDG from Step 2E.
step2e_3f = (
    b3_step2e_df[
        [
            "dataset_index",
            "B0_count",
            "SDG_B0_C1_D_G_count",
        ]
    ]
    .copy()
    .sort_values(
        "dataset_index"
    )
    .reset_index(
        drop=True
    )
)


assert np.array_equal(
    b3_step3f_df[
        "dataset_index"
    ].to_numpy(),

    step2e_3f[
        "dataset_index"
    ].to_numpy(),
)


b3_step3f_df[
    "B0_count"
] = step2e_3f[
    "B0_count"
].to_numpy(
    dtype=float
)


b3_step3f_df[
    "SG_count"
] = b3_step3f_df[
    "SG_w1.00_count"
].to_numpy(
    dtype=float
)


b3_step3f_df[
    "SDG_count"
] = step2e_3f[
    "SDG_B0_C1_D_G_count"
].to_numpy(
    dtype=float
)


# ------------------------------------------------------------
# 3. Exact regression checks
# ------------------------------------------------------------

gt_3f = (
    b3_step3f_df[
        "gt_count"
    ]
    .to_numpy(
        dtype=float
    )
)


def calc_metrics_3f(
    pred,
):

    pred = np.asarray(
        pred,
        dtype=float,
    )

    err = (
        pred
        -
        gt_3f
    )

    return {
        "total_prediction":
            float(
                pred.sum()
            ),

        "mean_prediction":
            float(
                pred.mean()
            ),

        "MAE":
            float(
                np.mean(
                    np.abs(
                        err
                    )
                )
            ),

        "RMSE":
            float(
                np.sqrt(
                    np.mean(
                        err ** 2
                    )
                )
            ),

        "mean_signed_error":
            float(
                err.mean()
            ),

        "under_images":
            int(
                (
                    err < 0
                )
                .sum()
            ),

        "exact_images":
            int(
                np.isclose(
                    err,
                    0.0,
                )
                .sum()
            ),

        "over_images":
            int(
                (
                    err > 0
                )
                .sum()
            ),
    }


architecture_specs_3f = [
    (
        "B0",
        "B0",
        "B0_count",
    ),

    (
        "S",
        "B0 + C1",
        "S_count",
    ),

    (
        "SG",
        "B0 + C1 + G",
        "SG_count",
    ),

    (
        "SDG",
        "B0 + C1 + D + G",
        "SDG_count",
    ),
]


architecture_rows_3f = []


for architecture_id, formula, pred_col in (
    architecture_specs_3f
):

    metrics = calc_metrics_3f(
        b3_step3f_df[
            pred_col
        ]
    )

    architecture_rows_3f.append(
        {
            "architecture":
                architecture_id,

            "formula":
                formula,

            **metrics,
        }
    )


b3_step3f_architecture_df = pd.DataFrame(
    architecture_rows_3f
)


# Expected regression values from earlier B3 steps.
expected_mae_3f = {
    "B0":
        80.69,

    "S":
        72.00,

    "SG":
        61.93,

    "SDG":
        61.63,
}


for architecture_id, expected in (
    expected_mae_3f.items()
):

    observed = float(
        b3_step3f_architecture_df.loc[
            b3_step3f_architecture_df[
                "architecture"
            ]
            ==
            architecture_id,
            "MAE",
        ]
        .iloc[
            0
        ]
    )

    assert np.isclose(
        observed,
        expected,
        atol=1e-8,
    ), (
        f"{architecture_id} MAE mismatch: "
        f"expected {expected}, got {observed}"
    )


# ------------------------------------------------------------
# 4. Add development-stage deltas
# ------------------------------------------------------------

B0_MAE_3F = float(
    b3_step3f_architecture_df.loc[
        b3_step3f_architecture_df[
            "architecture"
        ]
        ==
        "B0",
        "MAE",
    ]
    .iloc[
        0
    ]
)


S_MAE_3F = float(
    b3_step3f_architecture_df.loc[
        b3_step3f_architecture_df[
            "architecture"
        ]
        ==
        "S",
        "MAE",
    ]
    .iloc[
        0
    ]
)


b3_step3f_architecture_df[
    "delta_MAE_vs_B0"
] = (
    b3_step3f_architecture_df[
        "MAE"
    ]
    -
    B0_MAE_3F
)


b3_step3f_architecture_df[
    "delta_MAE_vs_S"
] = (
    b3_step3f_architecture_df[
        "MAE"
    ]
    -
    S_MAE_3F
)


# ------------------------------------------------------------
# 5. Major ablation evidence summary
# ------------------------------------------------------------

ablation_rows_3f = []


# --------------------------------------------------------
# A. Semantic representation
# --------------------------------------------------------

semantic_lookup_3f = (
    b3_step3e_overall_df
    .set_index(
        "candidate_id"
    )
)


for candidate_id in [
    "C1",
    "C2b",
    "C2c",
]:

    ablation_rows_3f.append(
        {
            "ablation_group":
                "semantic_representation",

            "variant":
                candidate_id,

            "MAE":
                float(
                    semantic_lookup_3f.loc[
                        candidate_id,
                        "MAE",
                    ]
                ),

            "RMSE":
                float(
                    semantic_lookup_3f.loc[
                        candidate_id,
                        "RMSE",
                    ]
                ),

            "selected":
                bool(
                    candidate_id
                    ==
                    "C1"
                ),

            "interpretation":
                (
                    "C1 retained as balanced semantic recovery"
                    if candidate_id == "C1"
                    else
                    "alternative semantic subdivision"
                ),
        }
    )


# --------------------------------------------------------
# B. Gate structure
# --------------------------------------------------------

gate_lookup_3f = (
    b3_step3b_overall_df
    .set_index(
        "system"
    )
)


for system_name in [
    "SG-Stage1-only",
    "SG-Stage2-only",
    "SG-Stage1+Stage2",
]:

    row = gate_lookup_3f.loc[
        system_name
    ]

    ablation_rows_3f.append(
        {
            "ablation_group":
                "gate_structure",

            "variant":
                system_name,

            "MAE":
                float(
                    row[
                        "MAE"
                    ]
                ),

            "RMSE":
                float(
                    row[
                        "RMSE"
                    ]
                ),

            "selected":
                bool(
                    system_name
                    ==
                    "SG-Stage2-only"
                ),

            "interpretation":
                (
                    "Stage 2 retained; Stage 1 redundant"
                    if system_name == "SG-Stage2-only"
                    else
                    "gate-structure comparison"
                ),
        }
    )


# --------------------------------------------------------
# C. Stage-2 threshold
# --------------------------------------------------------

threshold_lookup_3f = (
    b3_step3c_overall_df
    .set_index(
        "system"
    )
)


for system_name in [
    "SG-t4",
    "SG-t5",
    "SG-t6",
]:

    row = threshold_lookup_3f.loc[
        system_name
    ]

    ablation_rows_3f.append(
        {
            "ablation_group":
                "stage2_threshold",

            "variant":
                system_name,

            "MAE":
                float(
                    row[
                        "MAE"
                    ]
                ),

            "RMSE":
                float(
                    row[
                        "RMSE"
                    ]
                ),

            "selected":
                bool(
                    system_name
                    ==
                    "SG-t5"
                ),

            "interpretation":
                (
                    "t=5 retained after coarse sensitivity check"
                    if system_name == "SG-t5"
                    else
                    "coarse neighboring threshold"
                ),
        }
    )


# --------------------------------------------------------
# D. Geometry weight
# --------------------------------------------------------

weight_lookup_3f = (
    b3_step3d_overall_df
    .set_index(
        "system"
    )
)


for system_name in [
    "SG-w0.5",
    "SG-w1.0",
]:

    row = weight_lookup_3f.loc[
        system_name
    ]

    ablation_rows_3f.append(
        {
            "ablation_group":
                "geometry_weight",

            "variant":
                system_name,

            "MAE":
                float(
                    row[
                        "MAE"
                    ]
                ),

            "RMSE":
                float(
                    row[
                        "RMSE"
                    ]
                ),

            "selected":
                bool(
                    system_name
                    ==
                    "SG-w1.0"
                ),

            "interpretation":
                (
                    "full geometry multiplicity retained"
                    if system_name == "SG-w1.0"
                    else
                    "conservative half correction"
                ),
        }
    )


b3_step3f_ablation_df = pd.DataFrame(
    ablation_rows_3f
)


# ------------------------------------------------------------
# 6. Density-stratum summary for frozen architectures
# ------------------------------------------------------------

STRATUM_ORDER_3F = [
    "S1_0_20",
    "S2_20_40",
    "S3_40_60",
    "S4_60_80",
    "S5_80_95",
    "S6_95_100",
]


density_rows_3f = []


for stratum in (
    STRATUM_ORDER_3F
):

    sdf = (
        b3_step3f_df[
            b3_step3f_df[
                "density_stratum"
            ]
            ==
            stratum
        ]
    )


    gt = (
        sdf[
            "gt_count"
        ]
        .to_numpy(
            dtype=float
        )
    )


    for architecture_id, formula, pred_col in (
        architecture_specs_3f
    ):

        pred = (
            sdf[
                pred_col
            ]
            .to_numpy(
                dtype=float
            )
        )

        err = (
            pred
            -
            gt
        )


        density_rows_3f.append(
            {
                "density_stratum":
                    stratum,

                "architecture":
                    architecture_id,

                "MAE":
                    float(
                        np.mean(
                            np.abs(
                                err
                            )
                        )
                    ),

                "RMSE":
                    float(
                        np.sqrt(
                            np.mean(
                                err ** 2
                            )
                        )
                    ),

                "mean_signed_error":
                    float(
                        err.mean()
                    ),
            }
        )


b3_step3f_density_df = pd.DataFrame(
    density_rows_3f
)


# ------------------------------------------------------------
# 7. Freeze manifest
# ------------------------------------------------------------

SG_V1_CONFIG_3F = {

    "architecture_id":
        "SG_v1",

    "architecture_formula":
        "B0 + C1 + adaptive G2",

    "status":
        "FROZEN_FOR_HELDOUT_FSC147_VALIDATION",

    "development_dataset":
        "FSC-147 validation dev100",

    "development_num_images":
        100,


    "B0": {
        "role":
            "unguided SAM2 anchor counter",

        "model":
            "SAM2.1 Hiera-Small",

        "count_definition":
            "native AMG mask count",

        "additional_post_filter":
            False,
    },


    "semantic": {
        "candidate":
            "C1",

        "source":
            "A3c semantic mask",

        "representation":
            "4-connected components",

        "recovery_definition":
            "C1 component centroid outside B0 mask support",

        "component_weight":
            1.0,
    },


    "geometry": {
        "depth_model":
            "prs-eth/marigold-depth-v1-1",

        "variant":
            "G2",

        "candidate_component_quantile":
            0.75,

        "satellite_parent_area_fraction_threshold":
            0.001,

        "gate_feature":
            "geometry_extra_per_refinable_component",

        "gate_threshold":
            5.0,

        "stage1_gate":
            None,

        "correction_weight":
            1.0,

        "correction_cap":
            None,
    },


    "D_branch": {
        "included_in_primary_SG":
            False,

        "optional_variant":
            "SDG",
    },


    "routing": {
        "density_based":
            False,

        "GT_based":
            False,

        "category_specific":
            False,
    },


    "development_reference_metrics": {

        "B0_MAE":
            float(
                b3_step3f_architecture_df.loc[
                    b3_step3f_architecture_df[
                        "architecture"
                    ]
                    ==
                    "B0",
                    "MAE",
                ]
                .iloc[
                    0
                ]
            ),

        "S_MAE":
            float(
                b3_step3f_architecture_df.loc[
                    b3_step3f_architecture_df[
                        "architecture"
                    ]
                    ==
                    "S",
                    "MAE",
                ]
                .iloc[
                    0
                ]
            ),

        "SG_MAE":
            float(
                b3_step3f_architecture_df.loc[
                    b3_step3f_architecture_df[
                        "architecture"
                    ]
                    ==
                    "SG",
                    "MAE",
                ]
                .iloc[
                    0
                ]
            ),

        "SG_RMSE":
            float(
                b3_step3f_architecture_df.loc[
                    b3_step3f_architecture_df[
                        "architecture"
                    ]
                    ==
                    "SG",
                    "RMSE",
                ]
                .iloc[
                    0
                ]
            ),

        "SDG_MAE":
            float(
                b3_step3f_architecture_df.loc[
                    b3_step3f_architecture_df[
                        "architecture"
                    ]
                    ==
                    "SDG",
                    "MAE",
                ]
                .iloc[
                    0
                ]
            ),

        "SDG_RMSE":
            float(
                b3_step3f_architecture_df.loc[
                    b3_step3f_architecture_df[
                        "architecture"
                    ]
                    ==
                    "SDG",
                    "RMSE",
                ]
                .iloc[
                    0
                ]
            ),
    },


    "validation_policy": {

        "next_stage":
            "remaining FSC-147 validation images not in dev100",

        "parameters_may_be_retuned_before_validation":
            False,

        "primary_architecture":
            "SG_v1",

        "optional_variant_to_evaluate":
            "SDG",

        "FSC147_test_set_reserved":
            True,

        "test_set_accessed":
            False,
    },
}


# ------------------------------------------------------------
# 8. Save final development-stage artifacts
# ------------------------------------------------------------

B3_STEP3F_PER_IMAGE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3F_frozen_architectures_per_image.csv"
)

B3_STEP3F_ARCHITECTURE_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3F_architecture_summary.csv"
)

B3_STEP3F_ABLATION_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3F_major_ablation_summary.csv"
)

B3_STEP3F_DENSITY_FILE = (
    B3_TABLES_DIR
    /
    "B3_step3F_architecture_by_density.csv"
)

B3_STEP3F_CONFIG_FILE = (
    B3_METADATA_DIR
    /
    "SG_v1_frozen_config.json"
)


b3_step3f_df.to_csv(
    B3_STEP3F_PER_IMAGE_FILE,
    index=False,
)


b3_step3f_architecture_df.to_csv(
    B3_STEP3F_ARCHITECTURE_FILE,
    index=False,
)


b3_step3f_ablation_df.to_csv(
    B3_STEP3F_ABLATION_FILE,
    index=False,
)


b3_step3f_density_df.to_csv(
    B3_STEP3F_DENSITY_FILE,
    index=False,
)


with open(
    B3_STEP3F_CONFIG_FILE,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        SG_V1_CONFIG_3F,
        f,
        indent=2,
    )


# ------------------------------------------------------------
# 9. Reports
# ------------------------------------------------------------

print("\nFinal development-stage architecture comparison")
print("-----------------------------------------------")

display(
    b3_step3f_architecture_df[
        [
            "architecture",
            "formula",
            "total_prediction",
            "MAE",
            "RMSE",
            "mean_signed_error",
            "under_images",
            "exact_images",
            "over_images",
            "delta_MAE_vs_B0",
            "delta_MAE_vs_S",
        ]
    ]
)


print("\nMajor architecture ablations")
print("----------------------------")

display(
    b3_step3f_ablation_df
)


print("\nFrozen architectures — MAE by density stratum")
print("----------------------------------------------")

display(
    b3_step3f_density_df
    .pivot(
        index=
            "density_stratum",

        columns=
            "architecture",

        values=
            "MAE",
    )
)


# ------------------------------------------------------------
# 10. Freeze declaration
# ------------------------------------------------------------

print("\n" + "=" * 120)
print("SG_v1 FREEZE DECLARATION")
print("=" * 120)

print("\nPrimary architecture")
print("--------------------")
print("SG_v1 = B0 + C1 + adaptive G2")

print("\nFrozen design choices")
print("---------------------")
print("Semantic representation            : C1")
print("Geometry variant                   : G2")
print("Candidate component quantile       : 0.75")
print("Satellite threshold                : 0.001")
print("Stage-1 gate                       : REMOVED")
print("Stage-2 feature                    : geometry_extra_per_refinable_component")
print("Stage-2 threshold                  : 5.0")
print("Geometry correction weight         : 1.0")
print("Geometry correction cap            : NONE")
print("D included in primary architecture : NO")

print("\nOptional architecture variant")
print("-----------------------------")
print("SDG = B0 + C1 + D + G")

print("\nDevelopment protocol")
print("--------------------")
print("dev100 further tuning allowed       : NO")
print("New inference in Step 3F            : NO")
print("FSC-147 test accessed               : NO")
print("Next stage                          : held-out FSC-147 validation")

print("\nSaved")
print("-----")
print(" ", B3_STEP3F_PER_IMAGE_FILE)
print(" ", B3_STEP3F_ARCHITECTURE_FILE)
print(" ", B3_STEP3F_ABLATION_FILE)
print(" ", B3_STEP3F_DENSITY_FILE)
print(" ", B3_STEP3F_CONFIG_FILE)

print("\nB3 Step 3F: PASS")

========================================================================================================================
B3 STEP 3F — FINAL SG CANDIDATE FREEZE AND ABLATION SUMMARY
========================================================================================================================

Final development-stage architecture comparison
-----------------------------------------------

,architecture,formula,total_prediction,MAE,RMSE,mean_signed_error,under_images,exact_images,over_images,delta_MAE_vs_B0,delta_MAE_vs_S
0,B0,B0,2298.0,80.69,270.233880,-77.47,76,4,20,0.00,8.69
1,S,B0 + C1,3513.0,72.00,262.235314,-65.32,52,5,43,-8.69,0.00
2,SG,B0 + C1 + G,4718.0,61.93,246.585219,-53.27,47,5,48,-18.76,-10.07
3,SDG,B0 + C1 + D + G,5047.0,61.63,245.550993,-49.98,40,7,53,-19.06,-10.37

Major architecture ablations
----------------------------

,ablation_group,variant,MAE,RMSE,selected,interpretation
0,semantic_representation,C1,72.000,262.235314,True,C1 retained as balanced semantic recovery
1,semantic_representation,C2b,77.640,257.181376,False,alternative semantic subdivision
2,semantic_representation,C2c,72.760,259.554002,False,alternative semantic subdivision
3,gate_structure,SG-Stage1-only,63.170,246.008354,False,gate-structure comparison
4,gate_structure,SG-Stage2-only,61.930,246.585219,True,Stage 2 retained; Stage 1 redundant
5,gate_structure,SG-Stage1+Stage2,61.930,246.585219,False,gate-structure comparison
6,stage2_threshold,SG-t4,62.430,246.057453,False,coarse neighboring threshold
7,stage2_threshold,SG-t5,61.930,246.585219,True,t=5 retained after coarse sensitivity check
8,stage2_threshold,SG-t6,63.890,247.704683,False,coarse neighboring threshold
9,geometry_weight,SG-w0.5,66.665,252.252042,False,conservative half correction
10,geometry_weight,SG-w1.0,61.930,246.585219,True,full geometry multiplicity retained

Frozen architectures — MAE by density stratum
----------------------------------------------

architecture         B0       S      SDG      SG
density_stratum
S1_0_20            5.15    4.55    6.975    5.95
S2_20_40           6.55    5.60    9.150    6.80
S3_40_60          14.95    8.95    9.700    8.70
S4_60_80          34.30   24.15   19.475   22.40
S5_80_95          62.10   44.60   38.450   40.60
S6_95_100        622.90  588.90  487.250  491.00

========================================================================================================================
SG_v1 FREEZE DECLARATION
========================================================================================================================

Primary architecture
--------------------
SG_v1 = B0 + C1 + adaptive G2

Frozen design choices
---------------------
Semantic representation            : C1
Geometry variant                   : G2
Candidate component quantile       : 0.75
Satellite threshold                : 0.001
Stage-1 gate                       : REMOVED
Stage-2 feature                    : geometry_extra_per_refinable_component
Stage-2 threshold                  : 5.0
Geometry correction weight         : 1.0
Geometry correction cap            : NONE
D included in primary architecture : NO

Optional architecture variant
-----------------------------
SDG = B0 + C1 + D + G

Development protocol
--------------------
dev100 further tuning allowed       : NO
New inference in Step 3F            : NO
FSC-147 test accessed               : NO
Next stage                          : held-out FSC-147 validation

Saved
-----
  /content/drive/MyDrive/MSc_Project_ZeroShot_Counting/results/B3_B0_B2_M_Geometry_Integration/tables/B3_step3F_frozen_architectures_per_image.csv
  /content/drive/MyDrive/MSc_Project_ZeroShot_Counting/results/B3_B0_B2_M_Geometry_Integration/tables/B3_step3F_architecture_summary.csv
  /content/drive/MyDrive/MSc_Project_ZeroShot_Counting/results/B3_B0_B2_M_Geometry_Integration/tables/B3_step3F_major_ablation_summary.csv
  /content/drive/MyDrive/MSc_Project_ZeroShot_Counting/results/B3_B0_B2_M_Geometry_Integration/tables/B3_step3F_architecture_by_density.csv
  /content/drive/MyDrive/MSc_Project_ZeroShot_Counting/results/B3_B0_B2_M_Geometry_Integration/metadata/SG_v1_frozen_config.json

B3 Step 3F: PASS

# Erratum — SG_v1 Stage-1 Gate (added 5 Oct 2026)

## What was recorded

The Step 3F freeze declaration and `SG_v1_frozen_config.json` record:

- `Stage-1 gate : REMOVED` / `"stage1_gate": null`

## What the code actually does

The Stage-1 gate (`candidate_area_fraction >= 0.85`) is **embedded in the definition of a refinable component** (Step 2A):

    geometry_refinable = geometry_split_candidate AND (candidate_area_fraction >= 0.85)

Both the Stage-2 feature (`geometry_extra_per_refinable_component`) and the added units (`G2_extra_units_refinable_only`) are computed over refinable components only. In any image failing Stage 1 there are zero refinable components, so Stage 2 cannot activate.

Evidence (Step 3B gate-structure output): `Stage2-only` and `Stage1+Stage2` activate on the **same 16 images** with the **same 1,205 extra units**. They are the same rule.

## Consequences

1. **SG_v1 = B0 + C1 + adaptive G2 with Stage-1 AND Stage-2 gates.** All reported SG_v1 results (dev100 MAE 61.93) are correct for this behaviour. Only the documentation was wrong.
2. **A genuinely Stage-2-only rule** (refinable = split candidate alone) **was never tested.** The Step 3B ablation does not show that Stage 1 is unnecessary, and the dissertation must not claim it was removed.
3. `SG_v1_frozen_config.json` is corrected by the cell below. The original file is preserved as `SG_v1_frozen_config_original.json`.

## No change to

- any count, metric, or per-image result
- any frozen parameter value
- the dev100 subset or the test-set reservation

## Next

The SG double-counting fix (SG_v1.1) and the end-to-end pipeline rebuild continue in notebook `B3R_SG_Rebuild_and_Fixes.ipynb`.

In [2]:
# ============================================================
# Erratum — Correct SG_v1 Stage-1 gate documentation
# ============================================================
#
# Documentation-only correction.
# No counts, metrics or parameters change.
# Safe to run on its own (no GPU, no prior cells needed).
# ============================================================

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

B3_METADATA_DIR = Path(
    "/content/drive/MyDrive/MSc_Project_ZeroShot_Counting"
    "/results/B3_B0_B2_M_Geometry_Integration/metadata"
)

CONFIG_FILE = B3_METADATA_DIR / "SG_v1_frozen_config.json"
ORIGINAL_BACKUP = B3_METADATA_DIR / "SG_v1_frozen_config_original.json"

assert CONFIG_FILE.exists(), f"Config not found: {CONFIG_FILE}"


# ------------------------------------------------------------
# 1. Preserve the original exactly once
# ------------------------------------------------------------

if not ORIGINAL_BACKUP.exists():
    shutil.copy2(CONFIG_FILE, ORIGINAL_BACKUP)
    print("Original preserved :", ORIGINAL_BACKUP.name)
else:
    print("Original already preserved — backup not overwritten.")


# ------------------------------------------------------------
# 2. Load from the ORIGINAL (so re-running is idempotent)
# ------------------------------------------------------------

with open(ORIGINAL_BACKUP, "r") as f:
    config = json.load(f)

assert config["architecture_id"] == "SG_v1"
assert config["geometry"]["stage1_gate"] is None, (
    "Unexpected original value — inspect before correcting."
)


# ------------------------------------------------------------
# 3. Correct the Stage-1 gate entry
# ------------------------------------------------------------

config["geometry"]["stage1_gate"] = {
    "feature": "candidate_area_fraction",
    "definition": (
        "sum of split-candidate A3c component area / "
        "total A3c foreground area"
    ),
    "operator": ">=",
    "threshold": 0.85,
    "implementation": (
        "Embedded in the refinable-component definition: "
        "geometry_refinable = geometry_split_candidate AND "
        "(candidate_area_fraction >= 0.85). Stage-2 feature and "
        "added units are computed over refinable components only."
    ),
}

config["erratum"] = {
    "date_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    "field_corrected": "geometry.stage1_gate",
    "original_value": None,
    "reason": (
        "Freeze declaration recorded Stage-1 as REMOVED, but Stage-1 is "
        "embedded in the refinable definition. Step 3B confirms "
        "Stage2-only == Stage1+Stage2 (16 images, 1205 extra units)."
    ),
    "behaviour_changed": False,
    "results_changed": False,
    "stage2_only_rule_tested": False,
}


# ------------------------------------------------------------
# 4. Save corrected config
# ------------------------------------------------------------

with open(CONFIG_FILE, "w") as f:
    json.dump(config, f, indent=2)


# ------------------------------------------------------------
# 5. Confirmation
# ------------------------------------------------------------

print("=" * 80)
print("SG_v1 CONFIG ERRATUM APPLIED")
print("=" * 80)
print("Corrected file     :", CONFIG_FILE.name)
print("Original preserved :", ORIGINAL_BACKUP.name)
print("\nCorrected stage1_gate:")
print(json.dumps(config["geometry"]["stage1_gate"], indent=2))
print("\nBehaviour changed  : NO")
print("Results changed    : NO")

Original preserved : SG_v1_frozen_config_original.json
================================================================================
SG_v1 CONFIG ERRATUM APPLIED
================================================================================
Corrected file     : SG_v1_frozen_config.json
Original preserved : SG_v1_frozen_config_original.json

Corrected stage1_gate:
{
  "feature": "candidate_area_fraction",
  "definition": "sum of split-candidate A3c component area / total A3c foreground area",
  "operator": ">=",
  "threshold": 0.85,
  "implementation": "Embedded in the refinable-component definition: geometry_refinable = geometry_split_candidate AND (candidate_area_fraction >= 0.85). Stage-2 feature and added units are computed over refinable components only."
}

Behaviour changed  : NO
Results changed    : NO